import { withLocaleFallback } from "@/lib/i18n";

/**
 * Shared site chrome copy — the primary navigation, header action buttons, the
 * two footers (marketing + legal), and a few common states/errors. Kept in one
 * place so every page (client landing/pricing via `useLocale`, and server pages
 * like affiliate/blog/legal via `getServerLocale`) switches language from a
 * single source of truth. Brand/product names (Dralvo, TiGold, Affiliate, Blog)
 * are intentionally left untranslated.
 */
export const COMMON_COPY = withLocaleFallback({
  "pt-BR": {
    nav: {
      products: "Produtos",
      performance: "Desempenho",
      tools: "Ferramentas",
      pricing: "Preços",
      blog: "Blog",
      affiliate: "Affiliate",
      tigold: "TiGold",
    },
    actions: {
      freeTrial: "Começar grátis",
      signUp: "Cadastrar",
      signIn: "Entrar",
      redirecting: "Redirecionando...",
    },
    installApp: {
      button: "Instalar app",
      iosTitle: "Instalar o Dralvo na tela inicial",
      iosStep1: "Toque no botão Compartilhar no Safari",
      iosStep2: 'Escolha "Adicionar à Tela de Início"',
      iosStep3: "Toque em Adicionar — pronto!",
    },
    footer: {
      productTitle: "Produto",
      companyTitle: "Empresa",
      legalTitle: "Jurídico",
      tagline:
        "Inteligência de decisão em ouro construída a partir de evidências de mercado rastreáveis. Apenas informativo, nunca aconselhamento financeiro.",
      rights: "© 2026 Dralvo. Todos os direitos reservados.",
      notAdvice: "© 2026 Dralvo. Não constitui aconselhamento financeiro.",
      pastPerformance: "Desempenho passado ≠ resultados futuros.",
      links: {
        blog: "Blog",
        methodology: "Metodologia",
        tigold: "TiGold",
        affiliate: "Affiliate",
        pricing: "Preços",
        trackRecord: "Histórico",
        signIn: "Entrar",
        createAccount: "Criar conta",
        privacy: "Privacidade",
        terms: "Termos",
        disclaimer: "Aviso legal",
      },
    },
    errors: {
      checkoutFailed: "Não foi possível criar uma sessão de checkout. Tente novamente.",
      connection: "Erro de conexão. Tente novamente.",
    },
  },
  es: {
    nav: {
      products: "Productos",
      performance: "Rendimiento",
      tools: "Herramientas",
      pricing: "Precios",
      blog: "Blog",
      affiliate: "Affiliate",
      tigold: "TiGold",
    },
    actions: {
      freeTrial: "Comenzar gratis",
      signUp: "Crear cuenta",
      signIn: "Iniciar sesión",
      redirecting: "Redirigiendo...",
    },
    installApp: {
      button: "Instalar app",
      iosTitle: "Instalar Dralvo en la pantalla de inicio",
      iosStep1: "Toque el botón Compartir en Safari",
      iosStep2: 'Elija "Añadir a pantalla de inicio"',
      iosStep3: "Toque Añadir — ¡listo!",
    },
    footer: {
      productTitle: "Producto",
      companyTitle: "Empresa",
      legalTitle: "Legal",
      tagline:
        "Inteligencia de decisiones sobre el oro construida a partir de evidencia de mercado trazable. Solo con fines informativos, nunca asesoramiento financiero.",
      rights: "© 2026 Dralvo. Todos los derechos reservados.",
      notAdvice: "© 2026 Dralvo. No constituye asesoramiento financiero.",
      pastPerformance: "El rendimiento pasado ≠ resultados futuros.",
      links: {
        blog: "Blog",
        methodology: "Metodología",
        tigold: "TiGold",
        affiliate: "Affiliate",
        pricing: "Precios",
        trackRecord: "Historial",
        signIn: "Iniciar sesión",
        createAccount: "Crear cuenta",
        privacy: "Privacidad",
        terms: "Términos",
        disclaimer: "Aviso legal",
      },
    },
    errors: {
      checkoutFailed: "No se pudo crear la sesión de pago. Inténtelo de nuevo.",
      connection: "Error de conexión. Inténtelo de nuevo.",
    },
  },
  id: {
    nav: {
      products: "Produk",
      performance: "Kinerja",
      tools: "Perkakas",
      pricing: "Harga",
      blog: "Blog",
      affiliate: "Affiliate",
      tigold: "TiGold",
    },
    actions: {
      freeTrial: "Mulai gratis",
      signUp: "Daftar",
      signIn: "Masuk",
      redirecting: "Mengalihkan...",
    },
    installApp: {
      button: "Instal aplikasi",
      iosTitle: "Instal Dralvo ke layar utama",
      iosStep1: "Ketuk tombol Share di Safari",
      iosStep2: 'Pilih "Tambahkan ke Layar Utama"',
      iosStep3: "Ketuk Tambah — selesai!",
    },
    footer: {
      productTitle: "Produk",
      companyTitle: "Perusahaan",
      legalTitle: "Legal",
      tagline:
        "Intelijen keputusan emas yang dibangun dari bukti pasar yang dapat ditelusuri. Hanya bersifat informatif, bukan nasihat keuangan.",
      rights: "© 2026 Dralvo. Seluruh hak cipta dilindungi.",
      notAdvice: "© 2026 Dralvo. Bukan nasihat keuangan.",
      pastPerformance: "Kinerja masa lalu ≠ hasil di masa depan.",
      links: {
        blog: "Blog",
        methodology: "Metodologi",
        tigold: "TiGold",
        affiliate: "Affiliate",
        pricing: "Harga",
        trackRecord: "Rekam jejak",
        signIn: "Masuk",
        createAccount: "Buat akun",
        privacy: "Privasi",
        terms: "Ketentuan",
        disclaimer: "Penafian",
      },
    },
    errors: {
      checkoutFailed: "Tidak dapat membuat sesi pembayaran. Silakan coba lagi.",
      connection: "Kesalahan koneksi. Silakan coba lagi.",
    },
  },
  ar: {
    nav: {
      products: "المنتجات",
      performance: "الأداء",
      tools: "الأدوات",
      pricing: "الأسعار",
      blog: "Blog",
      affiliate: "Affiliate",
      tigold: "TiGold",
    },
    actions: {
      freeTrial: "ابدأ مجانًا",
      signUp: "إنشاء حساب",
      signIn: "تسجيل الدخول",
      redirecting: "جارٍ التحويل...",
    },
    installApp: {
      button: "تثبيت التطبيق",
      iosTitle: "تثبيت Dralvo على الشاشة الرئيسية",
      iosStep1: "اضغط على زر المشاركة في Safari",
      iosStep2: "اختر \"إضافة إلى الشاشة الرئيسية\"",
      iosStep3: "اضغط إضافة — تم!",
    },
    footer: {
      productTitle: "المنتج",
      companyTitle: "الشركة",
      legalTitle: "الشؤون القانونية",
      tagline:
        "ذكاء قرارات الذهب المبني على أدلة سوقية قابلة للتتبع. لأغراض إعلامية فقط، وليس مشورة مالية بأي حال.",
      rights: "© 2026 Dralvo. جميع الحقوق محفوظة.",
      notAdvice: "© 2026 Dralvo. ليست مشورة مالية.",
      pastPerformance: "الأداء السابق ≠ النتائج المستقبلية.",
      links: {
        blog: "Blog",
        methodology: "المنهجية",
        tigold: "TiGold",
        affiliate: "Affiliate",
        pricing: "الأسعار",
        trackRecord: "سجل الأداء",
        signIn: "تسجيل الدخول",
        createAccount: "إنشاء حساب",
        privacy: "الخصوصية",
        terms: "الشروط",
        disclaimer: "إخلاء المسؤولية",
      },
    },
    errors: {
      checkoutFailed: "تعذّر إنشاء جلسة الدفع. يُرجى المحاولة مرة أخرى.",
      connection: "خطأ في الاتصال. يُرجى المحاولة مرة أخرى.",
    },
  },
  vi: {
    nav: {
      products: "Sản phẩm",
      performance: "Hiệu suất",
      tools: "Công cụ",
      pricing: "Bảng giá",
      blog: "Blog",
      affiliate: "Affiliate",
      tigold: "TiGold",
    },
    actions: {
      freeTrial: "Dùng thử miễn phí",
      signUp: "Đăng ký",
      signIn: "Đăng nhập",
      redirecting: "Đang chuyển...",
    },
    installApp: {
      button: "Tải ứng dụng",
      iosTitle: "Cài Dralvo lên màn hình chính",
      iosStep1: "Bấm nút Share ở thanh dưới Safari",
      iosStep2: 'Chọn "Thêm vào MH chính"',
      iosStep3: "Bấm Thêm — xong!",
    },
    footer: {
      productTitle: "Sản phẩm",
      companyTitle: "Công ty",
      legalTitle: "Pháp lý",
      tagline:
        "Trí tuệ quyết định vàng, dựng từ bằng chứng thị trường truy xuất được. Chỉ mang tính thông tin, không phải lời khuyên đầu tư.",
      rights: "© 2026 Dralvo. Bảo lưu mọi quyền.",
      notAdvice: "© 2026 Dralvo. Không phải lời khuyên đầu tư.",
      pastPerformance: "Hiệu suất quá khứ ≠ kết quả tương lai.",
      links: {
        blog: "Blog",
        methodology: "Phương pháp",
        tigold: "TiGold",
        affiliate: "Affiliate",
        pricing: "Bảng giá",
        trackRecord: "Hiệu suất",
        signIn: "Đăng nhập",
        createAccount: "Tạo tài khoản",
        privacy: "Bảo mật",
        terms: "Điều khoản",
        disclaimer: "Miễn trừ trách nhiệm",
      },
    },
    errors: {
      checkoutFailed: "Không thể tạo phiên thanh toán. Vui lòng thử lại.",
      connection: "Lỗi kết nối. Vui lòng thử lại.",
    },
  },
  en: {
    nav: {
      products: "Products",
      performance: "Performance",
      tools: "Tools",
      pricing: "Pricing",
      blog: "Blog",
      affiliate: "Affiliate",
      tigold: "TiGold",
    },
    actions: {
      freeTrial: "Start free",
      signUp: "Sign up",
      signIn: "Sign in",
      redirecting: "Redirecting...",
    },
    installApp: {
      button: "Install app",
      iosTitle: "Install Dralvo to your Home Screen",
      iosStep1: "Tap the Share button in Safari",
      iosStep2: 'Choose "Add to Home Screen"',
      iosStep3: "Tap Add — done!",
    },
    footer: {
      productTitle: "Product",
      companyTitle: "Company",
      legalTitle: "Legal",
      tagline:
        "Gold decision intelligence built from traceable market evidence. Informational only, never financial advice.",
      rights: "© 2026 Dralvo. All rights reserved.",
      notAdvice: "© 2026 Dralvo. Not financial advice.",
      pastPerformance: "Past performance ≠ future results.",
      links: {
        blog: "Blog",
        methodology: "Methodology",
        tigold: "TiGold",
        affiliate: "Affiliate",
        pricing: "Pricing",
        trackRecord: "Track record",
        signIn: "Sign in",
        createAccount: "Create account",
        privacy: "Privacy",
        terms: "Terms",
        disclaimer: "Disclaimer",
      },
    },
    errors: {
      checkoutFailed: "Could not create a checkout session. Please try again.",
      connection: "Connection error. Please try again.",
    },
  },
});
