import { withLocaleFallback } from "@/lib/i18n";

/** Copy for the /compare ("Dralvo vs grid/martingale") page, in 8 locales.
 *  Product names (Dralvo, GoldMaster, GoldScalp, TiGold, MetaTrader, MT5,
 *  XAUUSD, IB) are kept untranslated as brand/technical terms. */
export const COMPARE_COPY = withLocaleFallback({
  ar: {
    back: "العودة إلى Dralvo",
    badge: "مقارنة",
    h1: "Dralvo مقابل روبوتات EA للذهب القائمة على grid و martingale",
    intro:
      "تعتمد غالبية روبوتات EA للذهب المعروضة عبر الإنترنت على استراتيجية grid أو martingale أو تخفيض متوسط السعر عند الخسارة. تبدو منحنيات رأس المال لديها مثالية لأن الصفقات الخاسرة لا تُغلق أبداً — إلى أن يمحو اتجاه قوي واحد الحساب بالكامل دفعة واحدة. يتبع Dralvo النهج المعاكس: وقف خسارة صارم في كل صفقة، ونسبة مخاطرة ثابتة، وسجل أداء منشور بالكامل. هذا هو الفارق الصادق، جنباً إلى جنب.",
    th: { dim: "المعيار", grid: "روبوت EA ذهب grid / martingale نموذجي", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "منهجية المخاطرة الأساسية", grid: "Grid أو martingale أو تخفيض المتوسط — يضيف إلى المراكز الخاسرة", dralvo: "نسبة مخاطرة % ثابتة لكل صفقة — لا يخفّض المتوسط أبداً" },
      { dim: "وقف الخسارة", grid: "غالباً غير موجود، أو مستوى \"استرداد\" بعيد نادراً ما يُفعّل", dralvo: "وقف خسارة صارم في كل صفقة، إضافة إلى وقف زمني (GoldScalp)" },
      { dim: "حجم اللوت بعد الخسارة", grid: "يزيد (يضاعف/يضرب) بهدف \"الاسترداد\"", dralvo: "دون تغيير — تبقى المخاطرة ثابتة" },
      { dim: "منحنى رأس المال النموذجي", grid: "سلس وجميل… إلى أن يحدث انفجار مفاجئ واحد", dralvo: "مستقر مع انخفاضات رأس مال واضحة ومحدودة" },
      { dim: "أسوأ سيناريو محتمل", grid: "محو كامل للحساب في اتجاه معاكس واحد", dralvo: "انخفاض رأس مال مُقيّد — منشور وغير مخفي" },
      { dim: "السلوك في اتجاه معاكس قوي", grid: "يستمر في تكديس المراكز الخاسرة", dralvo: "يتوقف أو يخرج — الحفاظ على رأس المال بحكم التصميم" },
      { dim: "نسبة الربح المُسوّقة", grid: "\"90%+ صفقات رابحة\" (أرباح صغيرة، خسارة كارثية نادرة)", dralvo: "صادقة (~40%) — الأفضلية في نسبة العائد إلى المخاطرة" },
      { dim: "الشفافية", grid: "منطق مخفي ولقطات شاشة منتقاة", dralvo: "اختبار تاريخي كامل + توقعات صادقة، منشورة علناً" },
      { dim: "التحقق من البيانات", grid: "ادعاءات غامضة ولقطات شاشة تجريبية فقط", dralvo: "بيانات تاريخية حقيقية / بجودة 100%-real-tick" },
      { dim: "المنصة", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "التسعير", grid: "غالباً دفعة واحدة مكلفة — ثم تلتهم الاستراتيجية الحساب", dralvo: "مجاني (TiGold عبر Dralvo IB) أو Dralvo VIP بدءاً من $59/شهرياً" },
    ],
    whyTitle: "لماذا ينفجر grid و martingale في نهاية المطاف",
    whyParas: [
      "يبقى نظام martingale أو grid على قيد الحياة برفضه تسجيل أي خسارة. عندما تتحرك الصفقة عكسه، فبدلاً من إغلاقها يفتح مزيداً من المراكز عند أسعار \"أفضل\" ويزيد الحجم، مراهناً على عودة السعر إلى نقطة التعادل. وفي معظم الأحيان يعود بالفعل — وهذا بالضبط ما يجعل منحنى رأس المال يبدو سلساً ويسمح للتسويق بادعاء نسبة ربح تتجاوز 90%.",
      "تكمن المشكلة في الطرف الأقصى للتوزيع. فالذهب (XAUUSD) يتّجه بقوة خلال الصدمات الاقتصادية الكلية. وحين يندفع السعر في اتجاه واحد ولا يعود، تنمو المراكز الخاسرة المتراكمة أسرع مما يستطيع الحساب استيعابه، فتمحو حركة واحدة أشهراً من \"المكاسب\". ولا يوجد وقف خسارة صارم يحدّ من الضرر.",
      "بُني Dralvo على النهج المعاكس. فـ GoldMaster نظام swing صبور على إطار D1 يتداول مع الاتجاه ويبقى خارج السوق حين يكون الذهب هابطاً. وأما GoldScalp فهو مضارب زخم على إطار M15 تمتلك فيه كل صفقة وقف خسارة صارماً ووقفاً زمنياً. و TiGold محرك تكيّفي مجاني بالانضباط نفسه. ولا يعتمد أي منها على تخفيض المتوسط — نسبة ربح مُسوّقة أدنى، لكن ملف مخاطرة قابل للبقاء ويمكن التحقق منه علناً.",
    ],
    faqTitle: "الأسئلة الشائعة",
    faq: [
      ["هل Dralvo روبوت EA يعتمد على martingale أو grid؟", "لا. كل روبوت من Dralvo — GoldMaster و GoldScalp و TiGold — يستخدم وقف خسارة صارماً ونسبة مخاطرة ثابتة لكل صفقة. ولا يعتمد أي منها على تخفيض المتوسط، أو تشغيل grid، أو زيادة حجم اللوت بعد الخسارة."],
      ["لماذا تُظهر روبوتات martingale منحنيات رأس مال بهذا القدر من السلاسة والمثالية؟", "لأن الصفقات الخاسرة لا تُغلق أبداً على خسارة — يستمر الروبوت في الإضافة إليها حتى يرتد السعر، مما يخفي كل خسارة على هيئة مركز \"مفتوح\". يبدو المنحنى خالياً من العيوب إلى أن يعجز اتجاه واحد عن الارتداد، فيُمحى الحساب بأكمله دفعة واحدة."],
      ["هل يضمن Dralvo الربح أو نسبة ربح مرتفعة؟", "لا. ينشر Dralvo توقعات صادقة، تشمل نسبة الربح، وأطول سلسلة خسائر، والحد الأقصى لانخفاض رأس المال. والهدف التصميمي هو نسبة ربح واقعية تبلغ ~40% مع نسبة عائد إلى مخاطرة قوية — وليس رقماً تسويقياً يتجاوز 90%."],
      ["ما الخدعة الكامنة وراء روبوت EA للذهب بنسبة ربح \"90%\"؟", "عادة ما تعني نسبة الربح المرتفعة جداً كثيراً من الأرباح الصغيرة وقليلاً من الخسائر الضخمة — أي قيمة متوقعة سالبة. يعمل Dralvo على تحسين القيمة المتوقعة (العائد إلى المخاطرة)، فيربح على نحو أقل تكراراً لكنه يُبقي الخسائر صغيرة ومنضبطة."],
    ] as [string, string][],
    ctaBacktest: "شاهد الاختبار التاريخي الحقيقي",
    ctaTigold: "احصل على TiGold مجاناً",
    disclaimer: "مقارنة تعليمية فقط — وليست نصيحة مالية. ينطوي تداول XAUUSD وغيره من الأدوات ذات الرافعة المالية على مخاطر خسارة كبيرة. والأداء السابق لا يضمن النتائج المستقبلية.",
  },
  en: {
    back: "Back to Dralvo",
    badge: "Comparison",
    h1: "Dralvo vs grid & martingale gold EAs",
    intro:
      "Most gold EAs sold online run a grid, martingale or averaging-down strategy. Their equity curves look perfect because losing trades are never closed — until one strong trend wipes the account out at once. Dralvo takes the opposite approach: a hard stop-loss on every trade, a fixed percentage of risk, and a fully published track record. Here is the honest, side-by-side difference.",
    th: { dim: "Dimension", grid: "Typical grid / martingale gold EA", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Core risk method", grid: "Grid, martingale or averaging-down — adds to losing positions", dralvo: "Fixed % risk per trade — never averages down" },
      { dim: "Stop-loss", grid: "Often none, or a far “recovery” level that rarely triggers", dralvo: "Hard stop-loss on every trade, plus a time-stop (GoldScalp)" },
      { dim: "Lot size after a loss", grid: "Increases (doubles/multiplies) to “recover”", dralvo: "Unchanged — risk stays constant" },
      { dim: "Typical equity curve", grid: "Smooth and beautiful… until one sudden blow-up", dralvo: "Steady with visible, bounded drawdowns" },
      { dim: "Worst-case outcome", grid: "Full account wipeout in a single adverse trend", dralvo: "Capped drawdown — published, not hidden" },
      { dim: "Behaviour in a strong adverse trend", grid: "Keeps stacking losing positions", dralvo: "Sits idle or exits — capital preservation by design" },
      { dim: "Marketed win rate", grid: "“90%+ wins” (tiny wins, rare catastrophic loss)", dralvo: "Honest (~40%) — the edge is reward-to-risk" },
      { dim: "Transparency", grid: "Hidden logic, cherry-picked screenshots", dralvo: "Full backtest + honest expectations, published openly" },
      { dim: "Data verification", grid: "Vague claims, demo-only screenshots", dralvo: "Real / 100%-real-tick historical data" },
      { dim: "Platform", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Pricing", grid: "Often a costly one-off — then the strategy eats the account", dralvo: "Free (TiGold via Dralvo IB) or Dralvo VIP from $59/month" },
    ],
    whyTitle: "Why grid & martingale eventually blow up",
    whyParas: [
      "A martingale or grid system survives by refusing to take a loss. When a trade moves against it, instead of closing it opens more positions at “better” prices and increases size, betting that price will return to break-even. Most of the time it does — which is exactly why the equity curve looks smooth and the marketing can claim a 90%+ win rate.",
      "The problem is the tail. Gold (XAUUSD) trends hard during macro shocks. When price runs in one direction and does not come back, the stacked losing positions grow faster than the account can absorb, and a single move erases months of “wins.” There is no hard stop-loss to cap the damage.",
      "Dralvo is built the other way around. GoldMaster is a patient D1 swing system that trades with the trend and stays out when gold is bearish. GoldScalp is an M15 momentum scalper where every trade has a hard stop-loss and a time-stop. TiGold is a free adaptive engine with the same discipline. None of them average down — a lower marketed win rate, but a survivable, publicly verifiable risk profile.",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      ["Is Dralvo a martingale or grid EA?", "No. Every Dralvo robot — GoldMaster, GoldScalp and TiGold — uses a hard stop-loss and a fixed percentage of risk per trade. None of them average down, run a grid, or increase lot size after a loss."],
      ["Why do martingale EAs show such smooth, perfect equity curves?", "Because losing trades are never closed at a loss — the EA keeps adding to them until price reverts, which hides every loss as an “open” position. The curve looks flawless until one trend does not revert, and the whole account is wiped out at once."],
      ["Does Dralvo guarantee profit or a high win rate?", "No. Dralvo publishes honest expectations, including win rate, the longest losing streak and the maximum drawdown. A realistic ~40% win rate with a strong reward-to-risk ratio is the design goal — not a marketed 90%+ figure."],
      ["What is the catch with a “90% win rate” gold EA?", "A very high win rate usually means many tiny wins and a few enormous losses — negative expectancy. Dralvo optimises expectancy (reward-to-risk), so it wins less often but keeps losses small and controlled."],
    ] as [string, string][],
    ctaBacktest: "See the real backtest",
    ctaTigold: "Get TiGold free",
    disclaimer: "Educational comparison only — not financial advice. Trading XAUUSD and other leveraged instruments involves substantial risk of loss. Past performance does not guarantee future results.",
  },

  vi: {
    back: "Quay lại Dralvo",
    badge: "So sánh",
    h1: "Dralvo vs EA grid & martingale",
    intro:
      "Phần lớn “EA vàng” bán trên mạng chạy chiến lược grid, martingale hoặc nhồi lệnh. Đường vốn trông hoàn hảo vì lệnh thua không bao giờ bị đóng — cho đến khi một con sóng mạnh quét sạch tài khoản trong một lần. Dralvo đi ngược lại: hard stop-loss cho mọi lệnh, rủi ro % cố định, và track record công khai đầy đủ. Đây là khác biệt thẳng thắn, đặt cạnh nhau.",
    th: { dim: "Tiêu chí", grid: "EA grid / martingale điển hình", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Phương pháp rủi ro cốt lõi", grid: "Grid, martingale hoặc nhồi lệnh — cộng thêm vào lệnh đang thua", dralvo: "Rủi ro % cố định mỗi lệnh — không bao giờ nhồi lệnh" },
      { dim: "Stop-loss", grid: "Thường không có, hoặc mức “gỡ” quá xa hiếm khi chạm", dralvo: "Hard stop-loss mỗi lệnh, cộng time-stop (GoldScalp)" },
      { dim: "Khối lượng sau lệnh thua", grid: "Tăng (gấp đôi/nhân lên) để “gỡ”", dralvo: "Không đổi — rủi ro giữ nguyên" },
      { dim: "Đường vốn điển hình", grid: "Mượt và đẹp… đến lúc nổ một phát", dralvo: "Ổn định, drawdown thấy được và có giới hạn" },
      { dim: "Kịch bản xấu nhất", grid: "Cháy sạch tài khoản trong một con sóng ngược", dralvo: "Drawdown bị chặn — công khai, không giấu" },
      { dim: "Khi gặp trend ngược mạnh", grid: "Cứ chồng thêm lệnh thua", dralvo: "Đứng yên hoặc thoát — bảo toàn vốn theo thiết kế" },
      { dim: "Win rate quảng cáo", grid: "“Thắng 90%+” (thắng nhỏ, thua thảm họa hiếm khi)", dralvo: "Trung thực (~40%) — lợi thế nằm ở reward-to-risk" },
      { dim: "Minh bạch", grid: "Giấu logic, ảnh chụp chọn lọc", dralvo: "Backtest đầy đủ + kỳ vọng thật, công khai" },
      { dim: "Kiểm chứng dữ liệu", grid: "Tuyên bố mơ hồ, chỉ ảnh demo", dralvo: "Dữ liệu thật / 100% real-tick" },
      { dim: "Nền tảng", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Giá", grid: "Thường mua đứt đắt — rồi chiến lược ăn sạch tài khoản", dralvo: "Miễn phí (TiGold qua Dralvo IB) hoặc Dralvo VIP từ $59/tháng" },
    ],
    whyTitle: "Vì sao grid & martingale rồi cũng cháy",
    whyParas: [
      "Một hệ martingale hay grid tồn tại được nhờ từ chối nhận lỗ. Khi lệnh đi ngược, thay vì đóng, nó mở thêm lệnh ở giá “tốt hơn” và tăng khối lượng, đặt cược rằng giá sẽ quay về hòa vốn. Phần lớn thời gian điều đó xảy ra — đó chính là lý do đường vốn trông mượt và marketing có thể khoe win rate 90%+.",
      "Vấn đề nằm ở phần đuôi. Vàng (XAUUSD) trend rất mạnh trong các cú sốc vĩ mô. Khi giá chạy một chiều và không quay lại, chuỗi lệnh thua phình to nhanh hơn sức chịu của tài khoản, và chỉ một cú chạy xóa sạch nhiều tháng “thắng”. Không có hard stop-loss nào để chặn thiệt hại.",
      "Dralvo được xây theo hướng ngược lại. GoldMaster là hệ swing D1 kiên nhẫn, giao dịch thuận xu hướng và đứng ngoài khi vàng giảm. GoldScalp là scalper momentum M15, mỗi lệnh đều có hard stop-loss và time-stop. TiGold là engine thích ứng miễn phí với cùng kỷ luật. Không cái nào nhồi lệnh — win rate quảng cáo thấp hơn, nhưng hồ sơ rủi ro sống sót được và kiểm chứng công khai.",
    ],
    faqTitle: "Câu hỏi thường gặp",
    faq: [
      ["Dralvo có phải EA martingale/grid không?", "Không. Mọi robot Dralvo — GoldMaster, GoldScalp và TiGold — đều dùng hard stop-loss và rủi ro % cố định mỗi lệnh. Không cái nào nhồi lệnh, chạy grid hay tăng khối lượng sau khi thua."],
      ["Vì sao EA martingale có đường vốn mượt và hoàn hảo đến vậy?", "Vì lệnh thua không bao giờ bị đóng ở mức lỗ — EA cứ cộng thêm cho tới khi giá hồi, che mọi khoản lỗ thành lệnh “đang mở”. Đường vốn trông không tì vết cho đến khi một con sóng không hồi, và cả tài khoản bị quét sạch một lần."],
      ["Dralvo có đảm bảo lợi nhuận hay win rate cao không?", "Không. Dralvo công khai kỳ vọng thật, gồm win rate, chuỗi thua dài nhất và drawdown tối đa. Mục tiêu thiết kế là win rate thực tế ~40% với tỉ lệ reward-to-risk tốt — không phải con số 90%+ kiểu quảng cáo."],
      ["“EA win rate 90%” thì bẫy nằm ở đâu?", "Win rate rất cao thường nghĩa là nhiều lệnh thắng nhỏ và vài lệnh thua khổng lồ — kỳ vọng âm. Dralvo tối ưu kỳ vọng (reward-to-risk), nên thắng ít lần hơn nhưng giữ khoản lỗ nhỏ và kiểm soát được."],
    ] as [string, string][],
    ctaBacktest: "Xem backtest thật",
    ctaTigold: "Nhận TiGold miễn phí",
    disclaimer: "Chỉ là so sánh mang tính giáo dục — không phải lời khuyên đầu tư. Giao dịch XAUUSD và các công cụ đòn bẩy có rủi ro thua lỗ đáng kể. Hiệu suất quá khứ không đảm bảo kết quả tương lai.",
  },

  "pt-BR": {
    back: "Voltar para a Dralvo",
    badge: "Comparação",
    h1: "Dralvo vs EAs de ouro grid & martingale",
    intro:
      "A maioria dos “EAs de ouro” vendidos online roda uma estratégia de grid, martingale ou preço médio. As curvas de capital parecem perfeitas porque as operações perdedoras nunca são fechadas — até que uma tendência forte zere a conta de uma só vez. A Dralvo faz o oposto: um stop-loss fixo em cada operação, um percentual de risco fixo e um histórico totalmente público. Aqui está a diferença honesta, lado a lado.",
    th: { dim: "Dimensão", grid: "EA de ouro grid / martingale típico", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Método de risco central", grid: "Grid, martingale ou preço médio — adiciona a posições perdedoras", dralvo: "Risco % fixo por operação — nunca faz preço médio" },
      { dim: "Stop-loss", grid: "Geralmente nenhum, ou um nível de “recuperação” distante que quase nunca dispara", dralvo: "Stop-loss fixo em cada operação, além de time-stop (GoldScalp)" },
      { dim: "Tamanho do lote após uma perda", grid: "Aumenta (dobra/multiplica) para “recuperar”", dralvo: "Inalterado — o risco permanece constante" },
      { dim: "Curva de capital típica", grid: "Suave e linda… até um estouro repentino", dralvo: "Estável, com drawdowns visíveis e limitados" },
      { dim: "Pior caso", grid: "Conta zerada por completo em uma única tendência adversa", dralvo: "Drawdown limitado — publicado, não escondido" },
      { dim: "Comportamento em tendência adversa forte", grid: "Continua empilhando posições perdedoras", dralvo: "Fica de fora ou sai — preservação de capital por design" },
      { dim: "Taxa de acerto divulgada", grid: "“90%+ de acertos” (ganhos minúsculos, perda catastrófica rara)", dralvo: "Honesta (~40%) — a vantagem é o risco-retorno" },
      { dim: "Transparência", grid: "Lógica oculta, capturas selecionadas", dralvo: "Backtest completo + expectativas honestas, públicas" },
      { dim: "Verificação de dados", grid: "Alegações vagas, capturas só de demo", dralvo: "Dados reais / ticks 100% reais" },
      { dim: "Plataforma", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Preço", grid: "Muitas vezes um pagamento único caro — e então a estratégia devora a conta", dralvo: "Grátis (TiGold via Dralvo IB) ou Dralvo VIP a partir de $59/mês" },
    ],
    whyTitle: "Por que grid & martingale acabam estourando",
    whyParas: [
      "Um sistema de martingale ou grid sobrevive recusando-se a assumir uma perda. Quando uma operação vai contra, em vez de fechar abre mais posições a preços “melhores” e aumenta o tamanho, apostando que o preço voltará ao ponto de equilíbrio. Na maioria das vezes volta — é exatamente por isso que a curva de capital parece suave e o marketing pode alegar 90%+ de acertos.",
      "O problema é a cauda. O ouro (XAUUSD) tem tendências fortes durante choques macro. Quando o preço corre numa direção e não volta, as posições perdedoras acumuladas crescem mais rápido do que a conta consegue absorver, e um único movimento apaga meses de “ganhos”. Não há stop-loss fixo para limitar o dano.",
      "A Dralvo é construída ao contrário. O GoldMaster é um sistema swing D1 paciente que opera a favor da tendência e fica de fora quando o ouro está em baixa. O GoldScalp é um scalper de momentum M15 onde cada operação tem stop-loss fixo e time-stop. O TiGold é um motor adaptativo gratuito com a mesma disciplina. Nenhum faz preço médio — uma taxa de acerto divulgada menor, mas um perfil de risco que sobrevive e é verificável publicamente.",
    ],
    faqTitle: "Perguntas frequentes",
    faq: [
      ["A Dralvo é um EA de martingale ou grid?", "Não. Cada robô Dralvo — GoldMaster, GoldScalp e TiGold — usa um stop-loss fixo e um percentual de risco fixo por operação. Nenhum faz preço médio, roda um grid ou aumenta o lote após uma perda."],
      ["Por que EAs de martingale mostram curvas de capital tão suaves e perfeitas?", "Porque as operações perdedoras nunca são fechadas no prejuízo — o EA continua adicionando até o preço reverter, escondendo cada perda como uma posição “aberta”. A curva parece impecável até uma tendência não reverter, e a conta inteira é zerada de uma vez."],
      ["A Dralvo garante lucro ou alta taxa de acerto?", "Não. A Dralvo publica expectativas honestas, incluindo taxa de acerto, a maior sequência de perdas e o drawdown máximo. O objetivo de projeto é uma taxa realista de ~40% com bom risco-retorno — não um 90%+ de marketing."],
      ["Qual é a pegadinha de um EA de ouro com “90% de acerto”?", "Uma taxa de acerto muito alta geralmente significa muitos ganhos minúsculos e algumas perdas enormes — expectativa negativa. A Dralvo otimiza a expectativa (risco-retorno), então ganha menos vezes, mas mantém as perdas pequenas e controladas."],
    ] as [string, string][],
    ctaBacktest: "Ver o backtest real",
    ctaTigold: "Obter o TiGold grátis",
    disclaimer: "Comparação educativa apenas — não é aconselhamento financeiro. Operar XAUUSD e outros instrumentos alavancados envolve risco substancial de perda. Desempenho passado não garante resultados futuros.",
  },

  es: {
    back: "Volver a Dralvo",
    badge: "Comparación",
    h1: "Dralvo vs EAs de oro grid y martingala",
    intro:
      "La mayoría de los “EAs de oro” que se venden online usan una estrategia de grid, martingala o promediado a la baja. Sus curvas de capital se ven perfectas porque las operaciones perdedoras nunca se cierran… hasta que una tendencia fuerte vacía la cuenta de golpe. Dralvo hace lo contrario: un stop-loss fijo en cada operación, un porcentaje de riesgo fijo y un historial totalmente público. Esta es la diferencia honesta, lado a lado.",
    th: { dim: "Dimensión", grid: "EA de oro grid / martingala típico", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Método de riesgo central", grid: "Grid, martingala o promediado — añade a posiciones perdedoras", dralvo: "Riesgo % fijo por operación — nunca promedia a la baja" },
      { dim: "Stop-loss", grid: "A menudo ninguno, o un nivel de “recuperación” lejano que casi nunca salta", dralvo: "Stop-loss fijo en cada operación, más un time-stop (GoldScalp)" },
      { dim: "Tamaño del lote tras una pérdida", grid: "Aumenta (duplica/multiplica) para “recuperar”", dralvo: "Sin cambios — el riesgo se mantiene constante" },
      { dim: "Curva de capital típica", grid: "Suave y bonita… hasta una explosión repentina", dralvo: "Estable, con drawdowns visibles y acotados" },
      { dim: "Peor caso", grid: "Cuenta vaciada por completo en una sola tendencia adversa", dralvo: "Drawdown limitado — publicado, no oculto" },
      { dim: "Comportamiento en una tendencia adversa fuerte", grid: "Sigue apilando posiciones perdedoras", dralvo: "Se queda fuera o sale — preservación del capital por diseño" },
      { dim: "Tasa de acierto publicitada", grid: "“90%+ de aciertos” (ganancias pequeñas, pérdida catastrófica rara)", dralvo: "Honesta (~40%) — la ventaja es el ratio riesgo-beneficio" },
      { dim: "Transparencia", grid: "Lógica oculta, capturas seleccionadas", dralvo: "Backtest completo + expectativas honestas, públicas" },
      { dim: "Verificación de datos", grid: "Afirmaciones vagas, capturas solo de demo", dralvo: "Datos reales / ticks 100% reales" },
      { dim: "Plataforma", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Precio", grid: "A menudo un pago único caro — y luego la estrategia se come la cuenta", dralvo: "Gratis (TiGold vía Dralvo IB) o Dralvo VIP desde $59/mes" },
    ],
    whyTitle: "Por qué grid y martingala acaban explotando",
    whyParas: [
      "Un sistema de martingala o grid sobrevive negándose a asumir una pérdida. Cuando una operación va en contra, en vez de cerrarla abre más posiciones a “mejores” precios y aumenta el tamaño, apostando a que el precio volverá al punto de equilibrio. La mayoría de las veces lo hace — por eso la curva de capital se ve suave y el marketing puede presumir de un 90%+ de aciertos.",
      "El problema es la cola. El oro (XAUUSD) tiene tendencias fuertes durante shocks macro. Cuando el precio corre en una dirección y no vuelve, las posiciones perdedoras acumuladas crecen más rápido de lo que la cuenta puede absorber, y un solo movimiento borra meses de “ganancias”. No hay stop-loss fijo que limite el daño.",
      "Dralvo está construido al revés. GoldMaster es un sistema swing D1 paciente que opera a favor de la tendencia y se mantiene fuera cuando el oro es bajista. GoldScalp es un scalper de momentum M15 donde cada operación tiene stop-loss fijo y time-stop. TiGold es un motor adaptativo gratuito con la misma disciplina. Ninguno promedia a la baja — una tasa de acierto publicitada menor, pero un perfil de riesgo que sobrevive y es verificable públicamente.",
    ],
    faqTitle: "Preguntas frecuentes",
    faq: [
      ["¿Es Dralvo un EA de martingala o grid?", "No. Cada robot Dralvo — GoldMaster, GoldScalp y TiGold — usa un stop-loss fijo y un porcentaje de riesgo fijo por operación. Ninguno promedia a la baja, corre un grid ni aumenta el lote tras una pérdida."],
      ["¿Por qué los EAs de martingala muestran curvas tan suaves y perfectas?", "Porque las operaciones perdedoras nunca se cierran con pérdida — el EA sigue añadiendo hasta que el precio revierte, ocultando cada pérdida como una posición “abierta”. La curva parece impecable hasta que una tendencia no revierte y toda la cuenta se vacía de golpe."],
      ["¿Dralvo garantiza beneficios o una tasa de acierto alta?", "No. Dralvo publica expectativas honestas, incluida la tasa de acierto, la racha perdedora más larga y el drawdown máximo. El objetivo de diseño es una tasa realista de ~40% con un buen ratio riesgo-beneficio — no un 90%+ publicitario."],
      ["¿Cuál es la trampa de un EA de oro con “90% de aciertos”?", "Una tasa de acierto muy alta suele significar muchas ganancias diminutas y unas pocas pérdidas enormes — expectativa negativa. Dralvo optimiza la expectativa (riesgo-beneficio), así que gana menos a menudo pero mantiene las pérdidas pequeñas y controladas."],
    ] as [string, string][],
    ctaBacktest: "Ver el backtest real",
    ctaTigold: "Obtener TiGold gratis",
    disclaimer: "Comparación educativa únicamente — no es asesoramiento financiero. Operar XAUUSD y otros instrumentos apalancados implica un riesgo sustancial de pérdida. El rendimiento pasado no garantiza resultados futuros.",
  },

  id: {
    back: "Kembali ke Dralvo",
    badge: "Perbandingan",
    h1: "Dralvo vs EA emas grid & martingale",
    intro:
      "Sebagian besar “EA emas” yang dijual online menjalankan strategi grid, martingale, atau averaging-down. Kurva ekuitasnya terlihat sempurna karena transaksi rugi tidak pernah ditutup — sampai satu tren kuat menghabiskan akun sekaligus. Dralvo mengambil pendekatan sebaliknya: hard stop-loss di setiap transaksi, persentase risiko tetap, dan rekam jejak yang dipublikasikan penuh. Inilah perbedaan jujurnya, berdampingan.",
    th: { dim: "Dimensi", grid: "EA emas grid / martingale pada umumnya", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Metode risiko inti", grid: "Grid, martingale atau averaging — menambah posisi rugi", dralvo: "Risiko % tetap per transaksi — tidak pernah averaging" },
      { dim: "Stop-loss", grid: "Sering tidak ada, atau level “recovery” jauh yang jarang kena", dralvo: "Hard stop-loss tiap transaksi, plus time-stop (GoldScalp)" },
      { dim: "Ukuran lot setelah rugi", grid: "Bertambah (gandakan/perbesar) untuk “recovery”", dralvo: "Tetap — risiko konstan" },
      { dim: "Kurva ekuitas khas", grid: "Mulus dan indah… sampai satu blow-up mendadak", dralvo: "Stabil, drawdown terlihat dan terbatas" },
      { dim: "Skenario terburuk", grid: "Akun ludes total dalam satu tren berlawanan", dralvo: "Drawdown dibatasi — dipublikasikan, tidak disembunyikan" },
      { dim: "Perilaku saat tren berlawanan kuat", grid: "Terus menumpuk posisi rugi", dralvo: "Diam atau keluar — menjaga modal sesuai desain" },
      { dim: "Win rate yang dipasarkan", grid: "“Menang 90%+” (untung kecil, rugi katastrofik jarang)", dralvo: "Jujur (~40%) — keunggulan ada pada risk-reward" },
      { dim: "Transparansi", grid: "Logika disembunyikan, screenshot pilihan", dralvo: "Backtest penuh + ekspektasi jujur, dipublikasikan" },
      { dim: "Verifikasi data", grid: "Klaim kabur, screenshot demo saja", dralvo: "Data nyata / 100% real-tick historis" },
      { dim: "Platform", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Harga", grid: "Sering sekali bayar mahal — lalu strateginya memakan akun", dralvo: "Gratis (TiGold via Dralvo IB) atau Dralvo VIP mulai $59/bulan" },
    ],
    whyTitle: "Mengapa grid & martingale akhirnya meledak",
    whyParas: [
      "Sistem martingale atau grid bertahan dengan menolak menerima kerugian. Saat transaksi berlawanan, alih-alih ditutup, ia membuka lebih banyak posisi di harga “lebih baik” dan memperbesar ukuran, bertaruh harga akan kembali ke titik impas. Sering kali memang begitu — itulah mengapa kurva ekuitas terlihat mulus dan pemasaran bisa mengklaim win rate 90%+.",
      "Masalahnya ada di ekor. Emas (XAUUSD) tren kuat saat guncangan makro. Ketika harga lari satu arah dan tak kembali, posisi rugi yang menumpuk membesar lebih cepat dari kemampuan akun menyerapnya, dan satu pergerakan menghapus “kemenangan” berbulan-bulan. Tidak ada hard stop-loss untuk membatasi kerusakan.",
      "Dralvo dibangun sebaliknya. GoldMaster adalah sistem swing D1 yang sabar, trading searah tren dan diam saat emas bearish. GoldScalp adalah scalper momentum M15 di mana setiap transaksi punya hard stop-loss dan time-stop. TiGold adalah mesin adaptif gratis dengan disiplin yang sama. Tidak ada yang averaging — win rate yang dipasarkan lebih rendah, tetapi profil risiko yang bisa bertahan dan dapat diverifikasi publik.",
    ],
    faqTitle: "Pertanyaan yang sering diajukan",
    faq: [
      ["Apakah Dralvo EA martingale/grid?", "Bukan. Setiap robot Dralvo — GoldMaster, GoldScalp, dan TiGold — memakai hard stop-loss dan persentase risiko tetap per transaksi. Tidak ada yang averaging, menjalankan grid, atau memperbesar lot setelah rugi."],
      ["Mengapa EA martingale menampilkan kurva ekuitas yang begitu mulus dan sempurna?", "Karena transaksi rugi tidak pernah ditutup dalam keadaan rugi — EA terus menambah sampai harga berbalik, menyembunyikan setiap kerugian sebagai posisi “terbuka”. Kurva tampak tanpa cela sampai satu tren tak berbalik, dan seluruh akun ludes sekaligus."],
      ["Apakah Dralvo menjamin profit atau win rate tinggi?", "Tidak. Dralvo mempublikasikan ekspektasi jujur, termasuk win rate, rentetan kalah terpanjang, dan drawdown maksimum. Target desainnya adalah win rate realistis ~40% dengan rasio risk-reward yang baik — bukan angka 90%+ ala pemasaran."],
      ["Apa jebakan EA emas dengan “win rate 90%”?", "Win rate sangat tinggi biasanya berarti banyak kemenangan kecil dan beberapa kerugian besar — ekspektasi negatif. Dralvo mengoptimalkan ekspektasi (risk-reward), jadi menang lebih jarang tapi menjaga kerugian tetap kecil dan terkendali."],
    ] as [string, string][],
    ctaBacktest: "Lihat backtest nyata",
    ctaTigold: "Dapatkan TiGold gratis",
    disclaimer: "Perbandingan edukatif saja — bukan nasihat keuangan. Trading XAUUSD dan instrumen leverage lain memiliki risiko kerugian besar. Kinerja masa lalu tidak menjamin hasil masa depan.",
  },

});
