import { withLocaleFallback } from "@/lib/i18n";

/** Copy for the /compare ("Dralvo vs grid/martingale") page, in 8 locales.
 *  Product names (Dralvo, GoldMaster, GoldScalp, TiGold, MetaTrader, MT5,
 *  XAUUSD, IB) are kept untranslated as brand/technical terms. */
export const COMPARE_COPY = withLocaleFallback({
  en: {
    back: "Back to Dralvo",
    badge: "Comparison",
    h1: "Dralvo vs grid & martingale gold EAs",
    intro:
      "Most gold EAs sold online run a grid, martingale or averaging-down strategy. Their equity curves look perfect because losing trades are never closed — until one strong trend wipes the account out at once. Dralvo takes the opposite approach: a hard stop-loss on every trade, a fixed percentage of risk, and a fully published track record. Here is the honest, side-by-side difference.",
    th: { dim: "Dimension", grid: "Typical grid / martingale gold EA", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Core risk method", grid: "Grid, martingale or averaging-down — adds to losing positions", dralvo: "Fixed % risk per trade — never averages down" },
      { dim: "Stop-loss", grid: "Often none, or a far “recovery” level that rarely triggers", dralvo: "Hard stop-loss on every trade, plus a time-stop (GoldScalp)" },
      { dim: "Lot size after a loss", grid: "Increases (doubles/multiplies) to “recover”", dralvo: "Unchanged — risk stays constant" },
      { dim: "Typical equity curve", grid: "Smooth and beautiful… until one sudden blow-up", dralvo: "Steady with visible, bounded drawdowns" },
      { dim: "Worst-case outcome", grid: "Full account wipeout in a single adverse trend", dralvo: "Capped drawdown — published, not hidden" },
      { dim: "Behaviour in a strong adverse trend", grid: "Keeps stacking losing positions", dralvo: "Sits idle or exits — capital preservation by design" },
      { dim: "Marketed win rate", grid: "“90%+ wins” (tiny wins, rare catastrophic loss)", dralvo: "Honest (~40%) — the edge is reward-to-risk" },
      { dim: "Transparency", grid: "Hidden logic, cherry-picked screenshots", dralvo: "Full backtest + honest expectations, published openly" },
      { dim: "Data verification", grid: "Vague claims, demo-only screenshots", dralvo: "Real / 100%-real-tick historical data" },
      { dim: "Platform", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Pricing", grid: "Often a costly one-off — then the strategy eats the account", dralvo: "Free (TiGold via Dralvo IB) or Dralvo Unlimited from $59/month" },
    ],
    whyTitle: "Why grid & martingale eventually blow up",
    whyParas: [
      "A martingale or grid system survives by refusing to take a loss. When a trade moves against it, instead of closing it opens more positions at “better” prices and increases size, betting that price will return to break-even. Most of the time it does — which is exactly why the equity curve looks smooth and the marketing can claim a 90%+ win rate.",
      "The problem is the tail. Gold (XAUUSD) trends hard during macro shocks. When price runs in one direction and does not come back, the stacked losing positions grow faster than the account can absorb, and a single move erases months of “wins.” There is no hard stop-loss to cap the damage.",
      "Dralvo is built the other way around. GoldMaster is a patient D1 swing system that trades with the trend and stays out when gold is bearish. GoldScalp is an M5 momentum scalper where every trade has a hard stop-loss and a time-stop. TiGold is a free adaptive engine with the same discipline. None of them average down — a lower marketed win rate, but a survivable, publicly verifiable risk profile.",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      ["Is Dralvo a martingale or grid EA?", "No. Every Dralvo robot — GoldMaster, GoldScalp and TiGold — uses a hard stop-loss and a fixed percentage of risk per trade. None of them average down, run a grid, or increase lot size after a loss."],
      ["Why do martingale EAs show such smooth, perfect equity curves?", "Because losing trades are never closed at a loss — the EA keeps adding to them until price reverts, which hides every loss as an “open” position. The curve looks flawless until one trend does not revert, and the whole account is wiped out at once."],
      ["Does Dralvo guarantee profit or a high win rate?", "No. Dralvo publishes honest expectations, including win rate, the longest losing streak and the maximum drawdown. A realistic ~40% win rate with a strong reward-to-risk ratio is the design goal — not a marketed 90%+ figure."],
      ["What is the catch with a “90% win rate” gold EA?", "A very high win rate usually means many tiny wins and a few enormous losses — negative expectancy. Dralvo optimises expectancy (reward-to-risk), so it wins less often but keeps losses small and controlled."],
    ] as [string, string][],
    ctaBacktest: "See the real backtest",
    ctaTigold: "Get TiGold free",
    disclaimer: "Educational comparison only — not financial advice. Trading XAUUSD and other leveraged instruments involves substantial risk of loss. Past performance does not guarantee future results.",
  },

  vi: {
    back: "Quay lại Dralvo",
    badge: "So sánh",
    h1: "Dralvo vs EA grid & martingale",
    intro:
      "Phần lớn “EA vàng” bán trên mạng chạy chiến lược grid, martingale hoặc nhồi lệnh. Đường vốn trông hoàn hảo vì lệnh thua không bao giờ bị đóng — cho đến khi một con sóng mạnh quét sạch tài khoản trong một lần. Dralvo đi ngược lại: hard stop-loss cho mọi lệnh, rủi ro % cố định, và track record công khai đầy đủ. Đây là khác biệt thẳng thắn, đặt cạnh nhau.",
    th: { dim: "Tiêu chí", grid: "EA grid / martingale điển hình", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Phương pháp rủi ro cốt lõi", grid: "Grid, martingale hoặc nhồi lệnh — cộng thêm vào lệnh đang thua", dralvo: "Rủi ro % cố định mỗi lệnh — không bao giờ nhồi lệnh" },
      { dim: "Stop-loss", grid: "Thường không có, hoặc mức “gỡ” quá xa hiếm khi chạm", dralvo: "Hard stop-loss mỗi lệnh, cộng time-stop (GoldScalp)" },
      { dim: "Khối lượng sau lệnh thua", grid: "Tăng (gấp đôi/nhân lên) để “gỡ”", dralvo: "Không đổi — rủi ro giữ nguyên" },
      { dim: "Đường vốn điển hình", grid: "Mượt và đẹp… đến lúc nổ một phát", dralvo: "Ổn định, drawdown thấy được và có giới hạn" },
      { dim: "Kịch bản xấu nhất", grid: "Cháy sạch tài khoản trong một con sóng ngược", dralvo: "Drawdown bị chặn — công khai, không giấu" },
      { dim: "Khi gặp trend ngược mạnh", grid: "Cứ chồng thêm lệnh thua", dralvo: "Đứng yên hoặc thoát — bảo toàn vốn theo thiết kế" },
      { dim: "Win rate quảng cáo", grid: "“Thắng 90%+” (thắng nhỏ, thua thảm họa hiếm khi)", dralvo: "Trung thực (~40%) — lợi thế nằm ở reward-to-risk" },
      { dim: "Minh bạch", grid: "Giấu logic, ảnh chụp chọn lọc", dralvo: "Backtest đầy đủ + kỳ vọng thật, công khai" },
      { dim: "Kiểm chứng dữ liệu", grid: "Tuyên bố mơ hồ, chỉ ảnh demo", dralvo: "Dữ liệu thật / 100% real-tick" },
      { dim: "Nền tảng", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Giá", grid: "Thường mua đứt đắt — rồi chiến lược ăn sạch tài khoản", dralvo: "Miễn phí (TiGold qua Dralvo IB) hoặc Dralvo Unlimited từ $59/tháng" },
    ],
    whyTitle: "Vì sao grid & martingale rồi cũng cháy",
    whyParas: [
      "Một hệ martingale hay grid tồn tại được nhờ từ chối nhận lỗ. Khi lệnh đi ngược, thay vì đóng, nó mở thêm lệnh ở giá “tốt hơn” và tăng khối lượng, đặt cược rằng giá sẽ quay về hòa vốn. Phần lớn thời gian điều đó xảy ra — đó chính là lý do đường vốn trông mượt và marketing có thể khoe win rate 90%+.",
      "Vấn đề nằm ở phần đuôi. Vàng (XAUUSD) trend rất mạnh trong các cú sốc vĩ mô. Khi giá chạy một chiều và không quay lại, chuỗi lệnh thua phình to nhanh hơn sức chịu của tài khoản, và chỉ một cú chạy xóa sạch nhiều tháng “thắng”. Không có hard stop-loss nào để chặn thiệt hại.",
      "Dralvo được xây theo hướng ngược lại. GoldMaster là hệ swing D1 kiên nhẫn, giao dịch thuận xu hướng và đứng ngoài khi vàng giảm. GoldScalp là scalper momentum M5, mỗi lệnh đều có hard stop-loss và time-stop. TiGold là engine thích ứng miễn phí với cùng kỷ luật. Không cái nào nhồi lệnh — win rate quảng cáo thấp hơn, nhưng hồ sơ rủi ro sống sót được và kiểm chứng công khai.",
    ],
    faqTitle: "Câu hỏi thường gặp",
    faq: [
      ["Dralvo có phải EA martingale/grid không?", "Không. Mọi robot Dralvo — GoldMaster, GoldScalp và TiGold — đều dùng hard stop-loss và rủi ro % cố định mỗi lệnh. Không cái nào nhồi lệnh, chạy grid hay tăng khối lượng sau khi thua."],
      ["Vì sao EA martingale có đường vốn mượt và hoàn hảo đến vậy?", "Vì lệnh thua không bao giờ bị đóng ở mức lỗ — EA cứ cộng thêm cho tới khi giá hồi, che mọi khoản lỗ thành lệnh “đang mở”. Đường vốn trông không tì vết cho đến khi một con sóng không hồi, và cả tài khoản bị quét sạch một lần."],
      ["Dralvo có đảm bảo lợi nhuận hay win rate cao không?", "Không. Dralvo công khai kỳ vọng thật, gồm win rate, chuỗi thua dài nhất và drawdown tối đa. Mục tiêu thiết kế là win rate thực tế ~40% với tỉ lệ reward-to-risk tốt — không phải con số 90%+ kiểu quảng cáo."],
      ["“EA win rate 90%” thì bẫy nằm ở đâu?", "Win rate rất cao thường nghĩa là nhiều lệnh thắng nhỏ và vài lệnh thua khổng lồ — kỳ vọng âm. Dralvo tối ưu kỳ vọng (reward-to-risk), nên thắng ít lần hơn nhưng giữ khoản lỗ nhỏ và kiểm soát được."],
    ] as [string, string][],
    ctaBacktest: "Xem backtest thật",
    ctaTigold: "Nhận TiGold miễn phí",
    disclaimer: "Chỉ là so sánh mang tính giáo dục — không phải lời khuyên đầu tư. Giao dịch XAUUSD và các công cụ đòn bẩy có rủi ro thua lỗ đáng kể. Hiệu suất quá khứ không đảm bảo kết quả tương lai.",
  },

  "pt-BR": {
    back: "Voltar para a Dralvo",
    badge: "Comparação",
    h1: "Dralvo vs EAs de ouro grid & martingale",
    intro:
      "A maioria dos “EAs de ouro” vendidos online roda uma estratégia de grid, martingale ou preço médio. As curvas de capital parecem perfeitas porque as operações perdedoras nunca são fechadas — até que uma tendência forte zere a conta de uma só vez. A Dralvo faz o oposto: um stop-loss fixo em cada operação, um percentual de risco fixo e um histórico totalmente público. Aqui está a diferença honesta, lado a lado.",
    th: { dim: "Dimensão", grid: "EA de ouro grid / martingale típico", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Método de risco central", grid: "Grid, martingale ou preço médio — adiciona a posições perdedoras", dralvo: "Risco % fixo por operação — nunca faz preço médio" },
      { dim: "Stop-loss", grid: "Geralmente nenhum, ou um nível de “recuperação” distante que quase nunca dispara", dralvo: "Stop-loss fixo em cada operação, além de time-stop (GoldScalp)" },
      { dim: "Tamanho do lote após uma perda", grid: "Aumenta (dobra/multiplica) para “recuperar”", dralvo: "Inalterado — o risco permanece constante" },
      { dim: "Curva de capital típica", grid: "Suave e linda… até um estouro repentino", dralvo: "Estável, com drawdowns visíveis e limitados" },
      { dim: "Pior caso", grid: "Conta zerada por completo em uma única tendência adversa", dralvo: "Drawdown limitado — publicado, não escondido" },
      { dim: "Comportamento em tendência adversa forte", grid: "Continua empilhando posições perdedoras", dralvo: "Fica de fora ou sai — preservação de capital por design" },
      { dim: "Taxa de acerto divulgada", grid: "“90%+ de acertos” (ganhos minúsculos, perda catastrófica rara)", dralvo: "Honesta (~40%) — a vantagem é o risco-retorno" },
      { dim: "Transparência", grid: "Lógica oculta, capturas selecionadas", dralvo: "Backtest completo + expectativas honestas, públicas" },
      { dim: "Verificação de dados", grid: "Alegações vagas, capturas só de demo", dralvo: "Dados reais / ticks 100% reais" },
      { dim: "Plataforma", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Preço", grid: "Muitas vezes um pagamento único caro — e então a estratégia devora a conta", dralvo: "Grátis (TiGold via Dralvo IB) ou Dralvo Unlimited a partir de $59/mês" },
    ],
    whyTitle: "Por que grid & martingale acabam estourando",
    whyParas: [
      "Um sistema de martingale ou grid sobrevive recusando-se a assumir uma perda. Quando uma operação vai contra, em vez de fechar abre mais posições a preços “melhores” e aumenta o tamanho, apostando que o preço voltará ao ponto de equilíbrio. Na maioria das vezes volta — é exatamente por isso que a curva de capital parece suave e o marketing pode alegar 90%+ de acertos.",
      "O problema é a cauda. O ouro (XAUUSD) tem tendências fortes durante choques macro. Quando o preço corre numa direção e não volta, as posições perdedoras acumuladas crescem mais rápido do que a conta consegue absorver, e um único movimento apaga meses de “ganhos”. Não há stop-loss fixo para limitar o dano.",
      "A Dralvo é construída ao contrário. O GoldMaster é um sistema swing D1 paciente que opera a favor da tendência e fica de fora quando o ouro está em baixa. O GoldScalp é um scalper de momentum M5 onde cada operação tem stop-loss fixo e time-stop. O TiGold é um motor adaptativo gratuito com a mesma disciplina. Nenhum faz preço médio — uma taxa de acerto divulgada menor, mas um perfil de risco que sobrevive e é verificável publicamente.",
    ],
    faqTitle: "Perguntas frequentes",
    faq: [
      ["A Dralvo é um EA de martingale ou grid?", "Não. Cada robô Dralvo — GoldMaster, GoldScalp e TiGold — usa um stop-loss fixo e um percentual de risco fixo por operação. Nenhum faz preço médio, roda um grid ou aumenta o lote após uma perda."],
      ["Por que EAs de martingale mostram curvas de capital tão suaves e perfeitas?", "Porque as operações perdedoras nunca são fechadas no prejuízo — o EA continua adicionando até o preço reverter, escondendo cada perda como uma posição “aberta”. A curva parece impecável até uma tendência não reverter, e a conta inteira é zerada de uma vez."],
      ["A Dralvo garante lucro ou alta taxa de acerto?", "Não. A Dralvo publica expectativas honestas, incluindo taxa de acerto, a maior sequência de perdas e o drawdown máximo. O objetivo de projeto é uma taxa realista de ~40% com bom risco-retorno — não um 90%+ de marketing."],
      ["Qual é a pegadinha de um EA de ouro com “90% de acerto”?", "Uma taxa de acerto muito alta geralmente significa muitos ganhos minúsculos e algumas perdas enormes — expectativa negativa. A Dralvo otimiza a expectativa (risco-retorno), então ganha menos vezes, mas mantém as perdas pequenas e controladas."],
    ] as [string, string][],
    ctaBacktest: "Ver o backtest real",
    ctaTigold: "Obter o TiGold grátis",
    disclaimer: "Comparação educativa apenas — não é aconselhamento financeiro. Operar XAUUSD e outros instrumentos alavancados envolve risco substancial de perda. Desempenho passado não garante resultados futuros.",
  },

  zh: {
    back: "返回 Dralvo",
    badge: "对比",
    h1: "Dralvo 对比 grid 与 martingale 黄金 EA",
    intro:
      "网上大多数“黄金 EA”运行 grid（网格）、martingale（马丁）或加仓摊平策略。它们的资金曲线看起来完美，因为亏损单从不平仓——直到一波强趋势一次性把账户清零。Dralvo 走相反的路线：每一笔交易都有硬止损、固定百分比风险，以及完整公开的业绩记录。下面是诚实的并排对比。",
    th: { dim: "维度", grid: "典型 grid / martingale 黄金 EA", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "核心风险方式", grid: "网格、马丁或加仓摊平——给亏损单加仓", dralvo: "每笔固定 % 风险——从不摊平加仓" },
      { dim: "止损", grid: "通常没有，或设很远的“补救”位，几乎不会触发", dralvo: "每笔都有硬止损，外加时间止损（GoldScalp）" },
      { dim: "亏损后的手数", grid: "加大（翻倍/倍增）以“补救”", dralvo: "不变——风险保持恒定" },
      { dim: "典型资金曲线", grid: "平滑漂亮……直到一次突然爆仓", dralvo: "稳健，回撤可见且有上限" },
      { dim: "最坏情况", grid: "一波逆势行情整账户清零", dralvo: "回撤封顶——公开，不隐藏" },
      { dim: "强逆势行情中的表现", grid: "继续堆叠亏损单", dralvo: "空仓或离场——按设计保全资金" },
      { dim: "营销宣传的胜率", grid: "“90%+ 胜率”（赢得小，偶尔灾难性亏损）", dralvo: "诚实（约 40%）——优势在于盈亏比" },
      { dim: "透明度", grid: "隐藏逻辑、精挑细选的截图", dralvo: "完整回测 + 诚实预期，公开披露" },
      { dim: "数据验证", grid: "含糊其辞，只有模拟盘截图", dralvo: "真实 / 100% 真实 tick 历史数据" },
      { dim: "平台", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5（Windows）" },
      { dim: "价格", grid: "通常一次性高价——然后策略吃光账户", dralvo: "免费（TiGold 通过 Dralvo IB）或 Dralvo Unlimited，每月 $59 起" },
    ],
    whyTitle: "为什么 grid 与 martingale 终究会爆仓",
    whyParas: [
      "马丁或网格系统靠拒绝认亏来“存活”。当一笔交易走反时，它不平仓，而是在“更好”的价格继续开仓并加大手数，赌价格会回到保本。多数时候确实会——这正是资金曲线看起来平滑、营销能宣称 90%+ 胜率的原因。",
      "问题出在尾部风险。黄金（XAUUSD）在宏观冲击时会强烈单边运行。当价格一路不回头，堆叠的亏损单膨胀的速度超过账户的承受力，一次行情就抹掉数月的“盈利”。没有任何硬止损来封顶损失。",
      "Dralvo 反其道而行。GoldMaster 是耐心的 D1 波段系统，顺势交易，黄金看跌时空仓。GoldScalp 是 M5 动量剥头皮，每笔都有硬止损和时间止损。TiGold 是免费的自适应引擎，纪律相同。它们都不摊平加仓——营销胜率更低，但风险状况可存活且可公开验证。",
    ],
    faqTitle: "常见问题",
    faq: [
      ["Dralvo 是 martingale/grid EA 吗？", "不是。每个 Dralvo 机器人——GoldMaster、GoldScalp 和 TiGold——每笔交易都使用硬止损和固定百分比风险。它们都不摊平、不跑网格，也不会在亏损后加大手数。"],
      ["为什么 martingale EA 的资金曲线如此平滑完美？", "因为亏损单从不在亏损时平仓——EA 不断加仓直到价格回归，把每笔亏损都藏成“浮动”持仓。曲线看起来毫无瑕疵，直到某一波不回头，整个账户被一次性清零。"],
      ["Dralvo 保证盈利或高胜率吗？", "不。Dralvo 公开诚实的预期，包括胜率、最长连亏和最大回撤。设计目标是现实的约 40% 胜率配以良好的盈亏比——而不是营销式的 90%+。"],
      ["“90% 胜率”黄金 EA 的陷阱在哪？", "极高的胜率通常意味着很多小盈利和少数巨额亏损——负期望。Dralvo 优化期望值（盈亏比），所以赢的次数更少，但把亏损控制得小而可控。"],
    ] as [string, string][],
    ctaBacktest: "查看真实回测",
    ctaTigold: "免费获取 TiGold",
    disclaimer: "仅为教育性对比——非投资建议。交易 XAUUSD 及其他杠杆产品涉及重大亏损风险。过往表现不保证未来结果。",
  },

  es: {
    back: "Volver a Dralvo",
    badge: "Comparación",
    h1: "Dralvo vs EAs de oro grid y martingala",
    intro:
      "La mayoría de los “EAs de oro” que se venden online usan una estrategia de grid, martingala o promediado a la baja. Sus curvas de capital se ven perfectas porque las operaciones perdedoras nunca se cierran… hasta que una tendencia fuerte vacía la cuenta de golpe. Dralvo hace lo contrario: un stop-loss fijo en cada operación, un porcentaje de riesgo fijo y un historial totalmente público. Esta es la diferencia honesta, lado a lado.",
    th: { dim: "Dimensión", grid: "EA de oro grid / martingala típico", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Método de riesgo central", grid: "Grid, martingala o promediado — añade a posiciones perdedoras", dralvo: "Riesgo % fijo por operación — nunca promedia a la baja" },
      { dim: "Stop-loss", grid: "A menudo ninguno, o un nivel de “recuperación” lejano que casi nunca salta", dralvo: "Stop-loss fijo en cada operación, más un time-stop (GoldScalp)" },
      { dim: "Tamaño del lote tras una pérdida", grid: "Aumenta (duplica/multiplica) para “recuperar”", dralvo: "Sin cambios — el riesgo se mantiene constante" },
      { dim: "Curva de capital típica", grid: "Suave y bonita… hasta una explosión repentina", dralvo: "Estable, con drawdowns visibles y acotados" },
      { dim: "Peor caso", grid: "Cuenta vaciada por completo en una sola tendencia adversa", dralvo: "Drawdown limitado — publicado, no oculto" },
      { dim: "Comportamiento en una tendencia adversa fuerte", grid: "Sigue apilando posiciones perdedoras", dralvo: "Se queda fuera o sale — preservación del capital por diseño" },
      { dim: "Tasa de acierto publicitada", grid: "“90%+ de aciertos” (ganancias pequeñas, pérdida catastrófica rara)", dralvo: "Honesta (~40%) — la ventaja es el ratio riesgo-beneficio" },
      { dim: "Transparencia", grid: "Lógica oculta, capturas seleccionadas", dralvo: "Backtest completo + expectativas honestas, públicas" },
      { dim: "Verificación de datos", grid: "Afirmaciones vagas, capturas solo de demo", dralvo: "Datos reales / ticks 100% reales" },
      { dim: "Plataforma", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Precio", grid: "A menudo un pago único caro — y luego la estrategia se come la cuenta", dralvo: "Gratis (TiGold vía Dralvo IB) o Dralvo Unlimited desde $59/mes" },
    ],
    whyTitle: "Por qué grid y martingala acaban explotando",
    whyParas: [
      "Un sistema de martingala o grid sobrevive negándose a asumir una pérdida. Cuando una operación va en contra, en vez de cerrarla abre más posiciones a “mejores” precios y aumenta el tamaño, apostando a que el precio volverá al punto de equilibrio. La mayoría de las veces lo hace — por eso la curva de capital se ve suave y el marketing puede presumir de un 90%+ de aciertos.",
      "El problema es la cola. El oro (XAUUSD) tiene tendencias fuertes durante shocks macro. Cuando el precio corre en una dirección y no vuelve, las posiciones perdedoras acumuladas crecen más rápido de lo que la cuenta puede absorber, y un solo movimiento borra meses de “ganancias”. No hay stop-loss fijo que limite el daño.",
      "Dralvo está construido al revés. GoldMaster es un sistema swing D1 paciente que opera a favor de la tendencia y se mantiene fuera cuando el oro es bajista. GoldScalp es un scalper de momentum M5 donde cada operación tiene stop-loss fijo y time-stop. TiGold es un motor adaptativo gratuito con la misma disciplina. Ninguno promedia a la baja — una tasa de acierto publicitada menor, pero un perfil de riesgo que sobrevive y es verificable públicamente.",
    ],
    faqTitle: "Preguntas frecuentes",
    faq: [
      ["¿Es Dralvo un EA de martingala o grid?", "No. Cada robot Dralvo — GoldMaster, GoldScalp y TiGold — usa un stop-loss fijo y un porcentaje de riesgo fijo por operación. Ninguno promedia a la baja, corre un grid ni aumenta el lote tras una pérdida."],
      ["¿Por qué los EAs de martingala muestran curvas tan suaves y perfectas?", "Porque las operaciones perdedoras nunca se cierran con pérdida — el EA sigue añadiendo hasta que el precio revierte, ocultando cada pérdida como una posición “abierta”. La curva parece impecable hasta que una tendencia no revierte y toda la cuenta se vacía de golpe."],
      ["¿Dralvo garantiza beneficios o una tasa de acierto alta?", "No. Dralvo publica expectativas honestas, incluida la tasa de acierto, la racha perdedora más larga y el drawdown máximo. El objetivo de diseño es una tasa realista de ~40% con un buen ratio riesgo-beneficio — no un 90%+ publicitario."],
      ["¿Cuál es la trampa de un EA de oro con “90% de aciertos”?", "Una tasa de acierto muy alta suele significar muchas ganancias diminutas y unas pocas pérdidas enormes — expectativa negativa. Dralvo optimiza la expectativa (riesgo-beneficio), así que gana menos a menudo pero mantiene las pérdidas pequeñas y controladas."],
    ] as [string, string][],
    ctaBacktest: "Ver el backtest real",
    ctaTigold: "Obtener TiGold gratis",
    disclaimer: "Comparación educativa únicamente — no es asesoramiento financiero. Operar XAUUSD y otros instrumentos apalancados implica un riesgo sustancial de pérdida. El rendimiento pasado no garantiza resultados futuros.",
  },

  hi: {
    back: "Dralvo पर वापस",
    badge: "तुलना",
    h1: "Dralvo बनाम grid और martingale गोल्ड EA",
    intro:
      "ऑनलाइन बिकने वाले अधिकतर “गोल्ड EA” grid, martingale या एवरेजिंग-डाउन रणनीति चलाते हैं। उनकी इक्विटी कर्व परफेक्ट दिखती है क्योंकि घाटे वाले ट्रेड कभी बंद नहीं होते — जब तक एक मज़बूत ट्रेंड पूरे खाते को एक ही बार में साफ़ न कर दे। Dralvo इसके उलट करता है: हर ट्रेड पर हार्ड स्टॉप-लॉस, तय प्रतिशत जोखिम, और पूरी तरह सार्वजनिक ट्रैक रिकॉर्ड। यहाँ ईमानदार, आमने-सामने का अंतर है।",
    th: { dim: "पहलू", grid: "सामान्य grid / martingale गोल्ड EA", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "मूल जोखिम तरीका", grid: "Grid, martingale या एवरेजिंग — घाटे वाली पोज़िशन में जोड़ता है", dralvo: "हर ट्रेड पर तय % जोखिम — कभी एवरेज नहीं करता" },
      { dim: "स्टॉप-लॉस", grid: "अक्सर कोई नहीं, या दूर का “रिकवरी” स्तर जो शायद ही चले", dralvo: "हर ट्रेड पर हार्ड स्टॉप-लॉस, साथ में टाइम-स्टॉप (GoldScalp)" },
      { dim: "घाटे के बाद लॉट साइज़", grid: "“रिकवर” करने के लिए बढ़ाता है (दोगुना/गुणा)", dralvo: "अपरिवर्तित — जोखिम स्थिर रहता है" },
      { dim: "सामान्य इक्विटी कर्व", grid: "चिकनी और सुंदर… जब तक एक अचानक ब्लो-अप न हो", dralvo: "स्थिर, दिखने वाला और सीमित ड्रॉडाउन" },
      { dim: "सबसे बुरा परिणाम", grid: "एक ही प्रतिकूल ट्रेंड में पूरा खाता साफ़", dralvo: "ड्रॉडाउन सीमित — सार्वजनिक, छिपा नहीं" },
      { dim: "मज़बूत प्रतिकूल ट्रेंड में व्यवहार", grid: "घाटे वाली पोज़िशन जमा करता रहता है", dralvo: "रुक जाता है या बाहर निकलता है — डिज़ाइन से पूँजी सुरक्षा" },
      { dim: "विज्ञापित जीत दर", grid: "“90%+ जीत” (छोटी जीत, कभी-कभी विनाशकारी हानि)", dralvo: "ईमानदार (~40%) — बढ़त रिस्क-रिवॉर्ड में है" },
      { dim: "पारदर्शिता", grid: "छिपा लॉजिक, चुनिंदा स्क्रीनशॉट", dralvo: "पूरा बैकटेस्ट + ईमानदार अपेक्षाएँ, सार्वजनिक" },
      { dim: "डेटा सत्यापन", grid: "अस्पष्ट दावे, केवल डेमो स्क्रीनशॉट", dralvo: "असली / 100% रियल-टिक ऐतिहासिक डेटा" },
      { dim: "प्लेटफ़ॉर्म", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "मूल्य", grid: "अक्सर महँगा एकमुश्त — फिर रणनीति खाता खा जाती है", dralvo: "मुफ़्त (TiGold, Dralvo IB के ज़रिए) या Dralvo Unlimited $59/माह से" },
    ],
    whyTitle: "grid और martingale आख़िर क्यों फटते हैं",
    whyParas: [
      "मार्टिंगेल या ग्रिड सिस्टम घाटा न मानकर “ज़िंदा” रहता है। जब ट्रेड उल्टा जाता है, तो बंद करने के बजाय वह “बेहतर” कीमतों पर और पोज़िशन खोलता है और साइज़ बढ़ाता है, यह दांव लगाकर कि कीमत ब्रेक-ईवन पर लौटेगी। अधिकतर बार ऐसा होता भी है — इसीलिए इक्विटी कर्व चिकनी दिखती है और मार्केटिंग 90%+ जीत दर का दावा कर पाती है।",
      "समस्या टेल में है। मैक्रो झटकों के दौरान सोना (XAUUSD) ज़ोरदार ट्रेंड करता है। जब कीमत एक दिशा में दौड़ती है और वापस नहीं आती, तो जमा घाटे वाली पोज़िशन खाते की सहन-शक्ति से तेज़ी से बढ़ती हैं, और एक ही चाल महीनों की “जीत” मिटा देती है। नुकसान सीमित करने के लिए कोई हार्ड स्टॉप-लॉस नहीं होता।",
      "Dralvo उल्टी तरह बना है। GoldMaster एक धैर्यवान D1 स्विंग सिस्टम है जो ट्रेंड के साथ ट्रेड करता है और सोना बेयरिश होने पर बाहर रहता है। GoldScalp एक M5 मोमेंटम स्कैल्पर है जहाँ हर ट्रेड पर हार्ड स्टॉप-लॉस और टाइम-स्टॉप होता है। TiGold उसी अनुशासन वाला मुफ़्त अनुकूली इंजन है। इनमें से कोई एवरेज नहीं करता — विज्ञापित जीत दर कम, पर जोखिम प्रोफ़ाइल टिकाऊ और सार्वजनिक रूप से सत्यापन योग्य।",
    ],
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faq: [
      ["क्या Dralvo एक martingale/grid EA है?", "नहीं। हर Dralvo रोबोट — GoldMaster, GoldScalp और TiGold — हर ट्रेड पर हार्ड स्टॉप-लॉस और तय प्रतिशत जोखिम का उपयोग करता है। इनमें से कोई एवरेज नहीं करता, grid नहीं चलाता, और घाटे के बाद लॉट नहीं बढ़ाता।"],
      ["martingale EA की इक्विटी कर्व इतनी चिकनी और परफेक्ट क्यों दिखती है?", "क्योंकि घाटे वाले ट्रेड कभी घाटे में बंद नहीं होते — EA तब तक जोड़ता रहता है जब तक कीमत न लौटे, हर घाटे को “खुली” पोज़िशन के रूप में छिपा देता है। कर्व तब तक निर्दोष दिखती है जब तक एक ट्रेंड न लौटे, और पूरा खाता एक ही बार में साफ़ हो जाए।"],
      ["क्या Dralvo मुनाफ़े या ऊँची जीत दर की गारंटी देता है?", "नहीं। Dralvo ईमानदार अपेक्षाएँ प्रकाशित करता है — जीत दर, सबसे लंबी हार की लड़ी, और अधिकतम ड्रॉडाउन सहित। डिज़ाइन का लक्ष्य अच्छे रिस्क-रिवॉर्ड के साथ यथार्थवादी ~40% जीत दर है — कोई विज्ञापित 90%+ नहीं।"],
      ["“90% जीत दर” वाले गोल्ड EA में पेच क्या है?", "बहुत ऊँची जीत दर का अर्थ अक्सर कई छोटी जीतें और कुछ विशाल हार होता है — नकारात्मक अपेक्षा। Dralvo अपेक्षा (रिस्क-रिवॉर्ड) को अनुकूलित करता है, इसलिए कम बार जीतता है पर हानि छोटी और नियंत्रित रखता है।"],
    ] as [string, string][],
    ctaBacktest: "असली बैकटेस्ट देखें",
    ctaTigold: "TiGold मुफ़्त पाएँ",
    disclaimer: "केवल शैक्षिक तुलना — वित्तीय सलाह नहीं। XAUUSD और अन्य लीवरेज उत्पादों का व्यापार पर्याप्त हानि जोखिम रखता है। पिछला प्रदर्शन भविष्य के परिणामों की गारंटी नहीं देता।",
  },

  id: {
    back: "Kembali ke Dralvo",
    badge: "Perbandingan",
    h1: "Dralvo vs EA emas grid & martingale",
    intro:
      "Sebagian besar “EA emas” yang dijual online menjalankan strategi grid, martingale, atau averaging-down. Kurva ekuitasnya terlihat sempurna karena transaksi rugi tidak pernah ditutup — sampai satu tren kuat menghabiskan akun sekaligus. Dralvo mengambil pendekatan sebaliknya: hard stop-loss di setiap transaksi, persentase risiko tetap, dan rekam jejak yang dipublikasikan penuh. Inilah perbedaan jujurnya, berdampingan.",
    th: { dim: "Dimensi", grid: "EA emas grid / martingale pada umumnya", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Metode risiko inti", grid: "Grid, martingale atau averaging — menambah posisi rugi", dralvo: "Risiko % tetap per transaksi — tidak pernah averaging" },
      { dim: "Stop-loss", grid: "Sering tidak ada, atau level “recovery” jauh yang jarang kena", dralvo: "Hard stop-loss tiap transaksi, plus time-stop (GoldScalp)" },
      { dim: "Ukuran lot setelah rugi", grid: "Bertambah (gandakan/perbesar) untuk “recovery”", dralvo: "Tetap — risiko konstan" },
      { dim: "Kurva ekuitas khas", grid: "Mulus dan indah… sampai satu blow-up mendadak", dralvo: "Stabil, drawdown terlihat dan terbatas" },
      { dim: "Skenario terburuk", grid: "Akun ludes total dalam satu tren berlawanan", dralvo: "Drawdown dibatasi — dipublikasikan, tidak disembunyikan" },
      { dim: "Perilaku saat tren berlawanan kuat", grid: "Terus menumpuk posisi rugi", dralvo: "Diam atau keluar — menjaga modal sesuai desain" },
      { dim: "Win rate yang dipasarkan", grid: "“Menang 90%+” (untung kecil, rugi katastrofik jarang)", dralvo: "Jujur (~40%) — keunggulan ada pada risk-reward" },
      { dim: "Transparansi", grid: "Logika disembunyikan, screenshot pilihan", dralvo: "Backtest penuh + ekspektasi jujur, dipublikasikan" },
      { dim: "Verifikasi data", grid: "Klaim kabur, screenshot demo saja", dralvo: "Data nyata / 100% real-tick historis" },
      { dim: "Platform", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Harga", grid: "Sering sekali bayar mahal — lalu strateginya memakan akun", dralvo: "Gratis (TiGold via Dralvo IB) atau Dralvo Unlimited mulai $59/bulan" },
    ],
    whyTitle: "Mengapa grid & martingale akhirnya meledak",
    whyParas: [
      "Sistem martingale atau grid bertahan dengan menolak menerima kerugian. Saat transaksi berlawanan, alih-alih ditutup, ia membuka lebih banyak posisi di harga “lebih baik” dan memperbesar ukuran, bertaruh harga akan kembali ke titik impas. Sering kali memang begitu — itulah mengapa kurva ekuitas terlihat mulus dan pemasaran bisa mengklaim win rate 90%+.",
      "Masalahnya ada di ekor. Emas (XAUUSD) tren kuat saat guncangan makro. Ketika harga lari satu arah dan tak kembali, posisi rugi yang menumpuk membesar lebih cepat dari kemampuan akun menyerapnya, dan satu pergerakan menghapus “kemenangan” berbulan-bulan. Tidak ada hard stop-loss untuk membatasi kerusakan.",
      "Dralvo dibangun sebaliknya. GoldMaster adalah sistem swing D1 yang sabar, trading searah tren dan diam saat emas bearish. GoldScalp adalah scalper momentum M5 di mana setiap transaksi punya hard stop-loss dan time-stop. TiGold adalah mesin adaptif gratis dengan disiplin yang sama. Tidak ada yang averaging — win rate yang dipasarkan lebih rendah, tetapi profil risiko yang bisa bertahan dan dapat diverifikasi publik.",
    ],
    faqTitle: "Pertanyaan yang sering diajukan",
    faq: [
      ["Apakah Dralvo EA martingale/grid?", "Bukan. Setiap robot Dralvo — GoldMaster, GoldScalp, dan TiGold — memakai hard stop-loss dan persentase risiko tetap per transaksi. Tidak ada yang averaging, menjalankan grid, atau memperbesar lot setelah rugi."],
      ["Mengapa EA martingale menampilkan kurva ekuitas yang begitu mulus dan sempurna?", "Karena transaksi rugi tidak pernah ditutup dalam keadaan rugi — EA terus menambah sampai harga berbalik, menyembunyikan setiap kerugian sebagai posisi “terbuka”. Kurva tampak tanpa cela sampai satu tren tak berbalik, dan seluruh akun ludes sekaligus."],
      ["Apakah Dralvo menjamin profit atau win rate tinggi?", "Tidak. Dralvo mempublikasikan ekspektasi jujur, termasuk win rate, rentetan kalah terpanjang, dan drawdown maksimum. Target desainnya adalah win rate realistis ~40% dengan rasio risk-reward yang baik — bukan angka 90%+ ala pemasaran."],
      ["Apa jebakan EA emas dengan “win rate 90%”?", "Win rate sangat tinggi biasanya berarti banyak kemenangan kecil dan beberapa kerugian besar — ekspektasi negatif. Dralvo mengoptimalkan ekspektasi (risk-reward), jadi menang lebih jarang tapi menjaga kerugian tetap kecil dan terkendali."],
    ] as [string, string][],
    ctaBacktest: "Lihat backtest nyata",
    ctaTigold: "Dapatkan TiGold gratis",
    disclaimer: "Perbandingan edukatif saja — bukan nasihat keuangan. Trading XAUUSD dan instrumen leverage lain memiliki risiko kerugian besar. Kinerja masa lalu tidak menjamin hasil masa depan.",
  },

  ru: {
    back: "Назад к Dralvo",
    badge: "Сравнение",
    h1: "Dralvo против grid и martingale золотых EA",
    intro:
      "Большинство «золотых EA», продаваемых онлайн, используют стратегию сетки (grid), мартингейла или усреднения. Их кривые капитала выглядят идеально, потому что убыточные сделки никогда не закрываются — пока один сильный тренд не обнулит счёт разом. Dralvo делает наоборот: жёсткий стоп-лосс на каждой сделке, фиксированный процент риска и полностью опубликованная история сделок. Вот честное сравнение бок о бок.",
    th: { dim: "Параметр", grid: "Типичный grid / martingale золотой EA", dralvo: "Dralvo (GoldMaster · GoldScalp · TiGold)" },
    rows: [
      { dim: "Базовый метод риска", grid: "Сетка, мартингейл или усреднение — добавляет к убыточным позициям", dralvo: "Фиксированный % риска на сделку — никогда не усредняет" },
      { dim: "Стоп-лосс", grid: "Часто отсутствует или далёкий уровень «восстановления», который почти не срабатывает", dralvo: "Жёсткий стоп-лосс на каждой сделке плюс тайм-стоп (GoldScalp)" },
      { dim: "Размер лота после убытка", grid: "Увеличивается (удвоение/умножение) для «отыгрыша»", dralvo: "Без изменений — риск постоянный" },
      { dim: "Типичная кривая капитала", grid: "Гладкая и красивая… до внезапного обнуления", dralvo: "Стабильная, с видимой и ограниченной просадкой" },
      { dim: "Худший сценарий", grid: "Полное обнуление счёта в одном неблагоприятном тренде", dralvo: "Ограниченная просадка — опубликована, не скрыта" },
      { dim: "Поведение в сильном неблагоприятном тренде", grid: "Продолжает наращивать убыточные позиции", dralvo: "Стоит вне рынка или выходит — сохранение капитала по дизайну" },
      { dim: "Рекламируемый винрейт", grid: "«90%+ побед» (крошечные прибыли, редкий катастрофический убыток)", dralvo: "Честный (~40%) — преимущество в соотношении риск/прибыль" },
      { dim: "Прозрачность", grid: "Скрытая логика, отобранные скриншоты", dralvo: "Полный бэктест + честные ожидания, открыто опубликованы" },
      { dim: "Проверка данных", grid: "Расплывчатые заявления, только демо-скриншоты", dralvo: "Реальные / 100% реальные тиковые исторические данные" },
      { dim: "Платформа", grid: "MetaTrader 4/5", dralvo: "MetaTrader 5 (Windows)" },
      { dim: "Цена", grid: "Часто дорогая разовая покупка — а потом стратегия съедает счёт", dralvo: "Бесплатно (TiGold через Dralvo IB) или Dralvo Unlimited от $59/мес" },
    ],
    whyTitle: "Почему grid и martingale в итоге обнуляют счёт",
    whyParas: [
      "Система мартингейла или сетки выживает, отказываясь фиксировать убыток. Когда сделка идёт против, вместо закрытия она открывает новые позиции по «лучшим» ценам и увеличивает объём, делая ставку на возврат цены к безубытку. Чаще всего так и происходит — именно поэтому кривая капитала выглядит гладкой, а маркетинг заявляет о винрейте 90%+.",
      "Проблема в хвосте. Золото (XAUUSD) сильно трендит во время макрошоков. Когда цена идёт в одну сторону и не возвращается, накопленные убыточные позиции растут быстрее, чем счёт способен выдержать, и одно движение стирает месяцы «побед». Никакого жёсткого стоп-лосса, чтобы ограничить ущерб.",
      "Dralvo построен наоборот. GoldMaster — терпеливая система свинга на D1, торгует по тренду и стоит вне рынка, когда золото медвежье. GoldScalp — импульсный скальпер на M5, где у каждой сделки есть жёсткий стоп-лосс и тайм-стоп. TiGold — бесплатный адаптивный движок с той же дисциплиной. Ни один не усредняет — рекламируемый винрейт ниже, но профиль риска выживаемый и публично проверяемый.",
    ],
    faqTitle: "Частые вопросы",
    faq: [
      ["Dralvo — это martingale/grid EA?", "Нет. Каждый робот Dralvo — GoldMaster, GoldScalp и TiGold — использует жёсткий стоп-лосс и фиксированный процент риска на сделку. Ни один не усредняет, не запускает сетку и не увеличивает лот после убытка."],
      ["Почему у martingale-EA такие гладкие, идеальные кривые капитала?", "Потому что убыточные сделки никогда не закрываются в минус — EA добавляет к ним, пока цена не вернётся, скрывая каждый убыток как «открытую» позицию. Кривая выглядит безупречно, пока один тренд не развернётся, и весь счёт обнуляется разом."],
      ["Гарантирует ли Dralvo прибыль или высокий винрейт?", "Нет. Dralvo публикует честные ожидания, включая винрейт, самую длинную серию убытков и максимальную просадку. Цель дизайна — реалистичный винрейт ~40% с хорошим соотношением риск/прибыль, а не рекламные 90%+."],
      ["В чём подвох золотого EA с «винрейтом 90%»?", "Очень высокий винрейт обычно означает много крошечных прибылей и несколько огромных убытков — отрицательное матожидание. Dralvo оптимизирует матожидание (риск/прибыль), поэтому выигрывает реже, но держит убытки малыми и контролируемыми."],
    ] as [string, string][],
    ctaBacktest: "Смотреть реальный бэктест",
    ctaTigold: "Получить TiGold бесплатно",
    disclaimer: "Только образовательное сравнение — не финансовый совет. Торговля XAUUSD и другими инструментами с плечом несёт существенный риск потерь. Прошлые результаты не гарантируют будущих.",
  },
});
