/**
 * Landing page copy (2-EA showcase). Prose/labels only — numeric EA figures come
 * from `EA_PRODUCTS` in `@/lib/backtest-stats`. vi + en authored; other locales
 * fall back to English via withLocaleFallback.
 *
 * Voice (see docs/DESIGN.md §9): confident, factual, professional. Never expose
 * the EA's internal logic (indicators, filters, SL/TP mechanics).
 */
import { withLocaleFallback } from "@/lib/i18n";

export const LANDING_COPY = withLocaleFallback({
  ar: {
    nav: { products: "المنتجات", evidence: "الأداء", pricing: "الأسعار", tools: "الأدوات", tigold: "TiGold", login: "تسجيل الدخول", cta: "جرّبه" },
    hero: {
      eyebrow: "Dralvo Capital · روبوتات آلية لتداول الذهب",
      titleA: "آلتان. معدن واحد. ",
      titleEm: "نتائج حقيقية.",
      subtitle:
        "روبوتان لتداول الذهب XAUUSD، بأسلوبين — swing صبور وscalp سريع. كلاهما استراتيجيتان مُثبتتان على بيانات سوق حقيقية. بلا martingale، بلا grid، بلا تجميل للأرقام.",
      ctaPrimary: "شاهد المنتجين",
      ctaSecondary: "شاهد الأداء",
      metalNote: ".9999 — بشفافية الذهب الخالص",
      equityLabel: "تيغولد — مباشر على MT5",
      equityRisk: "حساب حقيقي · بدون تعديل",
    },
    products: {
      eyebrow: "منتجان — يُباعان معاً",
      title: "اختر مزاجك.",
      intro: "الانضباط نفسه في المخاطرة، وإيقاع مختلف. كلاهما مُثبَت على بيانات سوق حقيقية.",
      styleTag: { swing: "D1 SWING", scalp: "M15 SCALP", free: "FREE" },
      styleName: { swing: "الصبور — الموجة الكبرى", scalp: "السريع — ضربة الزخم", free: "التكيفي — حماية رأس المال" },
      directionLabels: { long: "متابع للاتجاه", both: "الاتجاهان معاً" },
      headlineLabels: ["العائد (الإعداد المُوصى به)", "Profit Factor", "نسبة الربح", "أقصى تراجع"],
      recommendedRiskLabel: "الإعداد",
      verified: {
        goldmaster: "مُثبَت على 8 سنوات من بيانات الذهب الحقيقية",
        scalp: "مُثبَت على بيانات tick حقيقية 100%",
        tigold: "مجاناً — افتح حساب Dralvo IB",
      },
      pitch: {
        goldmaster:
          "روبوت ذهب لأصحاب الصبر — يركب موجات الذهب الكبرى ويُفضّل الجودة على الكمية. يربح بانتقائية، لكن كل ربح كبير بما يكفي ليقود الأداء.",
        scalp:
          "روبوت ذهب لأصحاب الإيقاع السريع — يلتقط الاندفاعات القوية خلال اليوم ويخرج بنظافة. نسبة ربح عالية، وشبه انعدام للتعرض الليلي.",
        tigold:
          "EA تكيفي لـ XAUUSD — مجاني مدى الحياة عند فتح حساب عبر شريك Dralvo IB. حماية رأس المال بثلاث طبقات: إيقاف مؤقت عند سلسلة الخسائر، ووقف يومي، ومرشّح للأخبار.",
      },
      bullets: {
        goldmaster: [
          "مُثبَت عبر 8 سنوات — خلال كل دورة صعود وهبوط للذهب",
          "يستفيد من بيانات التمركز المؤسسي لقراءة تدفق الأموال الكبيرة",
          "انضباط مطلق في المخاطرة: كل صفقة محمية، ولا تُترك في خسارة أبداً",
        ],
        scalp: [
          "مُثبَت على بيانات tick حقيقية 100% · إيجابي خارج العينة على مستويات المخاطرة الثلاثة",
          "بلا grid · بلا martingale · بلا تعزيز في الخسارة",
          "دخول وخروج حاسمان، وأدنى تعرض ليلي",
        ],
        tigold: [
          "مجاني مدى الحياة — فقط افتح حساباً عبر رابط Dralvo IB",
          "يعمل على XAUUSD · وقف خسارة متحرك ذكي",
          "حماية رأس المال بثلاث طبقات: سلسلة خسائر ← إيقاف مؤقت، خسارة يومية ← وقف، أخبار ← تجنّب",
        ],
      },
      cta: "احصل عليه",
      viewReport: "عرض التقرير الكامل",
      evidenceEyebrow: "أداء مُثبَت",
      evidenceTitle: "الأرقام تتحدث.",
      matrix: { title: "ملف المخاطرة", risk: "الإعداد", ret: "العائد", dd: "أقصى DD", pf: "PF", cagr: "سنوياً", trades: "الصفقات" },
      statLabels: { trades: "إجمالي الصفقات", winRate: "نسبة الربح", avgWin: "متوسط الربح", avgLoss: "متوسط الخسارة", rr: "ربح/خسارة", avgHold: "متوسط مدة الاحتفاظ", streak: "سلسلة ر/خ" },
      monthlyTitle: "الأرباح الشهرية",
      badgePopular: "الأكثر رواجاً",
      badgePro: "احترافي",
    },
    trust: {
      eyebrow: "لماذا يمكنك الوثوق به",
      title: "على خلاف 99% من روبوتات الذهب.",
      items: [
        { title: "بلا martingale / grid", body: "لكل صفقة سقف مخاطرة واضح. بلا تعزيز في الخسارة، وبلا الاحتفاظ بالصفقات الخاسرة — منحنى رأس المال ليس قنبلة موقوتة." },
        { title: "مُثبَت على بيانات حقيقية", body: "GoldMaster عبر 8 سنوات من الذهب، وScalp على tick حقيقية 100%. الأداء علني — بلا نوافذ منتقاة." },
        { title: "بيانات مؤسسية", body: "يستفيد من بيانات التمركز المؤسسي لقراءة سلوك الأموال الذكية، لا مجرد رسم للمخططات." },
        { title: "شفاف", body: "العائد ونسبة الربح والتراجع جميعها علنية. نعرض الأرقام كتقرير فحص وتحليل." },
      ],
    },
    tools: {
      eyebrow: "مجاناً",
      title: "حاسبة حجم اللوت — سريعة ودقيقة.",
      body: "احسب حجم المركز انطلاقاً من الرصيد ونسبة المخاطرة ووقف الخسارة. تدعم XAUUSD وأزواج FX الرئيسية. لا حاجة لحساب — أداة مجانية من Dralvo.",
      cta: "افتح حاسبة اللوت",
      note: "لكل متداول.",
    },
    pricing: {
      eyebrow: "الأسعار",
      title: "استأجر روبوتاً، وابدأ اليوم.",
      intro: "ابدأ مجاناً عبر Dralvo IB، أو افتح كامل المنظومة مع Dralvo VIP. ألغِ في أي وقت.",
      periods: { monthly: "شهر واحد", sixmo: "6 أشهر", yearly: "سنة واحدة" },
      save: { sixmo: "وفّر 15%", yearly: "وفّر 30%" },
      perMonth: "/شهرياً",
      popular: "الأكثر رواجاً",
      cancelNote: "ألغِ في أي وقت · بلا عقد · دعم التثبيت مشمول.",
      tiers: [
        { id: "free", name: "Free", tagline: "احصل على EA مجاناً عبر Dralvo IB", cta: "افتح حساباً واحصل على EA", features: ["TiGold EA مجاناً", "حساب MT5 حقيقي واحد عبر IB", "حاسبة اللوت", "مجتمع Telegram", "تحديثات EA أساسية"] },
        { id: "unlimited", name: "Dralvo VIP", tagline: "كامل منظومة Dralvo", cta: "افتح كل Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Telegram VIP", "تحديثات EA مستمرة", "دعم التثبيت", "VPS واحد مشمول", "وصول مبكر إلى EA الجديدة", "دعم ذو أولوية"] },
      ],
    },
    faq: {
      eyebrow: "الأسئلة الشائعة",
      title: "كل ما تحتاج معرفته.",
      items: [
        ["كيف تختلف الروبوتات؟", "GoldMaster هو swing على D1 — صبور، صفقات قليلة، يركب الموجات الكبرى. GoldScalp هو M15 — دخول سريع خلال اليوم، وخروج ضمن اليوم نفسه. TiGold محرك تكيفي مجاني (عبر Dralvo IB). وباقة Dralvo VIP تتيح لك تشغيل الثلاثة."],
        ["GoldMaster يربح 39% — كيف يكون مربحاً؟", "لأن كل ربح أكبر بكثير من كل خسارة. تخسر مراراً أكثر لكنك تربح بما يكفي لقيادة الأداء. إنها ميزة غير متماثلة."],
        ["هل يوجد martingale / grid؟", "إطلاقاً لا. كلا الروبوتين يحدّان المخاطرة بوضوح في كل صفقة، بلا تعزيز في الخسارة، وبلا الاحتفاظ بالصفقات الخاسرة."],
        ["ماذا أحتاج لتشغيله؟", "MetaTrader 5 + حساب يتضمن الذهب (XAUUSD)، ويُفضّل بفارق سعر منخفض. يُنصح باستخدام VPS لتشغيل متواصل 24/5 دون انقطاع."],
        ["كيف يعمل الاستئجار؟", "تختار دورة شهر واحد / 6 أشهر / سنة واحدة. يُفعَّل الروبوت طوال سريان باقتك ويرتبط بحساب MT5 الخاص بك."],
        ["هل يمكنني الإلغاء؟", "نعم، في أي وقت — بلا عقد. تظل باقتك سارية حتى نهاية الدورة التي دفعت مقابلها."],
        ["هل أحتاج خبرة في التداول؟", "لا. الروبوت آلي بالكامل. تُثبّته مرة واحدة. نوصي بتجربته على حساب demo قبل الانتقال إلى الحساب الحقيقي."],
        ["هل الربح مضمون؟", "لا — ولا تثق بمن يعدك بذلك. الأرقام نتائج مُثبتة على بيانات سابقة. نحن نوفّر أداة، لا وعداً."],
      ],
      notFound: "سؤال آخر؟",
      telegram: "راسلنا على Telegram",
    },
    finalCta: {
      eyebrow: "جاهز؟",
      title: "دع الروبوت يتداول. وأنت تحافظ على الانضباط.",
      body: "ابدأ مجاناً بالمؤشر والأدوات والمجتمع. أو استأجر روبوتاً ودعه يعمل 24/5 على حسابك.",
      primaryCta: "شاهد باقات الاستئجار",
      secondaryCta: "انضم إلى مجتمع Telegram",
      guarantee: "ألغِ في أي وقت · بلا عقد · دعم التثبيت",
    },
    footer: {
      tagline: "Dralvo Capital — روبوتات آلية لتداول الذهب. استراتيجيات مُثبتة على بيانات حقيقية.",
      product: "المنتجات",
      company: "الشركة",
      legal: "الشؤون القانونية",
      goldmaster: "GoldMaster (D1)",
      scalp: "GoldScalp (M15)",
      tigold: "TiGold (مجاناً)",
      tools: "حاسبة اللوت",
      trackRecord: "الأداء",
      compare: "Dralvo مقابل روبوتات grid/martingale",
      telegram: "Telegram",
      login: "تسجيل الدخول",
      privacy: "الخصوصية",
      terms: "الشروط",
      disclaimer: "إخلاء المسؤولية",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  vi: {
    nav: { products: "Sản phẩm", evidence: "Hiệu suất", pricing: "Bảng giá", tools: "Công cụ", tigold: "TiGold", login: "Đăng nhập", cta: "Dùng thử" },
    hero: {
      eyebrow: "Dralvo Capital · Robot giao dịch vàng tự động",
      titleA: "Hai cỗ máy. Một kim loại. ",
      titleEm: "Kết quả thật.",
      subtitle:
        "Hai robot vàng XAUUSD, hai phong cách — swing kiên nhẫn và scalp tốc độ. Cả hai đều là chiến lược đã được kiểm chứng trên dữ liệu thật. Không Martingale, không Grid, không tô vẽ.",
      ctaPrimary: "Xem 2 sản phẩm",
      ctaSecondary: "Xem hiệu suất",
      metalNote: ".9999 — minh bạch như vàng nguyên chất",
      equityLabel: "TiGold — chạy trực tiếp trên MT5",
      equityRisk: "Tài khoản thật · không chỉnh sửa",
    },
    products: {
      eyebrow: "Hai sản phẩm — bán song song",
      title: "Chọn khẩu vị của bạn.",
      intro:
        "Cùng triết lý kỷ luật rủi ro, khác nhịp giao dịch. Cả hai đều được kiểm chứng trên dữ liệu thị trường thật.",
      styleTag: { swing: "D1 SWING", scalp: "M15 SCALP", free: "FREE" },
      styleName: { swing: "Kiên nhẫn — sóng lớn", scalp: "Tốc độ — xung lực", free: "Thích ứng — bảo vệ vốn" },
      directionLabels: { long: "Thuận xu hướng tăng", both: "Hai chiều" },
      headlineLabels: ["Lợi nhuận (cấu hình khuyến nghị)", "Profit Factor", "Tỷ lệ thắng", "Sụt giảm tối đa"],
      recommendedRiskLabel: "Cấu hình",
      verified: {
        goldmaster: "Kiểm chứng trên 8 năm dữ liệu vàng thật",
        scalp: "Kiểm chứng trên dữ liệu tick thật 100%",
        tigold: "Miễn phí — mở tài khoản IB Dralvo",
      },
      pitch: {
        goldmaster:
          "Robot vàng cho người kiên nhẫn — bám theo những con sóng lớn của vàng, ưu tiên chất lượng hơn số lượng. Thắng chọn lọc nhưng mỗi lần thắng đủ lớn để dẫn dắt hiệu suất.",
        scalp:
          "Robot vàng cho người thích nhịp nhanh — nắm bắt các đợt biến động mạnh trong ngày, vào ra gọn gàng. Tỷ lệ thắng cao, hầu như không ôm lệnh qua đêm.",
        tigold:
          "EA thích ứng cho XAUUSD — miễn phí trọn đời khi mở tài khoản qua đối tác IB của Dralvo. 3 lớp bảo vệ vốn: chặn chuỗi thua, giới hạn lỗ ngày, lọc tin tức.",
      },
      bullets: {
        goldmaster: [
          "Kiểm chứng qua 8 năm — đi qua mọi chu kỳ tăng/giảm của vàng",
          "Tận dụng dữ liệu định vị tổ chức để đọc dòng tiền lớn",
          "Kỷ luật rủi ro tuyệt đối: mỗi lệnh được bảo vệ, không gồng lỗ",
        ],
        scalp: [
          "Kiểm chứng trên dữ liệu tick thật 100% · OOS dương cả 3 mức rủi ro",
          "KHÔNG Grid · KHÔNG Martingale · KHÔNG nhồi lệnh",
          "Vào ra dứt khoát, hạn chế tối đa rủi ro qua đêm",
        ],
        tigold: [
          "Miễn phí trọn đời — chỉ cần mở tài khoản qua link IB Dralvo",
          "Chạy XAUUSD · Trailing stop thông minh",
          "3 lớp bảo vệ vốn: chuỗi thua → tạm nghỉ, lỗ ngày → dừng, tin tức → né",
        ],
      },
      cta: "Sở hữu",
      viewReport: "Xem báo cáo đầy đủ",
      evidenceEyebrow: "Hiệu suất đã kiểm chứng",
      evidenceTitle: "Số liệu nói thay lời.",
      matrix: { title: "Hồ sơ rủi ro", risk: "Cấu hình", ret: "Lợi nhuận", dd: "Max DD", pf: "PF", cagr: "Mỗi năm", trades: "Lệnh" },
      statLabels: { trades: "Tổng lệnh", winRate: "Tỷ lệ thắng", avgWin: "Lãi TB", avgLoss: "Lỗ TB", rr: "Lãi/Lỗ", avgHold: "Giữ lệnh TB", streak: "Chuỗi T/B" },
      monthlyTitle: "Lãi theo tháng",
      badgePopular: "Phổ biến",
      badgePro: "Chuyên nghiệp",
    },
    trust: {
      eyebrow: "Vì sao tin được",
      title: "Khác 99% robot vàng trên thị trường.",
      items: [
        { title: "Không Martingale / Grid", body: "Mỗi lệnh đều được giới hạn rủi ro rõ ràng. Không nhồi lệnh, không gồng lỗ — đường vốn không phải 'bom hẹn giờ'." },
        { title: "Kiểm chứng dữ liệu thật", body: "GoldMaster qua 8 năm vàng, Scalp trên tick thật 100%. Hiệu suất công khai, không chọn lọc giai đoạn đẹp." },
        { title: "Dữ liệu tổ chức", body: "Tận dụng dữ liệu định vị của dòng tiền tổ chức — đọc hành vi smart-money, không chỉ vẽ chart." },
        { title: "Minh bạch", body: "Lợi nhuận, tỷ lệ thắng, sụt giảm vốn đều công khai. Chúng tôi trình bày số liệu như một bản kiểm định." },
      ],
    },
    tools: {
      eyebrow: "Miễn phí",
      title: "Công cụ tính lot — nhanh, chính xác.",
      body: "Tính khối lượng giao dịch theo số dư, % rủi ro, và stop loss. Hỗ trợ XAUUSD và các cặp FX chính. Không cần tài khoản — công cụ miễn phí của Dralvo.",
      cta: "Mở công cụ tính lot",
      note: "Dành cho mọi trader.",
    },
    pricing: {
      eyebrow: "Bảng giá",
      title: "Thuê robot, bắt đầu hôm nay.",
      intro: "Bắt đầu miễn phí qua Dralvo IB, hoặc mở khóa toàn bộ hệ sinh thái với gói Dralvo VIP. Hủy bất cứ lúc nào.",
      periods: { monthly: "1 tháng", sixmo: "6 tháng", yearly: "1 năm" },
      save: { sixmo: "tiết kiệm 15%", yearly: "tiết kiệm 30%" },
      perMonth: "/tháng",
      popular: "Phổ biến",
      cancelNote: "Hủy bất cứ lúc nào · không ràng buộc hợp đồng · hỗ trợ cài đặt.",
      tiers: [
        { id: "free", name: "Free", tagline: "Nhận EA miễn phí qua Dralvo IB", cta: "Mở tài khoản nhận EA", features: ["TiGold EA miễn phí", "1 tài khoản MT5 thật qua IB", "Công cụ tính lot", "Telegram Community", "Cập nhật EA cơ bản"] },
        { id: "unlimited", name: "Dralvo VIP", tagline: "Toàn bộ hệ sinh thái Dralvo", cta: "Mở khóa toàn bộ Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Telegram VIP", "Cập nhật EA liên tục", "Hỗ trợ cài đặt", "Truy cập sớm EA mới", "Ưu tiên hỗ trợ"] },
      ],
    },
    faq: {
      eyebrow: "Hỏi đáp",
      title: "Mọi điều bạn cần biết.",
      items: [
        ["Các robot khác nhau thế nào?", "GoldMaster là swing D1 — kiên nhẫn, ít lệnh, giữ theo sóng lớn. GoldScalp là M15 — vào theo nhịp nhanh, chốt trong ngày. TiGold là engine thích ứng (miễn phí qua Dralvo IB). Gói Dralvo VIP cho bạn chạy cả ba."],
        ["GoldMaster thắng 39% — sao vẫn lãi?", "Vì mỗi lệnh thắng lớn hơn nhiều so với mỗi lệnh thua. Thua nhiều lần hơn nhưng mỗi lần thắng đủ to để dẫn dắt hiệu suất. Đây là lợi thế bất đối xứng."],
        ["Có Martingale / Grid không?", "Tuyệt đối không. Cả 2 robot đều giới hạn rủi ro rõ ràng trên mỗi lệnh, không nhồi lệnh, không gồng lỗ."],
        ["Tôi cần gì để chạy?", "MetaTrader 5 + tài khoản có vàng (XAUUSD), khuyến nghị tài khoản spread thấp. Nên dùng VPS để robot chạy 24/5 không gián đoạn."],
        ["Thuê hoạt động thế nào?", "Bạn chọn chu kỳ 1 tháng / 6 tháng / 1 năm. Robot kích hoạt theo gói còn hiệu lực và gắn với tài khoản MT5 của bạn."],
        ["Tôi hủy được không?", "Được, bất cứ lúc nào — không ràng buộc hợp đồng. Gói vẫn chạy hết chu kỳ bạn đã thanh toán."],
        ["Tôi cần kinh nghiệm trading không?", "Không. Robot tự động hoàn toàn. Bạn chỉ cần cài đặt một lần. Khuyến nghị chạy thử trên tài khoản demo trước khi vào tiền thật."],
        ["Có cam kết lợi nhuận không?", "Không — và đừng tin ai cam kết điều đó. Số liệu là kết quả kiểm chứng trên dữ liệu quá khứ. Chúng tôi cung cấp công cụ, không bán lời hứa."],
      ],
      notFound: "Còn câu hỏi khác?",
      telegram: "Nhắn Telegram",
    },
    finalCta: {
      eyebrow: "Sẵn sàng?",
      title: "Để robot giao dịch. Bạn giữ kỷ luật.",
      body: "Bắt đầu miễn phí với indicator, công cụ và cộng đồng. Hoặc thuê robot và để nó làm việc 24/5 trên tài khoản của bạn.",
      primaryCta: "Xem gói thuê",
      secondaryCta: "Vào cộng đồng Telegram",
      guarantee: "Hủy bất cứ lúc nào · Không ràng buộc · Hỗ trợ cài đặt",
    },
    footer: {
      tagline: "Dralvo Capital — robot giao dịch vàng tự động. Chiến lược kiểm chứng trên dữ liệu thật.",
      product: "Sản phẩm",
      company: "Công ty",
      legal: "Pháp lý",
      goldmaster: "GoldMaster (D1)",
      scalp: "GoldScalp (M15)",
      tigold: "TiGold (miễn phí)",
      tools: "Công cụ tính lot",
      trackRecord: "Hiệu suất",
      compare: "Dralvo vs EA grid/martingale",
      telegram: "Telegram",
      login: "Đăng nhập",
      privacy: "Bảo mật",
      terms: "Điều khoản",
      disclaimer: "Miễn trừ trách nhiệm",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  en: {
    nav: { products: "Products", evidence: "Performance", pricing: "Pricing", tools: "Tools", tigold: "TiGold", login: "Log in", cta: "Try it" },
    hero: {
      eyebrow: "Dralvo Capital · Automated gold trading robots",
      titleA: "Two machines. One metal. ",
      titleEm: "Real results.",
      subtitle:
        "Two XAUUSD gold robots, two styles — patient swing and fast scalp. Both are strategies verified on real market data. No martingale, no grid, no window dressing.",
      ctaPrimary: "See both products",
      ctaSecondary: "See performance",
      metalNote: ".9999 — as transparent as pure gold",
      equityLabel: "TiGold — live in MT5",
      equityRisk: "Real account · unedited",
    },
    products: {
      eyebrow: "Two products — sold in parallel",
      title: "Pick your temper.",
      intro: "Same risk discipline, different cadence. Both verified on real market data.",
      styleTag: { swing: "D1 SWING", scalp: "M15 SCALP", free: "FREE" },
      styleName: { swing: "Patient — the long wave", scalp: "Fast — the momentum strike", free: "Adaptive — capital protection" },
      directionLabels: { long: "Trend-following", both: "Both directions" },
      headlineLabels: ["Return (recommended config)", "Profit Factor", "Win rate", "Max drawdown"],
      recommendedRiskLabel: "Config",
      verified: {
        goldmaster: "Verified on 8 years of real gold data",
        scalp: "Verified on 100% real tick data",
        tigold: "Free — open a Dralvo IB account",
      },
      pitch: {
        goldmaster:
          "A gold robot for the patient — it rides gold's major waves and favors quality over quantity. It wins selectively, but each win is big enough to drive performance.",
        scalp:
          "A gold robot for the fast-paced — it captures strong intraday bursts and exits cleanly. High win rate, almost no overnight exposure.",
        tigold:
          "An adaptive EA for XAUUSD — free for life when you open an account through a Dralvo IB partner. 3-layer capital protection: loss-streak pause, daily stop, and news filter.",
      },
      bullets: {
        goldmaster: [
          "Verified across 8 years — through every gold bull and bear cycle",
          "Leverages institutional positioning data to read big-money flow",
          "Absolute risk discipline: every trade is protected, never held in loss",
        ],
        scalp: [
          "Verified on 100% real tick data · out-of-sample positive on all 3 risk tiers",
          "NO grid · NO martingale · NO averaging down",
          "Decisive entries and exits, minimal overnight exposure",
        ],
        tigold: [
          "Free for life — just open an account via the Dralvo IB link",
          "Runs on XAUUSD · Smart trailing stop",
          "3-layer capital protection: loss streak → pause, daily loss → stop, news → avoid",
        ],
      },
      cta: "Get",
      viewReport: "View full report",
      evidenceEyebrow: "Verified performance",
      evidenceTitle: "The numbers speak.",
      matrix: { title: "Risk profile", risk: "Config", ret: "Return", dd: "Max DD", pf: "PF", cagr: "Per year", trades: "Trades" },
      statLabels: { trades: "Total trades", winRate: "Win rate", avgWin: "Avg win", avgLoss: "Avg loss", rr: "Win/Loss", avgHold: "Avg hold", streak: "Streak W/L" },
      monthlyTitle: "Monthly gains",
      badgePopular: "Popular",
      badgePro: "Professional",
    },
    trust: {
      eyebrow: "Why you can trust it",
      title: "Unlike 99% of gold robots.",
      items: [
        { title: "No martingale / grid", body: "Every trade has a clear risk cap. No averaging down, no holding losers — the equity curve isn't a time bomb." },
        { title: "Verified on real data", body: "GoldMaster across 8 years of gold, Scalp on 100% real ticks. Performance is public — no cherry-picked windows." },
        { title: "Institutional data", body: "Leverages institutional positioning data to read smart-money behavior, not just chart drawing." },
        { title: "Transparent", body: "Return, win rate and drawdown are all public. We present the numbers like an assay report." },
      ],
    },
    tools: {
      eyebrow: "Free",
      title: "Lot size calculator — fast, accurate.",
      body: "Calculate position size from balance, risk %, and stop loss. Supports XAUUSD and major FX pairs. No account needed — a free Dralvo tool.",
      cta: "Open lot calculator",
      note: "For every trader.",
    },
    pricing: {
      eyebrow: "Pricing",
      title: "Rent a robot, start today.",
      intro: "Start free through Dralvo IB, or unlock the entire ecosystem with Dralvo VIP. Cancel anytime.",
      periods: { monthly: "1 month", sixmo: "6 months", yearly: "1 year" },
      save: { sixmo: "save 15%", yearly: "save 30%" },
      perMonth: "/mo",
      popular: "Popular",
      cancelNote: "Cancel anytime · no contract · install support included.",
      tiers: [
        { id: "free", name: "Free", tagline: "Get the EA free via Dralvo IB", cta: "Open account, get the EA", features: ["TiGold EA free", "1 real MT5 account via IB", "Lot calculator", "Telegram community", "Basic EA updates"] },
        { id: "unlimited", name: "Dralvo VIP", tagline: "The entire Dralvo ecosystem", cta: "Unlock all of Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Telegram VIP", "Continuous EA updates", "Install support", "1 VPS included", "Early access to new EAs", "Priority support"] },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Everything you need to know.",
      items: [
        ["How do the robots differ?", "GoldMaster is a D1 swing — patient, few trades, riding the big waves. GoldScalp is M15 — fast intraday entries, exits within the day. TiGold is a free adaptive engine (via Dralvo IB). Dralvo VIP lets you run all three."],
        ["GoldMaster wins 39% — how is it profitable?", "Because each win is far bigger than each loss. You lose more often but win big enough to drive performance. It's an asymmetric edge."],
        ["Any martingale / grid?", "Absolutely none. Both robots cap risk clearly per trade, no averaging down, no holding losers."],
        ["What do I need to run it?", "MetaTrader 5 + an account with gold (XAUUSD), preferably low-spread. A VPS is recommended for uninterrupted 24/5 operation."],
        ["How does renting work?", "You pick a 1-month / 6-month / 1-year cycle. The robot activates for your active plan and is bound to your MT5 account."],
        ["Can I cancel?", "Yes, anytime — no contract. Your plan runs to the end of the cycle you've paid for."],
        ["Do I need trading experience?", "No. The robot is fully automated. You install it once. We recommend a demo run before going live."],
        ["Is profit guaranteed?", "No — and don't trust anyone who promises it. The figures are verified on past data. We provide a tool, not a promise."],
      ],
      notFound: "Another question?",
      telegram: "Message us on Telegram",
    },
    finalCta: {
      eyebrow: "Ready?",
      title: "Let the robot trade. You keep the discipline.",
      body: "Start free with the indicator, tools and community. Or rent a robot and let it work 24/5 on your account.",
      primaryCta: "See rental plans",
      secondaryCta: "Join the Telegram community",
      guarantee: "Cancel anytime · No contract · Install support",
    },
    footer: {
      tagline: "Dralvo Capital — automated gold trading robots. Strategies verified on real data.",
      product: "Products",
      company: "Company",
      legal: "Legal",
      goldmaster: "GoldMaster (D1)",
      scalp: "GoldScalp (M15)",
      tigold: "TiGold (free)",
      tools: "Lot calculator",
      trackRecord: "Performance",
      compare: "Dralvo vs grid/martingale EAs",
      telegram: "Telegram",
      login: "Log in",
      privacy: "Privacy",
      terms: "Terms",
      disclaimer: "Disclaimer",
      copyright: "© 2026 Dralvo Capital.",
    },
  },

  // Partial translations — any key omitted deep-merges to English (withLocaleFallback).
  es: {
    nav: { products: "Productos", evidence: "Rendimiento", pricing: "Precios", tools: "Herramientas", login: "Entrar", cta: "Probar" },
    hero: {
      eyebrow: "Dralvo Capital · Robots de trading de oro automáticos",
      titleA: "Dos máquinas. Un metal. ", titleEm: "Resultados reales.",
      subtitle: "Dos robots de oro XAUUSD, dos estilos — swing paciente y scalp veloz. Ambos son estrategias verificadas con datos reales. Sin martingala, sin grid, sin maquillaje.",
      ctaPrimary: "Ver ambos productos", ctaSecondary: "Ver rendimiento",
      metalNote: ".9999 — transparente como el oro puro",
      equityLabel: "TiGold — en vivo en MT5", equityRisk: "Cuenta real · sin editar",
    },
    products: {
      eyebrow: "Dos productos — en paralelo", title: "Elige tu estilo.",
      intro: "Misma disciplina de riesgo, distinto ritmo. Ambos verificados con datos reales de mercado.",
      styleName: { swing: "Paciente — la gran ola", scalp: "Rápido — el golpe de momentum", free: "Adaptativo — protección del capital" },
      directionLabels: { long: "Solo a favor de tendencia", both: "Ambas direcciones" },
      headlineLabels: ["Retorno (config. recom.)", "Profit Factor", "Tasa de acierto", "Drawdown máx."],
      recommendedRiskLabel: "Config.",
      verified: { goldmaster: "Verificado en 8 años de datos reales de oro", scalp: "Verificado en datos de ticks 100% reales", tigold: "Gratis — abre una cuenta Dralvo IB" },
      pitch: {
        goldmaster: "Un robot de oro para los pacientes: cabalga las grandes olas del oro y prioriza la calidad sobre la cantidad. Gana de forma selectiva, pero cada ganancia es lo bastante grande para impulsar el rendimiento.",
        scalp: "Un robot de oro para el ritmo rápido: captura fuertes impulsos intradía y sale limpiamente. Alta tasa de acierto, casi sin exposición nocturna.",
        tigold: "Un EA adaptativo para XAUUSD: gratis de por vida al abrir una cuenta con un socio IB de Dralvo. Protección de capital en 3 capas: pausa por racha perdedora, stop diario y filtro de noticias.",
      },
      bullets: {
        goldmaster: ["Verificado a lo largo de 8 años — por cada ciclo alcista y bajista del oro", "Aprovecha datos de posicionamiento institucional para leer el flujo del dinero grande", "Disciplina de riesgo absoluta: cada operación está protegida, nunca se mantiene en pérdida"],
        scalp: ["Verificado en datos de ticks 100% reales · positivo fuera de muestra en los 3 niveles", "SIN grid · SIN martingala · SIN promediar a la baja", "Entradas y salidas decididas, mínima exposición nocturna"],
        tigold: ["Gratis de por vida — solo abre una cuenta vía el enlace IB de Dralvo", "Funciona en XAUUSD · Trailing stop inteligente", "Protección de capital en 3 capas: racha perdedora → pausa, pérdida diaria → stop, noticias → evitar"],
      },
      badgePopular: "Popular",
      badgePro: "Profesional",
      cta: "Obtener", viewReport: "Ver informe completo",
      evidenceEyebrow: "Rendimiento verificado", evidenceTitle: "Los números hablan.",
      matrix: { title: "Perfil de riesgo", risk: "Config.", ret: "Retorno", dd: "DD máx.", pf: "PF", cagr: "Anual", trades: "Ops." },
      statLabels: { trades: "Operaciones", winRate: "Tasa de acierto", avgWin: "Gan. media", avgLoss: "Pérd. media", rr: "Gan/Pérd", avgHold: "Duración media", streak: "Racha G/P" },
      monthlyTitle: "Ganancias mensuales",
    },
    trust: {
      eyebrow: "Por qué confiar", title: "Distinto al 99% de los robots de oro.",
      items: [
        { title: "Sin martingala / grid", body: "Cada operación tiene un límite de riesgo claro. Sin promediar a la baja, sin mantener perdedoras — la curva de capital no es una bomba de tiempo." },
        { title: "Verificado con datos reales", body: "GoldMaster a lo largo de 8 años de oro, Scalp en ticks 100% reales. El rendimiento es público — sin ventanas seleccionadas." },
        { title: "Datos institucionales", body: "Aprovecha datos de posicionamiento institucional para leer el comportamiento del smart-money, no solo dibujar gráficos." },
        { title: "Transparente", body: "Retorno, tasa de acierto y drawdown son todos públicos. Presentamos los números como un informe de ensayo." },
      ],
    },
    faq: {
      eyebrow: "Preguntas frecuentes", title: "Todo lo que necesitas saber.",
      items: [
        ["¿En qué se diferencian los robots?", "GoldMaster es swing D1 — paciente, pocas operaciones, sigue las grandes olas. GoldScalp es M15 — entradas rápidas, cierre en el día. TiGold es un motor adaptativo (gratis vía Dralvo IB). El plan Dralvo VIP te permite ejecutar los tres."],
        ["GoldMaster acierta el 39% — ¿cómo es rentable?", "Porque cada ganancia es mucho mayor que cada pérdida. Pierde más veces, pero cada victoria es lo bastante grande para impulsar el rendimiento. Es una ventaja asimétrica."],
        ["¿Hay martingala / grid?", "En absoluto. Ambos robots limitan claramente el riesgo en cada operación, no promedian a la baja ni mantienen perdedoras."],
        ["¿Qué necesito para ejecutarlo?", "MetaTrader 5 + una cuenta con oro (XAUUSD), preferiblemente de spread bajo. Se recomienda un VPS para que el robot funcione 24/5 sin interrupciones."],
        ["¿Cómo funciona el alquiler?", "Eliges un periodo de 1 mes / 6 meses / 1 año. El robot se activa mientras el plan esté vigente y queda vinculado a tu cuenta MT5."],
        ["¿Puedo cancelar?", "Sí, cuando quieras — sin contrato. El plan sigue activo hasta el final del periodo que pagaste."],
        ["¿Necesito experiencia en trading?", "No. El robot es totalmente automático. Solo lo configuras una vez. Se recomienda probarlo primero en una cuenta demo antes de usar dinero real."],
        ["¿Se garantiza ganancia?", "No — y no creas a quien lo prometa. Los números son resultados verificados con datos históricos. Ofrecemos herramientas, no promesas."],
      ],
      notFound: "¿Otra pregunta?", telegram: "Escríbenos por Telegram",
    },
    tools: {
      eyebrow: "Gratis", title: "Calculadora de lotes — rápida, precisa.",
      body: "Elige un par + una estrategia de ejemplo y ve al instante la curva de capital, la tasa de acierto y el drawdown sobre datos históricos. Sin cuenta — una herramienta gratuita de Dralvo.",
      cta: "Abrir calculadora", note: "Próximamente — para todo trader.",
    },
    pricing: {
      eyebrow: "Precios", title: "Alquila un robot, empieza hoy.",
      intro: "Empieza gratis vía Dralvo IB o desbloquea todo el ecosistema con Dralvo VIP. Cancela cuando quieras.",
      periods: { monthly: "1 mes", sixmo: "6 meses", yearly: "1 año" },
      save: { sixmo: "ahorra 15%", yearly: "ahorra 30%" },
      perMonth: "/mes", popular: "Popular",
      cancelNote: "Cancela cuando quieras · sin contrato · soporte de instalación incluido.",
      tiers: [
        { id: "free", name: "Free", tagline: "Recibe el EA gratis vía Dralvo IB", cta: "Abrir cuenta y recibir el EA", features: ["TiGold EA gratis", "1 cuenta real MT5 vía IB", "Calculadora de lotes", "Comunidad de Telegram", "Actualizaciones básicas de EA"] },
        { id: "unlimited", name: "Dralvo VIP", tagline: "Todo el ecosistema Dralvo", cta: "Desbloquear todo Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Telegram VIP", "Actualizaciones continuas de EA", "Soporte de instalación", "1 VPS incluido", "Acceso anticipado a nuevos EA", "Soporte prioritario"] },
      ],
    },
    finalCta: {
      eyebrow: "¿Listo?", title: "Deja que el robot opere. Tú mantén la disciplina.",
      body: "Empieza gratis con el indicador, las herramientas y la comunidad. O alquila un robot y deja que trabaje 24/5 en tu cuenta.",
      primaryCta: "Ver planes de alquiler", secondaryCta: "Unirme a la comunidad de Telegram", guarantee: "Cancela cuando quieras · Sin contrato · Soporte de instalación",
    },
    footer: {
      tagline: "Dralvo Capital — robots de trading de oro automáticos. Estrategias verificadas con datos reales.",
      product: "Productos", company: "Empresa", legal: "Legal",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M15)", tools: "Calculadora de lotes", trackRecord: "Rendimiento",
      telegram: "Telegram", login: "Entrar", privacy: "Privacidad", terms: "Términos", disclaimer: "Aviso legal",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  id: {
    nav: { products: "Produk", evidence: "Performa", pricing: "Harga", tools: "Alat", login: "Masuk", cta: "Coba" },
    hero: {
      eyebrow: "Dralvo Capital · Robot trading emas otomatis",
      titleA: "Dua mesin. Satu logam. ", titleEm: "Hasil nyata.",
      subtitle: "Dua robot emas XAUUSD, dua gaya — swing yang sabar dan scalp yang cepat. Keduanya strategi yang teruji pada data nyata. Tanpa martingale, tanpa grid, tanpa rekayasa.",
      ctaPrimary: "Lihat kedua produk", ctaSecondary: "Lihat performa",
      metalNote: ".9999 — setransparan emas murni",
      equityLabel: "TiGold — langsung di MT5", equityRisk: "Akun nyata · tanpa edit",
    },
    products: {
      eyebrow: "Dua produk — dijual paralel", title: "Pilih gaya Anda.",
      intro: "Disiplin risiko yang sama, irama berbeda. Keduanya teruji pada data pasar nyata.",
      styleName: { swing: "Sabar — gelombang besar", scalp: "Cepat — momentum", free: "Adaptif — proteksi modal" },
      directionLabels: { long: "Searah tren", both: "Dua arah" },
      headlineLabels: ["Imbal hasil (konfig disarankan)", "Profit Factor", "Win rate", "Drawdown maks"],
      recommendedRiskLabel: "Konfig",
      verified: { goldmaster: "Teruji pada 8 tahun data emas nyata", scalp: "Teruji pada data tick 100% nyata", tigold: "Gratis — buka akun Dralvo IB" },
      pitch: {
        goldmaster: "Robot emas untuk yang sabar — mengikuti gelombang besar emas dan mengutamakan kualitas daripada kuantitas. Menang secara selektif, tetapi setiap kemenangan cukup besar untuk mendorong kinerja.",
        scalp: "Robot emas untuk yang bertempo cepat — menangkap lonjakan kuat intraday dan keluar dengan rapi. Win rate tinggi, hampir tanpa eksposur menginap.",
        tigold: "EA adaptif untuk XAUUSD — gratis seumur hidup saat membuka akun melalui mitra IB Dralvo. Proteksi modal 3 lapis: jeda saat rentetan kalah, stop harian, dan filter berita.",
      },
      bullets: {
        goldmaster: ["Teruji selama 8 tahun — melewati setiap siklus naik/turun emas", "Memanfaatkan data posisi institusional untuk membaca aliran dana besar", "Disiplin risiko mutlak: setiap transaksi terlindungi, tidak pernah dibiarkan rugi"],
        scalp: ["Teruji pada data tick 100% nyata · OOS positif di ketiga level risiko", "TANPA grid · TANPA martingale · TANPA averaging", "Masuk dan keluar tegas, eksposur menginap minimal"],
        tigold: ["Gratis seumur hidup — cukup buka akun via tautan IB Dralvo", "Berjalan di XAUUSD · Trailing stop pintar", "Proteksi modal 3 lapis: rentetan kalah → jeda, rugi harian → stop, berita → hindari"],
      },
      badgePopular: "Populer",
      badgePro: "Profesional",
      cta: "Dapatkan", viewReport: "Lihat laporan lengkap",
      evidenceEyebrow: "Performa terverifikasi", evidenceTitle: "Angka yang berbicara.",
      matrix: { title: "Profil risiko", risk: "Konfig", ret: "Imbal hasil", dd: "DD maks", pf: "PF", cagr: "Per tahun", trades: "Transaksi" },
      statLabels: { trades: "Total transaksi", winRate: "Win rate", avgWin: "Profit rata2", avgLoss: "Rugi rata2", rr: "Untung/Rugi", avgHold: "Durasi rata2", streak: "Beruntun M/K" },
      monthlyTitle: "Keuntungan bulanan",
    },
    trust: {
      eyebrow: "Mengapa bisa dipercaya", title: "Beda dari 99% robot emas.",
      items: [
        { title: "Tanpa martingale / grid", body: "Setiap transaksi punya batas risiko jelas. Tanpa averaging, tanpa menahan posisi rugi — kurva ekuitas bukan bom waktu." },
        { title: "Teruji pada data nyata", body: "GoldMaster selama 8 tahun emas, Scalp pada tick 100% nyata. Kinerja dipublikasikan — tanpa jendela pilihan." },
        { title: "Data institusional", body: "Memanfaatkan data posisi institusional untuk membaca perilaku smart-money, bukan sekadar menggambar grafik." },
        { title: "Transparan", body: "Imbal hasil, win rate, dan drawdown semuanya publik. Kami menyajikan angka seperti laporan uji." },
      ],
    },
    faq: {
      eyebrow: "Tanya jawab", title: "Semua yang perlu Anda tahu.",
      items: [
        ["Apa beda robotnya?", "GoldMaster adalah swing D1 — sabar, sedikit transaksi, mengikuti gelombang besar. GoldScalp adalah M15 — masuk cepat, tutup di hari yang sama. TiGold adalah mesin adaptif (gratis via Dralvo IB). Paket Dralvo VIP memungkinkan Anda menjalankan ketiganya."],
        ["GoldMaster menang 39% — kok bisa untung?", "Karena setiap kemenangan jauh lebih besar daripada setiap kerugian. Lebih sering kalah, tetapi setiap menang cukup besar untuk mendorong kinerja. Ini keunggulan asimetris."],
        ["Ada martingale / grid?", "Sama sekali tidak. Kedua robot membatasi risiko dengan jelas pada setiap transaksi, tidak averaging, tidak menahan posisi rugi."],
        ["Apa yang saya butuhkan untuk menjalankannya?", "MetaTrader 5 + akun dengan emas (XAUUSD), sebaiknya spread rendah. VPS disarankan agar robot berjalan 24/5 tanpa terputus."],
        ["Bagaimana sewa bekerja?", "Anda memilih periode 1 bulan / 6 bulan / 1 tahun. Robot aktif selama paket berlaku dan terikat pada akun MT5 Anda."],
        ["Bisakah saya batalkan?", "Bisa, kapan saja — tanpa kontrak. Paket tetap berjalan sampai akhir periode yang sudah Anda bayar."],
        ["Apakah saya butuh pengalaman trading?", "Tidak. Robot sepenuhnya otomatis. Anda hanya perlu mengaturnya sekali. Disarankan mencoba di akun demo dulu sebelum uang nyata."],
        ["Apakah profit dijamin?", "Tidak — dan jangan percaya siapa pun yang menjanjikannya. Angka adalah hasil teruji pada data historis. Kami menyediakan alat, bukan menjual janji."],
      ],
      notFound: "Ada pertanyaan lain?", telegram: "Hubungi kami di Telegram",
    },
    tools: {
      eyebrow: "Gratis", title: "Kalkulator lot — cepat, akurat.",
      body: "Pilih pasangan + strategi contoh, lihat langsung kurva ekuitas, win rate, dan drawdown pada data historis. Tanpa akun — alat gratis dari Dralvo.",
      cta: "Buka kalkulator lot", note: "Segera hadir — untuk semua trader.",
    },
    pricing: {
      eyebrow: "Harga", title: "Sewa robot, mulai hari ini.",
      intro: "Mulai gratis via Dralvo IB, atau buka seluruh ekosistem dengan Dralvo VIP. Batalkan kapan saja.",
      periods: { monthly: "1 bulan", sixmo: "6 bulan", yearly: "1 tahun" },
      save: { sixmo: "hemat 15%", yearly: "hemat 30%" },
      perMonth: "/bln", popular: "Populer",
      cancelNote: "Batalkan kapan saja · tanpa kontrak · termasuk bantuan instalasi.",
      tiers: [
        { id: "free", name: "Free", tagline: "Dapatkan EA gratis via Dralvo IB", cta: "Buka akun, dapatkan EA", features: ["TiGold EA gratis", "1 akun live MT5 via IB", "Kalkulator lot", "Komunitas Telegram", "Pembaruan EA dasar"] },
        { id: "unlimited", name: "Dralvo VIP", tagline: "Seluruh ekosistem Dralvo", cta: "Buka semua Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Telegram VIP", "Pembaruan EA berkelanjutan", "Bantuan instalasi", "1 VPS termasuk", "Akses awal EA baru", "Dukungan prioritas"] },
      ],
    },
    finalCta: {
      eyebrow: "Siap?", title: "Biarkan robot trading. Anda jaga disiplin.",
      body: "Mulai gratis dengan indikator, alat, dan komunitas. Atau sewa robot dan biarkan bekerja 24/5 di akun Anda.",
      primaryCta: "Lihat paket sewa", secondaryCta: "Gabung komunitas Telegram", guarantee: "Batalkan kapan saja · Tanpa kontrak · Bantuan instalasi",
    },
    footer: {
      tagline: "Dralvo Capital — robot trading emas otomatis. Strategi teruji pada data nyata.",
      product: "Produk", company: "Perusahaan", legal: "Legal",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M15)", tools: "Kalkulator lot", trackRecord: "Performa",
      telegram: "Telegram", login: "Masuk", privacy: "Privasi", terms: "Ketentuan", disclaimer: "Penafian",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  "pt-BR": {
    nav: { products: "Produtos", evidence: "Desempenho", pricing: "Preços", tools: "Ferramentas", login: "Entrar", cta: "Testar" },
    hero: {
      eyebrow: "Dralvo Capital · Robôs de trading de ouro automáticos",
      titleA: "Duas máquinas. Um metal. ", titleEm: "Resultados reais.",
      subtitle: "Dois robôs de ouro XAUUSD, dois estilos — swing paciente e scalp veloz. Ambos são estratégias verificadas em dados reais. Sem martingale, sem grid, sem maquiagem.",
      ctaPrimary: "Ver os dois produtos", ctaSecondary: "Ver desempenho",
      metalNote: ".9999 — transparente como ouro puro",
      equityLabel: "TiGold — ao vivo no MT5", equityRisk: "Conta real · sem edição",
    },
    products: {
      eyebrow: "Dois produtos — em paralelo", title: "Escolha seu estilo.",
      intro: "Mesma disciplina de risco, ritmo diferente. Ambos verificados em dados reais de mercado.",
      styleName: { swing: "Paciente — a grande onda", scalp: "Rápido — o golpe de momentum", free: "Adaptativo — proteção de capital" },
      directionLabels: { long: "A favor da tendência", both: "Ambas as direções" },
      headlineLabels: ["Retorno (config. recom.)", "Profit Factor", "Taxa de acerto", "Drawdown máx."],
      recommendedRiskLabel: "Config.",
      verified: { goldmaster: "Verificado em 8 anos de dados reais de ouro", scalp: "Verificado em dados de ticks 100% reais", tigold: "Grátis — abra uma conta Dralvo IB" },
      pitch: {
        goldmaster: "Um robô de ouro para os pacientes — cavalga as grandes ondas do ouro e prioriza qualidade sobre quantidade. Ganha de forma seletiva, mas cada ganho é grande o bastante para impulsionar o desempenho.",
        scalp: "Um robô de ouro para o ritmo rápido — captura fortes impulsos intradiários e sai de forma limpa. Alta taxa de acerto, quase sem exposição overnight.",
        tigold: "Um EA adaptativo para XAUUSD — grátis para sempre ao abrir uma conta por um parceiro IB da Dralvo. Proteção de capital em 3 camadas: pausa por sequência de perdas, stop diário e filtro de notícias.",
      },
      bullets: {
        goldmaster: ["Verificado ao longo de 8 anos — por cada ciclo de alta e baixa do ouro", "Aproveita dados de posicionamento institucional para ler o fluxo do dinheiro grande", "Disciplina de risco absoluta: cada operação é protegida, nunca mantida no prejuízo"],
        scalp: ["Verificado em ticks 100% reais · positivo fora da amostra nos 3 níveis", "SEM grid · SEM martingale · SEM preço médio", "Entradas e saídas decididas, exposição overnight mínima"],
        tigold: ["Grátis para sempre — basta abrir uma conta pelo link IB da Dralvo", "Roda em XAUUSD · Trailing stop inteligente", "Proteção de capital em 3 camadas: sequência de perdas → pausa, perda diária → stop, notícias → evitar"],
      },
      badgePopular: "Popular",
      badgePro: "Profissional",
      cta: "Obter", viewReport: "Ver relatório completo",
      evidenceEyebrow: "Desempenho verificado", evidenceTitle: "Os números falam.",
      matrix: { title: "Perfil de risco", risk: "Config.", ret: "Retorno", dd: "DD máx.", pf: "PF", cagr: "Ao ano", trades: "Ops." },
      statLabels: { trades: "Operações", winRate: "Taxa de acerto", avgWin: "Ganho médio", avgLoss: "Perda média", rr: "Ganho/Perda", avgHold: "Duração média", streak: "Sequência G/P" },
      monthlyTitle: "Ganhos mensais",
    },
    trust: {
      eyebrow: "Por que confiar", title: "Diferente de 99% dos robôs de ouro.",
      items: [
        { title: "Sem martingale / grid", body: "Cada operação tem um limite de risco claro. Sem preço médio, sem segurar perdedoras — a curva de capital não é uma bomba-relógio." },
        { title: "Verificado em dados reais", body: "GoldMaster ao longo de 8 anos de ouro, Scalp em ticks 100% reais. O desempenho é público — sem janelas selecionadas." },
        { title: "Dados institucionais", body: "Aproveita dados de posicionamento institucional para ler o comportamento do smart-money, não apenas desenhar gráficos." },
        { title: "Transparente", body: "Retorno, taxa de acerto e drawdown são todos públicos. Apresentamos os números como um laudo de ensaio." },
      ],
    },
    faq: {
      eyebrow: "Perguntas frequentes", title: "Tudo o que você precisa saber.",
      items: [
        ["Como os robôs se diferenciam?", "GoldMaster é um swing D1 — paciente, poucas operações, surfa as grandes ondas. GoldScalp é M15 — entradas rápidas, fecha no dia. TiGold é um motor adaptativo (grátis via Dralvo IB). O plano Dralvo VIP permite rodar os três."],
        ["GoldMaster acerta 39% — como é lucrativo?", "Porque cada ganho é muito maior que cada perda. Perde mais vezes, mas cada vitória é grande o bastante para impulsionar o desempenho. É uma vantagem assimétrica."],
        ["Tem martingale / grid?", "De jeito nenhum. Os dois robôs limitam claramente o risco em cada operação, não fazem preço médio nem seguram perdedoras."],
        ["O que preciso para rodar?", "MetaTrader 5 + uma conta com ouro (XAUUSD), de preferência com spread baixo. Recomenda-se um VPS para o robô rodar 24/5 sem interrupção."],
        ["Como funciona o aluguel?", "Você escolhe um período de 1 mês / 6 meses / 1 ano. O robô fica ativo enquanto o plano estiver vigente e vinculado à sua conta MT5."],
        ["Posso cancelar?", "Sim, quando quiser — sem contrato. O plano continua ativo até o fim do período que você pagou."],
        ["Preciso de experiência em trading?", "Não. O robô é totalmente automático. Você só configura uma vez. Recomenda-se testar em conta demo antes de usar dinheiro real."],
        ["O lucro é garantido?", "Não — e não confie em quem promete isso. Os números são resultados verificados em dados históricos. Oferecemos ferramentas, não vendemos promessas."],
      ],
      notFound: "Outra pergunta?", telegram: "Fale conosco no Telegram",
    },
    tools: {
      eyebrow: "Grátis", title: "Calculadora de lote — rápida, precisa.",
      body: "Escolha um par + uma estratégia de exemplo e veja na hora a curva de capital, a taxa de acerto e o drawdown em dados históricos. Sem conta — uma ferramenta gratuita da Dralvo.",
      cta: "Abrir calculadora", note: "Em breve — para todo trader.",
    },
    pricing: {
      eyebrow: "Preços", title: "Alugue um robô, comece hoje.",
      intro: "Comece grátis via Dralvo IB ou desbloqueie todo o ecossistema com o Dralvo VIP. Cancele quando quiser.",
      periods: { monthly: "1 mês", sixmo: "6 meses", yearly: "1 ano" },
      save: { sixmo: "economize 15%", yearly: "economize 30%" },
      perMonth: "/mês", popular: "Popular",
      cancelNote: "Cancele quando quiser · sem contrato · suporte de instalação incluído.",
      tiers: [
        { id: "free", name: "Free", tagline: "Receba o EA grátis via Dralvo IB", cta: "Abrir conta e receber o EA", features: ["TiGold EA grátis", "1 conta real MT5 via IB", "Calculadora de lote", "Comunidade no Telegram", "Atualizações básicas de EA"] },
        { id: "unlimited", name: "Dralvo VIP", tagline: "Todo o ecossistema Dralvo", cta: "Desbloquear todo o Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Telegram VIP", "Atualizações contínuas de EA", "Suporte de instalação", "1 VPS incluído", "Acesso antecipado a novos EAs", "Suporte prioritário"] },
      ],
    },
    finalCta: {
      eyebrow: "Pronto?", title: "Deixe o robô operar. Você mantém a disciplina.",
      body: "Comece grátis com o indicador, as ferramentas e a comunidade. Ou alugue um robô e deixe-o trabalhar 24/5 na sua conta.",
      primaryCta: "Ver planos de aluguel", secondaryCta: "Entrar na comunidade do Telegram", guarantee: "Cancele quando quiser · Sem contrato · Suporte de instalação",
    },
    footer: {
      tagline: "Dralvo Capital — robôs de trading de ouro automáticos. Estratégias verificadas em dados reais.",
      product: "Produtos", company: "Empresa", legal: "Jurídico",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M15)", tools: "Calculadora de lote", trackRecord: "Desempenho",
      telegram: "Telegram", login: "Entrar", privacy: "Privacidade", terms: "Termos", disclaimer: "Aviso legal",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
});
