/**
 * Landing page copy (2-EA showcase). Prose/labels only — numeric EA figures come
 * from `EA_PRODUCTS` in `@/lib/backtest-stats`. vi + en authored; other locales
 * fall back to English via withLocaleFallback.
 *
 * Voice (see docs/DESIGN.md §9): confident, factual, professional. Never expose
 * the EA's internal logic (indicators, filters, SL/TP mechanics).
 */
import { withLocaleFallback } from "@/lib/i18n";

export const LANDING_COPY = withLocaleFallback({
  vi: {
    nav: { products: "Sản phẩm", evidence: "Hiệu suất", pricing: "Bảng giá", tools: "Công cụ", tigold: "TiGold", login: "Đăng nhập", cta: "Dùng thử" },
    hero: {
      eyebrow: "Dralvo Capital · Robot giao dịch vàng tự động",
      titleA: "Hai cỗ máy. Một kim loại. ",
      titleEm: "Kết quả thật.",
      subtitle:
        "Hai robot vàng XAUUSD, hai phong cách — swing kiên nhẫn và scalp tốc độ. Cả hai đều là chiến lược đã được kiểm chứng trên dữ liệu thật. Không Martingale, không Grid, không tô vẽ.",
      ctaPrimary: "Xem 2 sản phẩm",
      ctaSecondary: "Xem hiệu suất",
      metalNote: ".9999 — minh bạch như vàng nguyên chất",
      equityLabel: "Đường cong vốn — GoldMaster",
      equityRisk: "Risk 5% · 10 năm · minh hoạ",
    },
    products: {
      eyebrow: "Hai sản phẩm — bán song song",
      title: "Chọn khẩu vị của bạn.",
      intro:
        "Cùng triết lý kỷ luật rủi ro, khác nhịp giao dịch. Cả hai đều được kiểm chứng trên dữ liệu thị trường thật.",
      styleTag: { swing: "D1 SWING", scalp: "M5 SCALP", free: "FREE" },
      styleName: { swing: "Kiên nhẫn — sóng lớn", scalp: "Tốc độ — xung lực", free: "Thích ứng — bảo vệ vốn" },
      directionLabels: { long: "Thuận xu hướng tăng", both: "Hai chiều" },
      headlineLabels: ["Lợi nhuận (cấu hình khuyến nghị)", "Profit Factor", "Tỷ lệ thắng", "Sụt giảm tối đa"],
      recommendedRiskLabel: "Cấu hình",
      verified: {
        goldmaster: "Kiểm chứng trên 10 năm dữ liệu vàng thật",
        scalp: "Kiểm chứng trên dữ liệu tick thật 100%",
        tigold: "Miễn phí — mở tài khoản IB Dralvo",
      },
      pitch: {
        goldmaster:
          "Robot vàng cho người kiên nhẫn — bám theo những con sóng lớn của vàng, ưu tiên chất lượng hơn số lượng. Thắng chọn lọc nhưng mỗi lần thắng đủ lớn để dẫn dắt hiệu suất.",
        scalp:
          "Robot vàng cho người thích nhịp nhanh — nắm bắt các đợt biến động mạnh trong ngày, vào ra gọn gàng. Tỷ lệ thắng cao, hầu như không ôm lệnh qua đêm.",
        tigold:
          "EA thích ứng cho XAUUSD — miễn phí trọn đời khi mở tài khoản qua đối tác IB của Dralvo. 3 lớp bảo vệ vốn: chặn chuỗi thua, giới hạn lỗ ngày, lọc tin tức.",
      },
      bullets: {
        goldmaster: [
          "Kiểm chứng qua 10 năm — đi qua mọi chu kỳ tăng/giảm của vàng",
          "Tận dụng dữ liệu định vị tổ chức để đọc dòng tiền lớn",
          "Kỷ luật rủi ro tuyệt đối: mỗi lệnh được bảo vệ, không gồng lỗ",
        ],
        scalp: [
          "Kiểm chứng trên dữ liệu tick thật 100% · 6/6 tháng dương",
          "KHÔNG Grid · KHÔNG Martingale · KHÔNG nhồi lệnh",
          "Vào ra dứt khoát, hạn chế tối đa rủi ro qua đêm",
        ],
        tigold: [
          "Miễn phí trọn đời — chỉ cần mở tài khoản qua link IB Dralvo",
          "Chạy XAUUSD · Trailing stop thông minh",
          "3 lớp bảo vệ vốn: chuỗi thua → tạm nghỉ, lỗ ngày → dừng, tin tức → né",
        ],
      },
      cta: "Sở hữu",
      viewReport: "Xem báo cáo đầy đủ",
      evidenceEyebrow: "Hiệu suất đã kiểm chứng",
      evidenceTitle: "Số liệu nói thay lời.",
      matrix: { title: "Hồ sơ rủi ro", risk: "Cấu hình", ret: "Lợi nhuận", dd: "Max DD", pf: "PF", cagr: "Mỗi năm", trades: "Lệnh" },
      statLabels: { trades: "Tổng lệnh", winRate: "Tỷ lệ thắng", avgWin: "Lãi TB", avgLoss: "Lỗ TB", rr: "Lãi/Lỗ", avgHold: "Giữ lệnh TB", streak: "Chuỗi T/B" },
      monthlyTitle: "Lãi theo tháng",
      badgePopular: "Phổ biến",
      badgePro: "Chuyên nghiệp",
    },
    trust: {
      eyebrow: "Vì sao tin được",
      title: "Khác 99% robot vàng trên thị trường.",
      items: [
        { title: "Không Martingale / Grid", body: "Mỗi lệnh đều được giới hạn rủi ro rõ ràng. Không nhồi lệnh, không gồng lỗ — đường vốn không phải 'bom hẹn giờ'." },
        { title: "Kiểm chứng dữ liệu thật", body: "GoldMaster qua 10 năm vàng, Scalp trên tick thật 100%. Hiệu suất công khai, không chọn lọc giai đoạn đẹp." },
        { title: "Dữ liệu tổ chức", body: "Tận dụng dữ liệu định vị của dòng tiền tổ chức — đọc hành vi smart-money, không chỉ vẽ chart." },
        { title: "Minh bạch", body: "Lợi nhuận, tỷ lệ thắng, sụt giảm vốn đều công khai. Chúng tôi trình bày số liệu như một bản kiểm định." },
      ],
    },
    tools: {
      eyebrow: "Miễn phí",
      title: "Công cụ tính lot — nhanh, chính xác.",
      body: "Tính khối lượng giao dịch theo số dư, % rủi ro, và stop loss. Hỗ trợ XAUUSD và các cặp FX chính. Không cần tài khoản — công cụ miễn phí của Dralvo.",
      cta: "Mở công cụ tính lot",
      note: "Dành cho mọi trader.",
    },
    pricing: {
      eyebrow: "Bảng giá",
      title: "Thuê robot, bắt đầu hôm nay.",
      intro: "Bắt đầu miễn phí qua Dralvo IB, hoặc mở khóa toàn bộ hệ sinh thái với gói Dralvo Unlimited. Hủy bất cứ lúc nào.",
      periods: { monthly: "1 tháng", sixmo: "6 tháng", yearly: "1 năm" },
      save: { sixmo: "tiết kiệm 15%", yearly: "tiết kiệm 30%" },
      perMonth: "/tháng",
      popular: "Phổ biến",
      cancelNote: "Hủy bất cứ lúc nào · không ràng buộc hợp đồng · hỗ trợ cài đặt.",
      tiers: [
        { id: "free", name: "Free", tagline: "Nhận EA miễn phí qua Dralvo IB", cta: "Mở tài khoản nhận EA", features: ["TiGold EA miễn phí", "1 tài khoản MT5 thật qua IB", "1 tài khoản Demo 30 ngày", "Công cụ tính lot", "Telegram Community", "Cập nhật EA cơ bản"] },
        { id: "unlimited", name: "Dralvo Unlimited", tagline: "Toàn bộ hệ sinh thái Dralvo", cta: "Mở khóa toàn bộ Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Không giới hạn tài khoản MT5", "Không giới hạn Demo", "Telegram VIP", "Cập nhật EA liên tục", "Hỗ trợ cài đặt", "Hỗ trợ 1 VPS tương ứng", "Truy cập sớm EA mới", "Ưu tiên hỗ trợ"] },
      ],
    },
    faq: {
      eyebrow: "Hỏi đáp",
      title: "Mọi điều bạn cần biết.",
      items: [
        ["Các robot khác nhau thế nào?", "GoldMaster là swing D1 — kiên nhẫn, ít lệnh, giữ theo sóng lớn. GoldScalp là M5 — vào theo nhịp nhanh, chốt trong ngày. TiGold là engine thích ứng (miễn phí qua Dralvo IB). Gói Dralvo Unlimited cho bạn chạy cả ba."],
        ["GoldMaster thắng 43% — sao vẫn lãi?", "Vì mỗi lệnh thắng lớn hơn nhiều so với mỗi lệnh thua. Thua nhiều lần hơn nhưng mỗi lần thắng đủ to để dẫn dắt hiệu suất. Đây là lợi thế bất đối xứng."],
        ["Có Martingale / Grid không?", "Tuyệt đối không. Cả 2 robot đều giới hạn rủi ro rõ ràng trên mỗi lệnh, không nhồi lệnh, không gồng lỗ."],
        ["Tôi cần gì để chạy?", "MetaTrader 5 + tài khoản có vàng (XAUUSD), khuyến nghị tài khoản spread thấp. Nên dùng VPS để robot chạy 24/5 không gián đoạn."],
        ["Thuê hoạt động thế nào?", "Bạn chọn chu kỳ 1 tháng / 6 tháng / 1 năm. Robot kích hoạt theo gói còn hiệu lực và gắn với tài khoản MT5 của bạn."],
        ["Tôi hủy được không?", "Được, bất cứ lúc nào — không ràng buộc hợp đồng. Gói vẫn chạy hết chu kỳ bạn đã thanh toán."],
        ["Tôi cần kinh nghiệm trading không?", "Không. Robot tự động hoàn toàn. Bạn chỉ cần cài đặt một lần. Khuyến nghị chạy thử trên tài khoản demo trước khi vào tiền thật."],
        ["Có cam kết lợi nhuận không?", "Không — và đừng tin ai cam kết điều đó. Số liệu là kết quả kiểm chứng trên dữ liệu quá khứ. Chúng tôi cung cấp công cụ, không bán lời hứa."],
      ],
      notFound: "Còn câu hỏi khác?",
      telegram: "Nhắn Telegram",
    },
    finalCta: {
      eyebrow: "Sẵn sàng?",
      title: "Để robot giao dịch. Bạn giữ kỷ luật.",
      body: "Bắt đầu miễn phí với indicator, công cụ và cộng đồng. Hoặc thuê robot và để nó làm việc 24/5 trên tài khoản của bạn.",
      primaryCta: "Xem gói thuê",
      secondaryCta: "Vào cộng đồng Telegram",
      guarantee: "Hủy bất cứ lúc nào · Không ràng buộc · Hỗ trợ cài đặt",
    },
    footer: {
      tagline: "Dralvo Capital — robot giao dịch vàng tự động. Chiến lược kiểm chứng trên dữ liệu thật.",
      product: "Sản phẩm",
      company: "Công ty",
      legal: "Pháp lý",
      goldmaster: "GoldMaster (D1)",
      scalp: "GoldScalp (M5)",
      tigold: "TiGold (miễn phí)",
      tools: "Công cụ tính lot",
      trackRecord: "Hiệu suất",
      compare: "Dralvo vs EA grid/martingale",
      telegram: "Telegram",
      login: "Đăng nhập",
      privacy: "Bảo mật",
      terms: "Điều khoản",
      disclaimer: "Miễn trừ trách nhiệm",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  en: {
    nav: { products: "Products", evidence: "Performance", pricing: "Pricing", tools: "Tools", tigold: "TiGold", login: "Log in", cta: "Try it" },
    hero: {
      eyebrow: "Dralvo Capital · Automated gold trading robots",
      titleA: "Two machines. One metal. ",
      titleEm: "Real results.",
      subtitle:
        "Two XAUUSD gold robots, two styles — patient swing and fast scalp. Both are strategies verified on real market data. No martingale, no grid, no window dressing.",
      ctaPrimary: "See both products",
      ctaSecondary: "See performance",
      metalNote: ".9999 — as transparent as pure gold",
      equityLabel: "Equity curve — GoldMaster",
      equityRisk: "Risk 5% · 10y · illustrative",
    },
    products: {
      eyebrow: "Two products — sold in parallel",
      title: "Pick your temper.",
      intro: "Same risk discipline, different cadence. Both verified on real market data.",
      styleTag: { swing: "D1 SWING", scalp: "M5 SCALP", free: "FREE" },
      styleName: { swing: "Patient — the long wave", scalp: "Fast — the momentum strike", free: "Adaptive — capital protection" },
      directionLabels: { long: "Trend-following", both: "Both directions" },
      headlineLabels: ["Return (recommended config)", "Profit Factor", "Win rate", "Max drawdown"],
      recommendedRiskLabel: "Config",
      verified: {
        goldmaster: "Verified on 10 years of real gold data",
        scalp: "Verified on 100% real tick data",
        tigold: "Free — open a Dralvo IB account",
      },
      pitch: {
        goldmaster:
          "A gold robot for the patient — it rides gold's major waves and favors quality over quantity. It wins selectively, but each win is big enough to drive performance.",
        scalp:
          "A gold robot for the fast-paced — it captures strong intraday bursts and exits cleanly. High win rate, almost no overnight exposure.",
        tigold:
          "An adaptive EA for XAUUSD — free for life when you open an account through a Dralvo IB partner. 3-layer capital protection: loss-streak pause, daily stop, and news filter.",
      },
      bullets: {
        goldmaster: [
          "Verified across 10 years — through every gold bull and bear cycle",
          "Leverages institutional positioning data to read big-money flow",
          "Absolute risk discipline: every trade is protected, never held in loss",
        ],
        scalp: [
          "Verified on 100% real tick data · 6/6 months positive",
          "NO grid · NO martingale · NO averaging down",
          "Decisive entries and exits, minimal overnight exposure",
        ],
        tigold: [
          "Free for life — just open an account via the Dralvo IB link",
          "Runs on XAUUSD · Smart trailing stop",
          "3-layer capital protection: loss streak → pause, daily loss → stop, news → avoid",
        ],
      },
      cta: "Get",
      viewReport: "View full report",
      evidenceEyebrow: "Verified performance",
      evidenceTitle: "The numbers speak.",
      matrix: { title: "Risk profile", risk: "Config", ret: "Return", dd: "Max DD", pf: "PF", cagr: "Per year", trades: "Trades" },
      statLabels: { trades: "Total trades", winRate: "Win rate", avgWin: "Avg win", avgLoss: "Avg loss", rr: "Win/Loss", avgHold: "Avg hold", streak: "Streak W/L" },
      monthlyTitle: "Monthly gains",
      badgePopular: "Popular",
      badgePro: "Professional",
    },
    trust: {
      eyebrow: "Why you can trust it",
      title: "Unlike 99% of gold robots.",
      items: [
        { title: "No martingale / grid", body: "Every trade has a clear risk cap. No averaging down, no holding losers — the equity curve isn't a time bomb." },
        { title: "Verified on real data", body: "GoldMaster across 10 years of gold, Scalp on 100% real ticks. Performance is public — no cherry-picked windows." },
        { title: "Institutional data", body: "Leverages institutional positioning data to read smart-money behavior, not just chart drawing." },
        { title: "Transparent", body: "Return, win rate and drawdown are all public. We present the numbers like an assay report." },
      ],
    },
    tools: {
      eyebrow: "Free",
      title: "Lot size calculator — fast, accurate.",
      body: "Calculate position size from balance, risk %, and stop loss. Supports XAUUSD and major FX pairs. No account needed — a free Dralvo tool.",
      cta: "Open lot calculator",
      note: "For every trader.",
    },
    pricing: {
      eyebrow: "Pricing",
      title: "Rent a robot, start today.",
      intro: "Start free through Dralvo IB, or unlock the entire ecosystem with Dralvo Unlimited. Cancel anytime.",
      periods: { monthly: "1 month", sixmo: "6 months", yearly: "1 year" },
      save: { sixmo: "save 15%", yearly: "save 30%" },
      perMonth: "/mo",
      popular: "Popular",
      cancelNote: "Cancel anytime · no contract · install support included.",
      tiers: [
        { id: "free", name: "Free", tagline: "Get the EA free via Dralvo IB", cta: "Open account, get the EA", features: ["TiGold EA free", "1 real MT5 account via IB", "1 demo account for 30 days", "Lot calculator", "Telegram community", "Basic EA updates"] },
        { id: "unlimited", name: "Dralvo Unlimited", tagline: "The entire Dralvo ecosystem", cta: "Unlock all of Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Unlimited MT5 accounts", "Unlimited demo accounts", "Telegram VIP", "Continuous EA updates", "Install support", "1 VPS included", "Early access to new EAs", "Priority support"] },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Everything you need to know.",
      items: [
        ["How do the robots differ?", "GoldMaster is a D1 swing — patient, few trades, riding the big waves. GoldScalp is M5 — fast intraday entries, exits within the day. TiGold is a free adaptive engine (via Dralvo IB). Dralvo Unlimited lets you run all three."],
        ["GoldMaster wins 43% — how is it profitable?", "Because each win is far bigger than each loss. You lose more often but win big enough to drive performance. It's an asymmetric edge."],
        ["Any martingale / grid?", "Absolutely none. Both robots cap risk clearly per trade, no averaging down, no holding losers."],
        ["What do I need to run it?", "MetaTrader 5 + an account with gold (XAUUSD), preferably low-spread. A VPS is recommended for uninterrupted 24/5 operation."],
        ["How does renting work?", "You pick a 1-month / 6-month / 1-year cycle. The robot activates for your active plan and is bound to your MT5 account."],
        ["Can I cancel?", "Yes, anytime — no contract. Your plan runs to the end of the cycle you've paid for."],
        ["Do I need trading experience?", "No. The robot is fully automated. You install it once. We recommend a demo run before going live."],
        ["Is profit guaranteed?", "No — and don't trust anyone who promises it. The figures are verified on past data. We provide a tool, not a promise."],
      ],
      notFound: "Another question?",
      telegram: "Message us on Telegram",
    },
    finalCta: {
      eyebrow: "Ready?",
      title: "Let the robot trade. You keep the discipline.",
      body: "Start free with the indicator, tools and community. Or rent a robot and let it work 24/5 on your account.",
      primaryCta: "See rental plans",
      secondaryCta: "Join the Telegram community",
      guarantee: "Cancel anytime · No contract · Install support",
    },
    footer: {
      tagline: "Dralvo Capital — automated gold trading robots. Strategies verified on real data.",
      product: "Products",
      company: "Company",
      legal: "Legal",
      goldmaster: "GoldMaster (D1)",
      scalp: "GoldScalp (M5)",
      tigold: "TiGold (free)",
      tools: "Lot calculator",
      trackRecord: "Performance",
      compare: "Dralvo vs grid/martingale EAs",
      telegram: "Telegram",
      login: "Log in",
      privacy: "Privacy",
      terms: "Terms",
      disclaimer: "Disclaimer",
      copyright: "© 2026 Dralvo Capital.",
    },
  },

  // Partial translations — any key omitted deep-merges to English (withLocaleFallback).
  zh: {
    nav: { products: "产品", evidence: "业绩", pricing: "价格", tools: "工具", login: "登录", cta: "试用" },
    hero: {
      eyebrow: "Dralvo Capital · 自动黄金交易机器人",
      titleA: "两台机器。一种金属。",
      titleEm: "真实结果。",
      subtitle: "两款 XAUUSD 黄金机器人，两种风格——耐心的波段与快速的剥头皮。均为在真实数据上验证过的策略。无马丁、无网格、不修饰。",
      ctaPrimary: "查看两款产品", ctaSecondary: "查看业绩",
      metalNote: ".9999 — 像纯金一样透明",
      equityLabel: "资金曲线 — GoldMaster", equityRisk: "风险 5% · 10 年 · 示意图",
    },
    products: {
      eyebrow: "两款产品 — 并行销售", title: "选择你的风格。",
      intro: "相同的风险纪律，不同的交易节奏。两者均在真实市场数据上验证。",
      styleName: { swing: "耐心 — 大浪", scalp: "快速 — 动量", free: "自适应 — 保护本金" },
      directionLabels: { long: "顺势做多", both: "双向" },
      headlineLabels: ["收益（推荐配置）", "盈利因子", "胜率", "最大回撤"],
      recommendedRiskLabel: "配置",
      verified: { goldmaster: "在 10 年真实黄金数据上验证", scalp: "在 100% 真实 tick 数据上验证", tigold: "免费 — 开设 Dralvo IB 账户" },
      pitch: {
        goldmaster: "为耐心者打造的黄金机器人——顺着黄金的大浪而行，重质不重量。它精挑细选地获胜，但每次盈利都足够大，能驱动整体业绩。",
        scalp: "为快节奏者打造的黄金机器人——捕捉盘中的强劲爆发，干净利落地进出。高胜率，几乎不持仓过夜。",
        tigold: "面向 XAUUSD 的自适应 EA——通过 Dralvo IB 合作伙伴开户即终身免费。3 层本金保护：连亏暂停、单日止损、新闻过滤。",
      },
      bullets: {
        goldmaster: ["历经 10 年验证——穿越黄金的每一轮牛熊周期", "利用机构持仓数据解读大资金流向", "绝对的风险纪律：每笔交易都有保护，绝不扛单"],
        scalp: ["在 100% 真实 tick 数据上验证 · 6/6 个月盈利", "无网格 · 无马丁 · 不加仓摊平", "进出果断，最大限度减少过夜风险"],
        tigold: ["终身免费——只需通过 Dralvo IB 链接开户", "运行于 XAUUSD · 智能移动止损", "3 层本金保护：连亏 → 暂停，单日亏损 → 止损，新闻 → 规避"],
      },
      badgePopular: "热门",
      badgePro: "专业",
      cta: "获取", viewReport: "查看完整报告",
      evidenceEyebrow: "已验证业绩", evidenceTitle: "数字会说话。",
      matrix: { title: "风险概况", risk: "配置", ret: "收益", dd: "最大回撤", pf: "PF", cagr: "每年", trades: "交易" },
      statLabels: { trades: "总交易", winRate: "胜率", avgWin: "平均盈利", avgLoss: "平均亏损", rr: "盈亏比", avgHold: "平均持仓", streak: "连胜/连亏" },
      monthlyTitle: "每月收益",
    },
    trust: {
      eyebrow: "为何可信", title: "不同于 99% 的黄金机器人。",
      items: [
        { title: "无马丁 / 网格", body: "每笔交易都有清晰的风险上限。不加仓摊平，不扛亏损单——资金曲线不是定时炸弹。" },
        { title: "真实数据验证", body: "GoldMaster 历经 10 年黄金行情，Scalp 在 100% 真实 tick 上验证。业绩公开——没有精选时间段。" },
        { title: "机构数据", body: "利用机构持仓数据解读聪明钱的行为，而不只是画图表。" },
        { title: "透明", body: "收益、胜率与回撤全部公开。我们像出具化验报告一样呈现数字。" },
      ],
    },
    faq: {
      eyebrow: "常见问题", title: "你需要知道的一切。",
      items: [
        ["这些机器人有何不同？", "GoldMaster 是 D1 波段——耐心、交易少、跟随大浪。GoldScalp 是 M5——快速进场，当日了结。TiGold 是自适应引擎（通过 Dralvo IB 免费）。Dralvo Unlimited 套餐让你同时运行这三者。"],
        ["GoldMaster 胜率 43%——为何还能盈利？", "因为每次盈利远大于每次亏损。亏的次数更多，但每次盈利都足够大，能驱动整体业绩。这是不对称的优势。"],
        ["有马丁 / 网格吗？", "绝对没有。两款机器人对每笔交易都有清晰的风险上限，不加仓摊平，不扛亏损单。"],
        ["运行需要什么？", "MetaTrader 5 + 含黄金（XAUUSD）的账户，建议低点差账户。建议使用 VPS 让机器人 24/5 不间断运行。"],
        ["租用如何运作？", "你选择 1 个月 / 6 个月 / 1 年的周期。机器人在套餐有效期内激活，并绑定到你的 MT5 账户。"],
        ["可以取消吗？", "可以，随时——无合约约束。套餐会运行到你已支付周期结束。"],
        ["需要交易经验吗？", "不需要。机器人完全自动。你只需设置一次。建议先在模拟账户上试运行，再投入真实资金。"],
        ["保证盈利吗？", "不——也别相信任何作此承诺的人。数字是在历史数据上的验证结果。我们提供工具，而不是兜售承诺。"],
      ],
      notFound: "还有其他问题？", telegram: "在 Telegram 联系我们",
    },
    tools: {
      eyebrow: "免费", title: "手数计算器 — 快速精确。",
      body: "选择货币对 + 示例策略，立即查看历史数据上的资金曲线、胜率和回撤。无需账户——Dralvo 的免费工具。",
      cta: "打开计算器", note: "即将推出 — 面向所有交易者。",
    },
    pricing: {
      eyebrow: "价格", title: "租用机器人，今天开始。",
      intro: "通过 Dralvo IB 免费开始，或用 Dralvo Unlimited 解锁完整生态系统。随时取消。",
      periods: { monthly: "1 个月", sixmo: "6 个月", yearly: "1 年" },
      save: { sixmo: "省 15%", yearly: "省 30%" },
      perMonth: "/月", popular: "热门",
      cancelNote: "随时取消 · 无合约 · 含安装支持。",
      tiers: [
        { id: "free", name: "Free", tagline: "通过 Dralvo IB 免费获取 EA", cta: "开户领取 EA", features: ["TiGold EA 免费", "1 个通过 IB 的实盘 MT5 账户", "1 个 30 天模拟账户", "计算器", "Telegram 社区", "基础 EA 更新"] },
        { id: "unlimited", name: "Dralvo Unlimited", tagline: "完整的 Dralvo 生态系统", cta: "解锁全部 Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "不限 MT5 账户", "不限模拟账户", "Telegram VIP", "持续 EA 更新", "安装支持", "包含 1 台 VPS", "新 EA 抢先体验", "优先支持"] },
      ],
    },
    finalCta: {
      eyebrow: "准备好了吗？", title: "让机器人交易。你保持纪律。",
      body: "免费开始：指标、工具和社区。或租用机器人，让它在你的账户上 24/5 工作。",
      primaryCta: "查看租用方案", secondaryCta: "加入 Telegram 社区", guarantee: "随时取消 · 无合约 · 安装支持",
    },
    footer: {
      tagline: "Dralvo Capital — 自动黄金交易机器人。策略在真实数据上验证。",
      product: "产品", company: "公司", legal: "法律",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M5)", tools: "计算器", trackRecord: "业绩",
      telegram: "Telegram", login: "登录", privacy: "隐私", terms: "条款", disclaimer: "免责声明",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  es: {
    nav: { products: "Productos", evidence: "Rendimiento", pricing: "Precios", tools: "Herramientas", login: "Entrar", cta: "Probar" },
    hero: {
      eyebrow: "Dralvo Capital · Robots de trading de oro automáticos",
      titleA: "Dos máquinas. Un metal. ", titleEm: "Resultados reales.",
      subtitle: "Dos robots de oro XAUUSD, dos estilos — swing paciente y scalp veloz. Ambos son estrategias verificadas con datos reales. Sin martingala, sin grid, sin maquillaje.",
      ctaPrimary: "Ver ambos productos", ctaSecondary: "Ver rendimiento",
      metalNote: ".9999 — transparente como el oro puro",
      equityLabel: "Curva de capital — GoldMaster", equityRisk: "Riesgo 5% · 10 años · ilustrativo",
    },
    products: {
      eyebrow: "Dos productos — en paralelo", title: "Elige tu estilo.",
      intro: "Misma disciplina de riesgo, distinto ritmo. Ambos verificados con datos reales de mercado.",
      styleName: { swing: "Paciente — la gran ola", scalp: "Rápido — el golpe de momentum", free: "Adaptativo — protección del capital" },
      directionLabels: { long: "Solo a favor de tendencia", both: "Ambas direcciones" },
      headlineLabels: ["Retorno (config. recom.)", "Profit Factor", "Tasa de acierto", "Drawdown máx."],
      recommendedRiskLabel: "Config.",
      verified: { goldmaster: "Verificado en 10 años de datos reales de oro", scalp: "Verificado en datos de ticks 100% reales", tigold: "Gratis — abre una cuenta Dralvo IB" },
      pitch: {
        goldmaster: "Un robot de oro para los pacientes: cabalga las grandes olas del oro y prioriza la calidad sobre la cantidad. Gana de forma selectiva, pero cada ganancia es lo bastante grande para impulsar el rendimiento.",
        scalp: "Un robot de oro para el ritmo rápido: captura fuertes impulsos intradía y sale limpiamente. Alta tasa de acierto, casi sin exposición nocturna.",
        tigold: "Un EA adaptativo para XAUUSD: gratis de por vida al abrir una cuenta con un socio IB de Dralvo. Protección de capital en 3 capas: pausa por racha perdedora, stop diario y filtro de noticias.",
      },
      bullets: {
        goldmaster: ["Verificado a lo largo de 10 años — por cada ciclo alcista y bajista del oro", "Aprovecha datos de posicionamiento institucional para leer el flujo del dinero grande", "Disciplina de riesgo absoluta: cada operación está protegida, nunca se mantiene en pérdida"],
        scalp: ["Verificado en datos de ticks 100% reales · 6/6 meses positivos", "SIN grid · SIN martingala · SIN promediar a la baja", "Entradas y salidas decididas, mínima exposición nocturna"],
        tigold: ["Gratis de por vida — solo abre una cuenta vía el enlace IB de Dralvo", "Funciona en XAUUSD · Trailing stop inteligente", "Protección de capital en 3 capas: racha perdedora → pausa, pérdida diaria → stop, noticias → evitar"],
      },
      badgePopular: "Popular",
      badgePro: "Profesional",
      cta: "Obtener", viewReport: "Ver informe completo",
      evidenceEyebrow: "Rendimiento verificado", evidenceTitle: "Los números hablan.",
      matrix: { title: "Perfil de riesgo", risk: "Config.", ret: "Retorno", dd: "DD máx.", pf: "PF", cagr: "Anual", trades: "Ops." },
      statLabels: { trades: "Operaciones", winRate: "Tasa de acierto", avgWin: "Gan. media", avgLoss: "Pérd. media", rr: "Gan/Pérd", avgHold: "Duración media", streak: "Racha G/P" },
      monthlyTitle: "Ganancias mensuales",
    },
    trust: {
      eyebrow: "Por qué confiar", title: "Distinto al 99% de los robots de oro.",
      items: [
        { title: "Sin martingala / grid", body: "Cada operación tiene un límite de riesgo claro. Sin promediar a la baja, sin mantener perdedoras — la curva de capital no es una bomba de tiempo." },
        { title: "Verificado con datos reales", body: "GoldMaster a lo largo de 10 años de oro, Scalp en ticks 100% reales. El rendimiento es público — sin ventanas seleccionadas." },
        { title: "Datos institucionales", body: "Aprovecha datos de posicionamiento institucional para leer el comportamiento del smart-money, no solo dibujar gráficos." },
        { title: "Transparente", body: "Retorno, tasa de acierto y drawdown son todos públicos. Presentamos los números como un informe de ensayo." },
      ],
    },
    faq: {
      eyebrow: "Preguntas frecuentes", title: "Todo lo que necesitas saber.",
      items: [
        ["¿En qué se diferencian los robots?", "GoldMaster es swing D1 — paciente, pocas operaciones, sigue las grandes olas. GoldScalp es M5 — entradas rápidas, cierre en el día. TiGold es un motor adaptativo (gratis vía Dralvo IB). El plan Dralvo Unlimited te permite ejecutar los tres."],
        ["GoldMaster acierta el 43% — ¿cómo es rentable?", "Porque cada ganancia es mucho mayor que cada pérdida. Pierde más veces, pero cada victoria es lo bastante grande para impulsar el rendimiento. Es una ventaja asimétrica."],
        ["¿Hay martingala / grid?", "En absoluto. Ambos robots limitan claramente el riesgo en cada operación, no promedian a la baja ni mantienen perdedoras."],
        ["¿Qué necesito para ejecutarlo?", "MetaTrader 5 + una cuenta con oro (XAUUSD), preferiblemente de spread bajo. Se recomienda un VPS para que el robot funcione 24/5 sin interrupciones."],
        ["¿Cómo funciona el alquiler?", "Eliges un periodo de 1 mes / 6 meses / 1 año. El robot se activa mientras el plan esté vigente y queda vinculado a tu cuenta MT5."],
        ["¿Puedo cancelar?", "Sí, cuando quieras — sin contrato. El plan sigue activo hasta el final del periodo que pagaste."],
        ["¿Necesito experiencia en trading?", "No. El robot es totalmente automático. Solo lo configuras una vez. Se recomienda probarlo primero en una cuenta demo antes de usar dinero real."],
        ["¿Se garantiza ganancia?", "No — y no creas a quien lo prometa. Los números son resultados verificados con datos históricos. Ofrecemos herramientas, no promesas."],
      ],
      notFound: "¿Otra pregunta?", telegram: "Escríbenos por Telegram",
    },
    tools: {
      eyebrow: "Gratis", title: "Calculadora de lotes — rápida, precisa.",
      body: "Elige un par + una estrategia de ejemplo y ve al instante la curva de capital, la tasa de acierto y el drawdown sobre datos históricos. Sin cuenta — una herramienta gratuita de Dralvo.",
      cta: "Abrir calculadora", note: "Próximamente — para todo trader.",
    },
    pricing: {
      eyebrow: "Precios", title: "Alquila un robot, empieza hoy.",
      intro: "Empieza gratis vía Dralvo IB o desbloquea todo el ecosistema con Dralvo Unlimited. Cancela cuando quieras.",
      periods: { monthly: "1 mes", sixmo: "6 meses", yearly: "1 año" },
      save: { sixmo: "ahorra 15%", yearly: "ahorra 30%" },
      perMonth: "/mes", popular: "Popular",
      cancelNote: "Cancela cuando quieras · sin contrato · soporte de instalación incluido.",
      tiers: [
        { id: "free", name: "Free", tagline: "Recibe el EA gratis vía Dralvo IB", cta: "Abrir cuenta y recibir el EA", features: ["TiGold EA gratis", "1 cuenta real MT5 vía IB", "1 cuenta demo por 30 días", "Calculadora de lotes", "Comunidad de Telegram", "Actualizaciones básicas de EA"] },
        { id: "unlimited", name: "Dralvo Unlimited", tagline: "Todo el ecosistema Dralvo", cta: "Desbloquear todo Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Cuentas MT5 ilimitadas", "Cuentas demo ilimitadas", "Telegram VIP", "Actualizaciones continuas de EA", "Soporte de instalación", "1 VPS incluido", "Acceso anticipado a nuevos EA", "Soporte prioritario"] },
      ],
    },
    finalCta: {
      eyebrow: "¿Listo?", title: "Deja que el robot opere. Tú mantén la disciplina.",
      body: "Empieza gratis con el indicador, las herramientas y la comunidad. O alquila un robot y deja que trabaje 24/5 en tu cuenta.",
      primaryCta: "Ver planes de alquiler", secondaryCta: "Unirme a la comunidad de Telegram", guarantee: "Cancela cuando quieras · Sin contrato · Soporte de instalación",
    },
    footer: {
      tagline: "Dralvo Capital — robots de trading de oro automáticos. Estrategias verificadas con datos reales.",
      product: "Productos", company: "Empresa", legal: "Legal",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M5)", tools: "Calculadora de lotes", trackRecord: "Rendimiento",
      telegram: "Telegram", login: "Entrar", privacy: "Privacidad", terms: "Términos", disclaimer: "Aviso legal",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  hi: {
    nav: { products: "उत्पाद", evidence: "प्रदर्शन", pricing: "मूल्य", tools: "टूल", login: "लॉग इन", cta: "आज़माएँ" },
    hero: {
      eyebrow: "Dralvo Capital · स्वचालित गोल्ड ट्रेडिंग रोबोट",
      titleA: "दो मशीनें। एक धातु। ", titleEm: "असली नतीजे।",
      subtitle: "दो XAUUSD गोल्ड रोबोट, दो शैलियाँ — धैर्यवान स्विंग और तेज़ स्कैल्प। दोनों असली डेटा पर सत्यापित रणनीतियाँ हैं। कोई मार्टिंगेल नहीं, कोई ग्रिड नहीं।",
      ctaPrimary: "दोनों उत्पाद देखें", ctaSecondary: "प्रदर्शन देखें",
      metalNote: ".9999 — शुद्ध सोने जैसा पारदर्शी",
      equityLabel: "इक्विटी कर्व — GoldMaster", equityRisk: "जोखिम 5% · 10 वर्ष · उदाहरण",
    },
    products: {
      eyebrow: "दो उत्पाद — साथ-साथ", title: "अपनी शैली चुनें।",
      intro: "समान जोखिम अनुशासन, अलग गति। दोनों असली बाज़ार डेटा पर सत्यापित।",
      styleName: { swing: "धैर्यवान — बड़ी लहर", scalp: "तेज़ — मोमेंटम", free: "अनुकूली — पूँजी सुरक्षा" },
      directionLabels: { long: "ट्रेंड के साथ", both: "दोनों दिशाएँ" },
      headlineLabels: ["रिटर्न (अनुशंसित)", "प्रॉफिट फैक्टर", "जीत दर", "अधिकतम ड्रॉडाउन"],
      recommendedRiskLabel: "कॉन्फ़िग",
      verified: { goldmaster: "10 वर्षों के असली गोल्ड डेटा पर सत्यापित", scalp: "100% असली tick डेटा पर सत्यापित", tigold: "मुफ़्त — Dralvo IB खाता खोलें" },
      pitch: {
        goldmaster: "धैर्यवानों के लिए एक गोल्ड रोबोट — सोने की बड़ी लहरों पर सवार होता है और मात्रा से ज़्यादा गुणवत्ता को तरजीह देता है। यह चुन-चुनकर जीतता है, पर हर जीत इतनी बड़ी होती है कि प्रदर्शन को आगे बढ़ा सके।",
        scalp: "तेज़ रफ़्तार के लिए एक गोल्ड रोबोट — दिन के भीतर के मज़बूत उछालों को पकड़ता है और साफ़-सुथरे ढंग से निकलता है। ऊँची जीत दर, लगभग कोई ओवरनाइट एक्सपोज़र नहीं।",
        tigold: "XAUUSD के लिए एक अनुकूली EA — Dralvo IB साझेदार के ज़रिए खाता खोलने पर आजीवन मुफ़्त। 3-परत पूँजी सुरक्षा: हार की लड़ी पर रोक, दैनिक स्टॉप, और न्यूज़ फ़िल्टर।",
      },
      bullets: {
        goldmaster: ["10 वर्षों में सत्यापित — सोने के हर तेज़ी/मंदी चक्र से होकर", "बड़े पैसे के प्रवाह को पढ़ने के लिए संस्थागत पोज़िशनिंग डेटा का उपयोग", "पूर्ण जोखिम अनुशासन: हर ट्रेड सुरक्षित, कभी घाटे में नहीं रखा जाता"],
        scalp: ["100% असली tick डेटा पर सत्यापित · 6/6 महीने सकारात्मक", "कोई Grid नहीं · कोई Martingale नहीं · कोई एवरेजिंग नहीं", "निर्णायक प्रवेश और निकास, न्यूनतम ओवरनाइट एक्सपोज़र"],
        tigold: ["आजीवन मुफ़्त — बस Dralvo IB लिंक से खाता खोलें", "XAUUSD पर चलता है · स्मार्ट ट्रेलिंग स्टॉप", "3-परत पूँजी सुरक्षा: हार की लड़ी → रुकें, दैनिक हानि → स्टॉप, न्यूज़ → टालें"],
      },
      badgePopular: "लोकप्रिय",
      badgePro: "प्रोफेशनल",
      cta: "प्राप्त करें", viewReport: "पूरी रिपोर्ट देखें",
      evidenceEyebrow: "सत्यापित प्रदर्शन", evidenceTitle: "आँकड़े बोलते हैं।",
      matrix: { title: "जोखिम प्रोफ़ाइल", risk: "कॉन्फ़िग", ret: "रिटर्न", dd: "अधि. DD", pf: "PF", cagr: "प्रति वर्ष", trades: "ट्रेड" },
      statLabels: { trades: "कुल ट्रेड", winRate: "जीत दर", avgWin: "औसत लाभ", avgLoss: "औसत हानि", rr: "लाभ/हानि", avgHold: "औसत होल्ड", streak: "लगातार जीत/हार" },
      monthlyTitle: "मासिक लाभ",
    },
    trust: {
      eyebrow: "क्यों भरोसा करें", title: "99% गोल्ड रोबोट से अलग।",
      items: [
        { title: "कोई Martingale / Grid नहीं", body: "हर ट्रेड पर स्पष्ट जोखिम सीमा। कोई एवरेजिंग नहीं, घाटे वाले ट्रेड नहीं रखे जाते — इक्विटी कर्व कोई टाइम बम नहीं।" },
        { title: "असली डेटा पर सत्यापित", body: "GoldMaster 10 वर्षों के सोने पर, Scalp 100% असली tick पर। प्रदर्शन सार्वजनिक — कोई चुनिंदा अवधि नहीं।" },
        { title: "संस्थागत डेटा", body: "सिर्फ़ चार्ट बनाने के बजाय smart-money के व्यवहार को पढ़ने के लिए संस्थागत पोज़िशनिंग डेटा का उपयोग।" },
        { title: "पारदर्शी", body: "रिटर्न, जीत दर और ड्रॉडाउन सब सार्वजनिक। हम आँकड़े एक परख रिपोर्ट की तरह प्रस्तुत करते हैं।" },
      ],
    },
    faq: {
      eyebrow: "सामान्य प्रश्न", title: "वह सब जो आपको जानना चाहिए।",
      items: [
        ["रोबोट कैसे अलग हैं?", "GoldMaster एक D1 स्विंग है — धैर्यवान, कम ट्रेड, बड़ी लहरों पर सवार। GoldScalp M5 है — तेज़ प्रवेश, उसी दिन निकास। TiGold एक अनुकूली इंजन है (Dralvo IB के ज़रिए मुफ़्त)। Dralvo Unlimited प्लान आपको तीनों चलाने देता है।"],
        ["GoldMaster 43% जीतता है — फिर लाभदायक कैसे?", "क्योंकि हर जीत हर हार से कहीं बड़ी होती है। हारता ज़्यादा बार है, पर हर जीत इतनी बड़ी होती है कि प्रदर्शन को आगे बढ़ा सके। यह एक असममित बढ़त है।"],
        ["कोई Martingale / Grid?", "बिल्कुल नहीं। दोनों रोबोट हर ट्रेड पर स्पष्ट रूप से जोखिम सीमित करते हैं, एवरेज नहीं करते, घाटे वाले ट्रेड नहीं रखते।"],
        ["चलाने के लिए मुझे क्या चाहिए?", "MetaTrader 5 + सोने (XAUUSD) वाला खाता, अधिमानतः कम स्प्रेड वाला। रोबोट को 24/5 निर्बाध चलाने के लिए VPS की सलाह दी जाती है।"],
        ["किराया कैसे काम करता है?", "आप 1 माह / 6 माह / 1 वर्ष की अवधि चुनते हैं। रोबोट प्लान के सक्रिय रहने तक चालू रहता है और आपके MT5 खाते से जुड़ा रहता है।"],
        ["क्या मैं रद्द कर सकता हूँ?", "हाँ, कभी भी — कोई अनुबंध नहीं। प्लान आपकी भुगतान की गई अवधि के अंत तक चलता रहता है।"],
        ["क्या मुझे ट्रेडिंग अनुभव चाहिए?", "नहीं। रोबोट पूरी तरह स्वचालित है। आपको बस एक बार सेटअप करना है। असली पैसे से पहले डेमो खाते पर आज़माने की सलाह दी जाती है।"],
        ["क्या लाभ की गारंटी है?", "नहीं — और जो ऐसा वादा करे उस पर भरोसा न करें। आँकड़े ऐतिहासिक डेटा पर सत्यापित परिणाम हैं। हम उपकरण देते हैं, वादे नहीं बेचते।"],
      ],
      notFound: "कोई और सवाल?", telegram: "Telegram पर संपर्क करें",
    },
    tools: {
      eyebrow: "मुफ़्त", title: "लॉट साइज कैलकुलेटर — तेज़, सटीक।",
      body: "एक जोड़ी + नमूना रणनीति चुनें और ऐतिहासिक डेटा पर तुरंत इक्विटी कर्व, जीत दर और ड्रॉडाउन देखें। खाते की ज़रूरत नहीं — Dralvo का मुफ़्त टूल।",
      cta: "कैलकुलेटर खोलें", note: "जल्द आ रहा है — हर ट्रेडर के लिए।",
    },
    pricing: {
      eyebrow: "मूल्य", title: "रोबोट किराए पर लें, आज शुरू करें।",
      intro: "Dralvo IB के ज़रिए मुफ़्त शुरू करें, या Dralvo Unlimited से पूरा इकोसिस्टम अनलॉक करें। कभी भी रद्द करें।",
      periods: { monthly: "1 माह", sixmo: "6 माह", yearly: "1 वर्ष" },
      save: { sixmo: "15% बचत", yearly: "30% बचत" },
      perMonth: "/माह", popular: "लोकप्रिय",
      cancelNote: "कभी भी रद्द करें · कोई अनुबंध नहीं · इंस्टॉल सहायता शामिल।",
      tiers: [
        { id: "free", name: "Free", tagline: "Dralvo IB के ज़रिए मुफ़्त EA पाएँ", cta: "खाता खोलें, EA पाएँ", features: ["TiGold EA मुफ़्त", "IB के ज़रिए 1 लाइव MT5 खाता", "1 डेमो खाता 30 दिनों के लिए", "कैलकुलेटर", "Telegram समुदाय", "बेसिक EA अपडेट"] },
        { id: "unlimited", name: "Dralvo Unlimited", tagline: "पूरा Dralvo इकोसिस्टम", cta: "पूरा Dralvo अनलॉक करें", features: ["GoldMaster", "GoldScalp", "TiGold", "असीमित MT5 खाते", "असीमित डेमो खाते", "Telegram VIP", "निरंतर EA अपडेट", "इंस्टॉल सहायता", "1 VPS शामिल", "नए EA तक जल्दी पहुँच", "प्राथमिकता सहायता"] },
      ],
    },
    finalCta: {
      eyebrow: "तैयार?", title: "रोबोट को ट्रेड करने दें। अनुशासन आप रखें।",
      body: "इंडिकेटर, टूल और समुदाय के साथ मुफ़्त शुरू करें। या रोबोट किराए पर लें और उसे अपने खाते पर 24/5 काम करने दें।",
      primaryCta: "किराया योजनाएँ देखें", secondaryCta: "Telegram समुदाय से जुड़ें", guarantee: "कभी भी रद्द करें · कोई अनुबंध नहीं · इंस्टॉल सहायता",
    },
    footer: {
      tagline: "Dralvo Capital — स्वचालित गोल्ड ट्रेडिंग रोबोट। असली डेटा पर सत्यापित रणनीतियाँ।",
      product: "उत्पाद", company: "कंपनी", legal: "कानूनी",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M5)", tools: "कैलकुलेटर", trackRecord: "प्रदर्शन",
      telegram: "Telegram", login: "लॉग इन", privacy: "गोपनीयता", terms: "शर्तें", disclaimer: "अस्वीकरण",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  id: {
    nav: { products: "Produk", evidence: "Performa", pricing: "Harga", tools: "Alat", login: "Masuk", cta: "Coba" },
    hero: {
      eyebrow: "Dralvo Capital · Robot trading emas otomatis",
      titleA: "Dua mesin. Satu logam. ", titleEm: "Hasil nyata.",
      subtitle: "Dua robot emas XAUUSD, dua gaya — swing yang sabar dan scalp yang cepat. Keduanya strategi yang teruji pada data nyata. Tanpa martingale, tanpa grid, tanpa rekayasa.",
      ctaPrimary: "Lihat kedua produk", ctaSecondary: "Lihat performa",
      metalNote: ".9999 — setransparan emas murni",
      equityLabel: "Kurva ekuitas — GoldMaster", equityRisk: "Risiko 5% · 10 tahun · ilustrasi",
    },
    products: {
      eyebrow: "Dua produk — dijual paralel", title: "Pilih gaya Anda.",
      intro: "Disiplin risiko yang sama, irama berbeda. Keduanya teruji pada data pasar nyata.",
      styleName: { swing: "Sabar — gelombang besar", scalp: "Cepat — momentum", free: "Adaptif — proteksi modal" },
      directionLabels: { long: "Searah tren", both: "Dua arah" },
      headlineLabels: ["Imbal hasil (konfig disarankan)", "Profit Factor", "Win rate", "Drawdown maks"],
      recommendedRiskLabel: "Konfig",
      verified: { goldmaster: "Teruji pada 10 tahun data emas nyata", scalp: "Teruji pada data tick 100% nyata", tigold: "Gratis — buka akun Dralvo IB" },
      pitch: {
        goldmaster: "Robot emas untuk yang sabar — mengikuti gelombang besar emas dan mengutamakan kualitas daripada kuantitas. Menang secara selektif, tetapi setiap kemenangan cukup besar untuk mendorong kinerja.",
        scalp: "Robot emas untuk yang bertempo cepat — menangkap lonjakan kuat intraday dan keluar dengan rapi. Win rate tinggi, hampir tanpa eksposur menginap.",
        tigold: "EA adaptif untuk XAUUSD — gratis seumur hidup saat membuka akun melalui mitra IB Dralvo. Proteksi modal 3 lapis: jeda saat rentetan kalah, stop harian, dan filter berita.",
      },
      bullets: {
        goldmaster: ["Teruji selama 10 tahun — melewati setiap siklus naik/turun emas", "Memanfaatkan data posisi institusional untuk membaca aliran dana besar", "Disiplin risiko mutlak: setiap transaksi terlindungi, tidak pernah dibiarkan rugi"],
        scalp: ["Teruji pada data tick 100% nyata · 6/6 bulan positif", "TANPA grid · TANPA martingale · TANPA averaging", "Masuk dan keluar tegas, eksposur menginap minimal"],
        tigold: ["Gratis seumur hidup — cukup buka akun via tautan IB Dralvo", "Berjalan di XAUUSD · Trailing stop pintar", "Proteksi modal 3 lapis: rentetan kalah → jeda, rugi harian → stop, berita → hindari"],
      },
      badgePopular: "Populer",
      badgePro: "Profesional",
      cta: "Dapatkan", viewReport: "Lihat laporan lengkap",
      evidenceEyebrow: "Performa terverifikasi", evidenceTitle: "Angka yang berbicara.",
      matrix: { title: "Profil risiko", risk: "Konfig", ret: "Imbal hasil", dd: "DD maks", pf: "PF", cagr: "Per tahun", trades: "Transaksi" },
      statLabels: { trades: "Total transaksi", winRate: "Win rate", avgWin: "Profit rata2", avgLoss: "Rugi rata2", rr: "Untung/Rugi", avgHold: "Durasi rata2", streak: "Beruntun M/K" },
      monthlyTitle: "Keuntungan bulanan",
    },
    trust: {
      eyebrow: "Mengapa bisa dipercaya", title: "Beda dari 99% robot emas.",
      items: [
        { title: "Tanpa martingale / grid", body: "Setiap transaksi punya batas risiko jelas. Tanpa averaging, tanpa menahan posisi rugi — kurva ekuitas bukan bom waktu." },
        { title: "Teruji pada data nyata", body: "GoldMaster selama 10 tahun emas, Scalp pada tick 100% nyata. Kinerja dipublikasikan — tanpa jendela pilihan." },
        { title: "Data institusional", body: "Memanfaatkan data posisi institusional untuk membaca perilaku smart-money, bukan sekadar menggambar grafik." },
        { title: "Transparan", body: "Imbal hasil, win rate, dan drawdown semuanya publik. Kami menyajikan angka seperti laporan uji." },
      ],
    },
    faq: {
      eyebrow: "Tanya jawab", title: "Semua yang perlu Anda tahu.",
      items: [
        ["Apa beda robotnya?", "GoldMaster adalah swing D1 — sabar, sedikit transaksi, mengikuti gelombang besar. GoldScalp adalah M5 — masuk cepat, tutup di hari yang sama. TiGold adalah mesin adaptif (gratis via Dralvo IB). Paket Dralvo Unlimited memungkinkan Anda menjalankan ketiganya."],
        ["GoldMaster menang 43% — kok bisa untung?", "Karena setiap kemenangan jauh lebih besar daripada setiap kerugian. Lebih sering kalah, tetapi setiap menang cukup besar untuk mendorong kinerja. Ini keunggulan asimetris."],
        ["Ada martingale / grid?", "Sama sekali tidak. Kedua robot membatasi risiko dengan jelas pada setiap transaksi, tidak averaging, tidak menahan posisi rugi."],
        ["Apa yang saya butuhkan untuk menjalankannya?", "MetaTrader 5 + akun dengan emas (XAUUSD), sebaiknya spread rendah. VPS disarankan agar robot berjalan 24/5 tanpa terputus."],
        ["Bagaimana sewa bekerja?", "Anda memilih periode 1 bulan / 6 bulan / 1 tahun. Robot aktif selama paket berlaku dan terikat pada akun MT5 Anda."],
        ["Bisakah saya batalkan?", "Bisa, kapan saja — tanpa kontrak. Paket tetap berjalan sampai akhir periode yang sudah Anda bayar."],
        ["Apakah saya butuh pengalaman trading?", "Tidak. Robot sepenuhnya otomatis. Anda hanya perlu mengaturnya sekali. Disarankan mencoba di akun demo dulu sebelum uang nyata."],
        ["Apakah profit dijamin?", "Tidak — dan jangan percaya siapa pun yang menjanjikannya. Angka adalah hasil teruji pada data historis. Kami menyediakan alat, bukan menjual janji."],
      ],
      notFound: "Ada pertanyaan lain?", telegram: "Hubungi kami di Telegram",
    },
    tools: {
      eyebrow: "Gratis", title: "Kalkulator lot — cepat, akurat.",
      body: "Pilih pasangan + strategi contoh, lihat langsung kurva ekuitas, win rate, dan drawdown pada data historis. Tanpa akun — alat gratis dari Dralvo.",
      cta: "Buka kalkulator lot", note: "Segera hadir — untuk semua trader.",
    },
    pricing: {
      eyebrow: "Harga", title: "Sewa robot, mulai hari ini.",
      intro: "Mulai gratis via Dralvo IB, atau buka seluruh ekosistem dengan Dralvo Unlimited. Batalkan kapan saja.",
      periods: { monthly: "1 bulan", sixmo: "6 bulan", yearly: "1 tahun" },
      save: { sixmo: "hemat 15%", yearly: "hemat 30%" },
      perMonth: "/bln", popular: "Populer",
      cancelNote: "Batalkan kapan saja · tanpa kontrak · termasuk bantuan instalasi.",
      tiers: [
        { id: "free", name: "Free", tagline: "Dapatkan EA gratis via Dralvo IB", cta: "Buka akun, dapatkan EA", features: ["TiGold EA gratis", "1 akun live MT5 via IB", "1 akun demo selama 30 hari", "Kalkulator lot", "Komunitas Telegram", "Pembaruan EA dasar"] },
        { id: "unlimited", name: "Dralvo Unlimited", tagline: "Seluruh ekosistem Dralvo", cta: "Buka semua Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Akun MT5 tak terbatas", "Akun demo tak terbatas", "Telegram VIP", "Pembaruan EA berkelanjutan", "Bantuan instalasi", "1 VPS termasuk", "Akses awal EA baru", "Dukungan prioritas"] },
      ],
    },
    finalCta: {
      eyebrow: "Siap?", title: "Biarkan robot trading. Anda jaga disiplin.",
      body: "Mulai gratis dengan indikator, alat, dan komunitas. Atau sewa robot dan biarkan bekerja 24/5 di akun Anda.",
      primaryCta: "Lihat paket sewa", secondaryCta: "Gabung komunitas Telegram", guarantee: "Batalkan kapan saja · Tanpa kontrak · Bantuan instalasi",
    },
    footer: {
      tagline: "Dralvo Capital — robot trading emas otomatis. Strategi teruji pada data nyata.",
      product: "Produk", company: "Perusahaan", legal: "Legal",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M5)", tools: "Kalkulator lot", trackRecord: "Performa",
      telegram: "Telegram", login: "Masuk", privacy: "Privasi", terms: "Ketentuan", disclaimer: "Penafian",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  ru: {
    nav: { products: "Продукты", evidence: "Результаты", pricing: "Цены", tools: "Инструменты", login: "Войти", cta: "Попробовать" },
    hero: {
      eyebrow: "Dralvo Capital · Автоматические золотые торговые роботы",
      titleA: "Две машины. Один металл. ", titleEm: "Реальные результаты.",
      subtitle: "Два золотых робота XAUUSD, два стиля — терпеливый свинг и быстрый скальп. Обе стратегии проверены на реальных данных. Без мартингейла, без сетки, без приукрашивания.",
      ctaPrimary: "Смотреть оба продукта", ctaSecondary: "Смотреть результаты",
      metalNote: ".9999 — прозрачно, как чистое золото",
      equityLabel: "Кривая капитала — GoldMaster", equityRisk: "Риск 5% · 10 лет · иллюстративно",
    },
    products: {
      eyebrow: "Два продукта — параллельно", title: "Выберите свой стиль.",
      intro: "Одна дисциплина риска, разный ритм. Оба проверены на реальных рыночных данных.",
      styleName: { swing: "Терпеливый — большая волна", scalp: "Быстрый — импульс", free: "Адаптивный — защита капитала" },
      directionLabels: { long: "По тренду", both: "В обе стороны" },
      headlineLabels: ["Доход (реком. конфиг.)", "Profit Factor", "Винрейт", "Макс. просадка"],
      recommendedRiskLabel: "Конфиг.",
      verified: { goldmaster: "Проверено на 10 годах реальных данных золота", scalp: "Проверено на 100% реальных тиковых данных", tigold: "Бесплатно — откройте счёт Dralvo IB" },
      pitch: {
        goldmaster: "Золотой робот для терпеливых — ловит большие волны золота и ставит качество выше количества. Выигрывает избирательно, но каждый выигрыш достаточно крупный, чтобы двигать результат.",
        scalp: "Золотой робот для быстрого темпа — ловит сильные внутридневные импульсы и аккуратно выходит. Высокий винрейт, почти без удержания позиций на ночь.",
        tigold: "Адаптивный EA для XAUUSD — бесплатно навсегда при открытии счёта через партнёра Dralvo IB. 3 слоя защиты капитала: пауза при серии убытков, дневной стоп и фильтр новостей.",
      },
      bullets: {
        goldmaster: ["Проверен на 10 годах — через каждый бычий и медвежий цикл золота", "Использует данные институционального позиционирования для чтения потока крупных денег", "Абсолютная дисциплина риска: каждая сделка защищена, убыток никогда не удерживается"],
        scalp: ["Проверен на 100% реальных тиковых данных · 6/6 месяцев в плюсе", "БЕЗ сетки · БЕЗ мартингейла · БЕЗ усреднения", "Решительные входы и выходы, минимум ночных позиций"],
        tigold: ["Бесплатно навсегда — просто откройте счёт по ссылке Dralvo IB", "Работает на XAUUSD · Умный трейлинг-стоп", "3 слоя защиты капитала: серия убытков → пауза, дневной убыток → стоп, новости → избегать"],
      },
      badgePopular: "Популярно",
      badgePro: "Профессионал",
      cta: "Получить", viewReport: "Полный отчёт",
      evidenceEyebrow: "Проверенные результаты", evidenceTitle: "Цифры говорят сами.",
      matrix: { title: "Профиль риска", risk: "Конфиг.", ret: "Доход", dd: "Макс. DD", pf: "PF", cagr: "в год", trades: "Сделки" },
      statLabels: { trades: "Всего сделок", winRate: "Винрейт", avgWin: "Сред. прибыль", avgLoss: "Сред. убыток", rr: "Приб/Убыт", avgHold: "Сред. удержание", streak: "Серия П/У" },
      monthlyTitle: "Доход по месяцам",
    },
    trust: {
      eyebrow: "Почему можно доверять", title: "В отличие от 99% золотых роботов.",
      items: [
        { title: "Без мартингейла / сетки", body: "У каждой сделки есть чёткий лимит риска. Без усреднения, без удержания убыточных — кривая капитала не бомба замедленного действия." },
        { title: "Проверено на реальных данных", body: "GoldMaster на 10 годах золота, Scalp на 100% реальных тиках. Результаты публичны — без отобранных периодов." },
        { title: "Институциональные данные", body: "Использует данные институционального позиционирования, чтобы читать поведение умных денег, а не просто рисовать графики." },
        { title: "Прозрачность", body: "Доходность, винрейт и просадка — всё публично. Мы подаём цифры как пробирный отчёт." },
      ],
    },
    faq: {
      eyebrow: "Вопросы и ответы", title: "Всё, что нужно знать.",
      items: [
        ["Чем отличаются роботы?", "GoldMaster — это свинг на D1: терпеливый, мало сделок, едет на больших волнах. GoldScalp — M5: быстрые входы, закрытие в тот же день. TiGold — адаптивный движок (бесплатно через Dralvo IB). Тариф Dralvo Unlimited позволяет запускать все три."],
        ["GoldMaster выигрывает 43% — как он прибыльный?", "Потому что каждый выигрыш намного больше каждого убытка. Проигрывает чаще, но каждый выигрыш достаточно крупный, чтобы двигать результат. Это асимметричное преимущество."],
        ["Есть мартингейл / сетка?", "Категорически нет. Оба робота чётко ограничивают риск на каждой сделке, не усредняют и не удерживают убыточные позиции."],
        ["Что нужно для запуска?", "MetaTrader 5 + счёт с золотом (XAUUSD), желательно с низким спредом. Рекомендуется VPS, чтобы робот работал 24/5 без перерывов."],
        ["Как работает аренда?", "Вы выбираете период 1 месяц / 6 месяцев / 1 год. Робот активен, пока действует тариф, и привязан к вашему счёту MT5."],
        ["Можно отменить?", "Да, в любой момент — без контракта. Тариф работает до конца оплаченного периода."],
        ["Нужен ли опыт торговли?", "Нет. Робот полностью автоматический. Настроить нужно один раз. Рекомендуем сначала протестировать на демо-счёте, прежде чем использовать реальные деньги."],
        ["Гарантируется ли прибыль?", "Нет — и не верьте тем, кто это обещает. Цифры — это результаты, проверенные на исторических данных. Мы даём инструменты, а не продаём обещания."],
      ],
      notFound: "Другой вопрос?", telegram: "Напишите нам в Telegram",
    },
    tools: {
      eyebrow: "Бесплатно", title: "Калькулятор лота — быстро, точно.",
      body: "Выберите пару + пример стратегии и сразу увидите кривую капитала, винрейт и просадку на исторических данных. Без аккаунта — бесплатный инструмент Dralvo.",
      cta: "Открыть калькулятор", note: "Скоро — для каждого трейдера.",
    },
    pricing: {
      eyebrow: "Цены", title: "Арендуйте робота, начните сегодня.",
      intro: "Начните бесплатно через Dralvo IB или откройте всю экосистему с Dralvo Unlimited. Отмена в любой момент.",
      periods: { monthly: "1 месяц", sixmo: "6 месяцев", yearly: "1 год" },
      save: { sixmo: "скидка 15%", yearly: "скидка 30%" },
      perMonth: "/мес", popular: "Популярно",
      cancelNote: "Отмена в любой момент · без контракта · поддержка установки включена.",
      tiers: [
        { id: "free", name: "Free", tagline: "Получите EA бесплатно через Dralvo IB", cta: "Открыть счёт и получить EA", features: ["TiGold EA бесплатно", "1 реальный счёт MT5 через IB", "1 демо-счёт на 30 дней", "Калькулятор лота", "Сообщество Telegram", "Базовые обновления EA"] },
        { id: "unlimited", name: "Dralvo Unlimited", tagline: "Вся экосистема Dralvo", cta: "Открыть весь Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Неограниченно счетов MT5", "Неограниченно демо-счетов", "Telegram VIP", "Постоянные обновления EA", "Помощь с установкой", "1 VPS включён", "Ранний доступ к новым EA", "Приоритетная поддержка"] },
      ],
    },
    finalCta: {
      eyebrow: "Готовы?", title: "Пусть робот торгует. Дисциплина — за вами.",
      body: "Начните бесплатно с индикатора, инструментов и сообщества. Или арендуйте робота, и пусть он работает 24/5 на вашем счёте.",
      primaryCta: "Смотреть тарифы аренды", secondaryCta: "Вступить в сообщество Telegram", guarantee: "Отмена в любой момент · Без контракта · Поддержка установки",
    },
    footer: {
      tagline: "Dralvo Capital — автоматические золотые торговые роботы. Стратегии проверены на реальных данных.",
      product: "Продукты", company: "Компания", legal: "Юридическое",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M5)", tools: "Калькулятор лота", trackRecord: "Результаты",
      telegram: "Telegram", login: "Войти", privacy: "Конфиденциальность", terms: "Условия", disclaimer: "Оговорка",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
  "pt-BR": {
    nav: { products: "Produtos", evidence: "Desempenho", pricing: "Preços", tools: "Ferramentas", login: "Entrar", cta: "Testar" },
    hero: {
      eyebrow: "Dralvo Capital · Robôs de trading de ouro automáticos",
      titleA: "Duas máquinas. Um metal. ", titleEm: "Resultados reais.",
      subtitle: "Dois robôs de ouro XAUUSD, dois estilos — swing paciente e scalp veloz. Ambos são estratégias verificadas em dados reais. Sem martingale, sem grid, sem maquiagem.",
      ctaPrimary: "Ver os dois produtos", ctaSecondary: "Ver desempenho",
      metalNote: ".9999 — transparente como ouro puro",
      equityLabel: "Curva de capital — GoldMaster", equityRisk: "Risco 5% · 10 anos · ilustrativo",
    },
    products: {
      eyebrow: "Dois produtos — em paralelo", title: "Escolha seu estilo.",
      intro: "Mesma disciplina de risco, ritmo diferente. Ambos verificados em dados reais de mercado.",
      styleName: { swing: "Paciente — a grande onda", scalp: "Rápido — o golpe de momentum", free: "Adaptativo — proteção de capital" },
      directionLabels: { long: "A favor da tendência", both: "Ambas as direções" },
      headlineLabels: ["Retorno (config. recom.)", "Profit Factor", "Taxa de acerto", "Drawdown máx."],
      recommendedRiskLabel: "Config.",
      verified: { goldmaster: "Verificado em 10 anos de dados reais de ouro", scalp: "Verificado em dados de ticks 100% reais", tigold: "Grátis — abra uma conta Dralvo IB" },
      pitch: {
        goldmaster: "Um robô de ouro para os pacientes — cavalga as grandes ondas do ouro e prioriza qualidade sobre quantidade. Ganha de forma seletiva, mas cada ganho é grande o bastante para impulsionar o desempenho.",
        scalp: "Um robô de ouro para o ritmo rápido — captura fortes impulsos intradiários e sai de forma limpa. Alta taxa de acerto, quase sem exposição overnight.",
        tigold: "Um EA adaptativo para XAUUSD — grátis para sempre ao abrir uma conta por um parceiro IB da Dralvo. Proteção de capital em 3 camadas: pausa por sequência de perdas, stop diário e filtro de notícias.",
      },
      bullets: {
        goldmaster: ["Verificado ao longo de 10 anos — por cada ciclo de alta e baixa do ouro", "Aproveita dados de posicionamento institucional para ler o fluxo do dinheiro grande", "Disciplina de risco absoluta: cada operação é protegida, nunca mantida no prejuízo"],
        scalp: ["Verificado em ticks 100% reais · 6/6 meses positivos", "SEM grid · SEM martingale · SEM preço médio", "Entradas e saídas decididas, exposição overnight mínima"],
        tigold: ["Grátis para sempre — basta abrir uma conta pelo link IB da Dralvo", "Roda em XAUUSD · Trailing stop inteligente", "Proteção de capital em 3 camadas: sequência de perdas → pausa, perda diária → stop, notícias → evitar"],
      },
      badgePopular: "Popular",
      badgePro: "Profissional",
      cta: "Obter", viewReport: "Ver relatório completo",
      evidenceEyebrow: "Desempenho verificado", evidenceTitle: "Os números falam.",
      matrix: { title: "Perfil de risco", risk: "Config.", ret: "Retorno", dd: "DD máx.", pf: "PF", cagr: "Ao ano", trades: "Ops." },
      statLabels: { trades: "Operações", winRate: "Taxa de acerto", avgWin: "Ganho médio", avgLoss: "Perda média", rr: "Ganho/Perda", avgHold: "Duração média", streak: "Sequência G/P" },
      monthlyTitle: "Ganhos mensais",
    },
    trust: {
      eyebrow: "Por que confiar", title: "Diferente de 99% dos robôs de ouro.",
      items: [
        { title: "Sem martingale / grid", body: "Cada operação tem um limite de risco claro. Sem preço médio, sem segurar perdedoras — a curva de capital não é uma bomba-relógio." },
        { title: "Verificado em dados reais", body: "GoldMaster ao longo de 10 anos de ouro, Scalp em ticks 100% reais. O desempenho é público — sem janelas selecionadas." },
        { title: "Dados institucionais", body: "Aproveita dados de posicionamento institucional para ler o comportamento do smart-money, não apenas desenhar gráficos." },
        { title: "Transparente", body: "Retorno, taxa de acerto e drawdown são todos públicos. Apresentamos os números como um laudo de ensaio." },
      ],
    },
    faq: {
      eyebrow: "Perguntas frequentes", title: "Tudo o que você precisa saber.",
      items: [
        ["Como os robôs se diferenciam?", "GoldMaster é um swing D1 — paciente, poucas operações, surfa as grandes ondas. GoldScalp é M5 — entradas rápidas, fecha no dia. TiGold é um motor adaptativo (grátis via Dralvo IB). O plano Dralvo Unlimited permite rodar os três."],
        ["GoldMaster acerta 43% — como é lucrativo?", "Porque cada ganho é muito maior que cada perda. Perde mais vezes, mas cada vitória é grande o bastante para impulsionar o desempenho. É uma vantagem assimétrica."],
        ["Tem martingale / grid?", "De jeito nenhum. Os dois robôs limitam claramente o risco em cada operação, não fazem preço médio nem seguram perdedoras."],
        ["O que preciso para rodar?", "MetaTrader 5 + uma conta com ouro (XAUUSD), de preferência com spread baixo. Recomenda-se um VPS para o robô rodar 24/5 sem interrupção."],
        ["Como funciona o aluguel?", "Você escolhe um período de 1 mês / 6 meses / 1 ano. O robô fica ativo enquanto o plano estiver vigente e vinculado à sua conta MT5."],
        ["Posso cancelar?", "Sim, quando quiser — sem contrato. O plano continua ativo até o fim do período que você pagou."],
        ["Preciso de experiência em trading?", "Não. O robô é totalmente automático. Você só configura uma vez. Recomenda-se testar em conta demo antes de usar dinheiro real."],
        ["O lucro é garantido?", "Não — e não confie em quem promete isso. Os números são resultados verificados em dados históricos. Oferecemos ferramentas, não vendemos promessas."],
      ],
      notFound: "Outra pergunta?", telegram: "Fale conosco no Telegram",
    },
    tools: {
      eyebrow: "Grátis", title: "Calculadora de lote — rápida, precisa.",
      body: "Escolha um par + uma estratégia de exemplo e veja na hora a curva de capital, a taxa de acerto e o drawdown em dados históricos. Sem conta — uma ferramenta gratuita da Dralvo.",
      cta: "Abrir calculadora", note: "Em breve — para todo trader.",
    },
    pricing: {
      eyebrow: "Preços", title: "Alugue um robô, comece hoje.",
      intro: "Comece grátis via Dralvo IB ou desbloqueie todo o ecossistema com o Dralvo Unlimited. Cancele quando quiser.",
      periods: { monthly: "1 mês", sixmo: "6 meses", yearly: "1 ano" },
      save: { sixmo: "economize 15%", yearly: "economize 30%" },
      perMonth: "/mês", popular: "Popular",
      cancelNote: "Cancele quando quiser · sem contrato · suporte de instalação incluído.",
      tiers: [
        { id: "free", name: "Free", tagline: "Receba o EA grátis via Dralvo IB", cta: "Abrir conta e receber o EA", features: ["TiGold EA grátis", "1 conta real MT5 via IB", "1 conta demo por 30 dias", "Calculadora de lote", "Comunidade no Telegram", "Atualizações básicas de EA"] },
        { id: "unlimited", name: "Dralvo Unlimited", tagline: "Todo o ecossistema Dralvo", cta: "Desbloquear todo o Dralvo", features: ["GoldMaster", "GoldScalp", "TiGold", "Contas MT5 ilimitadas", "Contas demo ilimitadas", "Telegram VIP", "Atualizações contínuas de EA", "Suporte de instalação", "1 VPS incluído", "Acesso antecipado a novos EAs", "Suporte prioritário"] },
      ],
    },
    finalCta: {
      eyebrow: "Pronto?", title: "Deixe o robô operar. Você mantém a disciplina.",
      body: "Comece grátis com o indicador, as ferramentas e a comunidade. Ou alugue um robô e deixe-o trabalhar 24/5 na sua conta.",
      primaryCta: "Ver planos de aluguel", secondaryCta: "Entrar na comunidade do Telegram", guarantee: "Cancele quando quiser · Sem contrato · Suporte de instalação",
    },
    footer: {
      tagline: "Dralvo Capital — robôs de trading de ouro automáticos. Estratégias verificadas em dados reais.",
      product: "Produtos", company: "Empresa", legal: "Jurídico",
      goldmaster: "GoldMaster (D1)", scalp: "GoldScalp (M5)", tools: "Calculadora de lote", trackRecord: "Desempenho",
      telegram: "Telegram", login: "Entrar", privacy: "Privacidade", terms: "Termos", disclaimer: "Aviso legal",
      copyright: "© 2026 Dralvo Capital.",
    },
  },
});
