import { withLocaleFallback } from "@/lib/i18n";

/** Copy for the /tigold IB-onboarding page, in 8 locales. MT5 UI labels
 *  (File → Open Data Folder, Navigator, Allow Algo Trading, etc.) are kept in
 *  English inside install steps because the MetaTrader interface is English. */
export const TIGOLD_COPY = withLocaleFallback({
  ar: {
    navHome: "الرئيسية",
    heroEyebrow: "Dralvo Capital · مجاني مدى الحياة",
    heroSub1: "EA تكيفي لزوج XAUUSD — مجاني عند فتح حساب عبر شريك GTC التابع لـ Dralvo.",
    heroSub2: "حماية رأس المال على 3 طبقات. وقف خسارة متحرك ذكي. 1,105 صفقة موثقة على مدى 6 أشهر.",
    acc: { usd: { name: "حساب USD", desc: "سبريد منخفض، حجم قياسي" }, cent: { name: "حساب Cent", desc: "رأس مال صغير، مخاطرة منخفضة" } },
    s1: { eyebrow: "الخطوة 1", title: "افتح حساب GTC عبر Dralvo", sub: "اختر نوع الحساب وافتحه عبر رابط الشريك. GTC هو الوسيط الحصري لـ Dralvo.", copy: "نسخ", copied: "تم النسخ", open: "فتح حساب" },
    s2: { eyebrow: "الخطوة 2", titleDefault: "تحقق من حساب MT5 الخاص بك", titleVerified: "تم التحقق من الحساب", sub: "أدخل رقم حساب MT5 الذي فتحته للتو عبر رابط Dralvo IB.", placeholder: "رقم حساب MT5", verify: "تحقق", verifying: "جارٍ التحقق...", errFail: "فشل التحقق. يرجى المحاولة مرة أخرى.", errConn: "خطأ في الاتصال. يرجى المحاولة مرة أخرى.", selectFirst: "اختر نوع الحساب في الخطوة 1 أولاً.", account: "الحساب", via: "تم التحقق عبر Dralvo IB." },
    s3: { eyebrow: "الخطوة 3", title: "نزّل EA وثبّته", sub: "أكمل الخطوتين 1 و2 لإلغاء قفل التنزيل.", locked: "أكمل الخطوتين 1 و2 لإلغاء قفل التنزيل.", ea: "EA (.ex5)", preset: "الإعداد المسبق (.set)", guide: "الدليل", guideDesc: "HTML · افتحه في متصفح", installHeading: "دليل التثبيت" },
    install: [
      { title: "انسخ EA إلى MT5", body: "أغلق MT5. <strong>File → Open Data Folder</strong>. انسخ <code>Dralvo TiGold.ex5</code> إلى <code>MQL5\\Experts\\</code>. أعد فتح MT5." },
      { title: "اسحب EA إلى الرسم البياني", body: "<strong>Navigator → Expert Advisors</strong>، انقر بزر الفأرة الأيمن على <strong>Refresh</strong>. اسحب <strong>Dralvo TiGold</strong> إلى رسم بياني <strong>XAUUSD M1</strong>. تبويب Common: فعّل <strong>Allow Algo Trading</strong>." },
      { title: "حمّل ملف .set", body: "تبويب <strong>Inputs → Load</strong>، اختر <strong>Dralvo tigold v1.set</strong>. تحقق من أن <code>InpFixedLot</code> يناسب رأس مالك. انقر <strong>OK</strong>." },
      { title: "فعّل التداول الآلي", body: "شغّل زر <strong>Algo Trading</strong> في شريط الأدوات (يضيء باللون الأخضر). تظهر لوحة <strong>DRALVO TiGOLD</strong> في أعلى اليسار — EA قيد التشغيل." },
    ],
    s4: { eyebrow: "الخطوة 4", title: "تفعيل الترخيص", sub: "يحتاج EA إلى مفتاح ترخيص للعمل. احصل عليه مجاناً عبر بوت Telegram الخاص بـ Dralvo.", cardHeading: "راسل بوت Telegram للحصول على مفتاح الترخيص", l1: "افتح Telegram وراسل", l2: 'يرشدك البوت خطوة بخطوة: تأكيد حساب MT5 المفتوح عبر Dralvo IB + إيداع لا يقل عن <strong>$50 (حساب USD) أو 5,000 سنت (حساب Cent)</strong>', l3: "يتحقق المشرف ويوافق — ويصلك إشعار داخل المحادثة مباشرة", l4: "احصل على مفتاح الترخيص → أدخله في EA → ابدأ التداول", open: "فتح بوت Telegram", note: "ترخيص مجاني مدى الحياة للحسابات المسجلة عبر Dralvo IB (بشرط إيداع لا يقل عن $50 / 5,000 سنت). يرتبط كل ترخيص بحساب MT5 واحد. دعم بشري: @dralvoea." },
    bt: { eyebrow: "أداء موثق", title: "الأرقام تتحدث.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · تيكات حقيقية 100% · $10K، إعادة ضبط شهرية.", profile: "ملف المخاطرة — TiGold v3.0", kNet: "صافي الربح", kPf: "Profit Factor", kWin: "نسبة الربح", kDd: "أقصى تراجع", sTrades: "إجمالي الصفقات", sWin: "نسبة الربح", sAvgWin: "متوسط الربح", sAvgLoss: "متوسط الخسارة", sRr: "ربح/خسارة", sStreak: "سلسلة ربح/خسارة", final: "الرصيد النهائي" },
    faqEyebrow: "الأسئلة الشائعة",
    faqTitle: "كل ما تحتاج معرفته.",
    faq: [
      ["هل يحتاج EA إلى VPS؟", "يُنصح باستخدام VPS كي يعمل EA على مدار 24/5 دون انقطاع. يكفي VPS رخيص (~$5–10 شهرياً) مثبت عليه MT5."],
      ["هل يمكنني استخدام حساب تجريبي؟", "الحساب التجريبي مناسب للتعرف على المنصة، لكن ترخيص TiGold يتطلب حساباً حقيقياً مفتوحاً عبر Dralvo IB بإيداع لا يقل عن $50 / 5,000 سنت. لبداية منخفضة المخاطر استخدم حساب Cent بالحد الأدنى للإيداع."],
      ["نسبة PF لا تتجاوز ~1.18 — كيف يكون مربحاً؟", "نسبة ربح مرتفعة تبلغ ~76% إضافة إلى قفل ربح يومي: يحقق +6% لليوم ثم يتوقف، فتتراكم الأفضليات الصغيرة عبر ~1,105 صفقة على مدى 6 أشهر. يُختبر كل شهر على $10K جديدة (إعادة ضبط شهرية) لإبقاء التراجع دون 30%. الأفضلية رفيعة — أعد التحقق مع تراكم المزيد من بيانات التيكات الحقيقية."],
      ["كم رأس المال الذي أحتاجه للبدء؟", "يتيح حساب Cent البدء من $50 (5,000 سنت — الحد الأدنى للإيداع لتفعيل الترخيص). في حساب USD، يُنصح بـ $5,000 فأكثر كي يُبقي اللوت الثابت أقصى تراجع شهري قرب 28% — دون $5K يدفعه الحد الأدنى لللوت 0.01 لدى الوسيط إلى ما فوق 40%."],
    ] as [string, string][],
    cta: { eyebrow: "مستعد؟", title: "مجاني. إلى الأبد. دون شروط.", body: "افتح حساب GTC عبر Dralvo، ونزّل EA، واحصل على الترخيص — كل ذلك مجاناً. أنت تدفع فقط سبريد الوسيط، مثل أي حساب عادي.", primary: "ابدأ الآن", secondary: "اسأل على Telegram", guarantee: "الإلغاء في أي وقت · دون التزام · دعم التثبيت" },
  },
  en: {
    navHome: "Home",
    heroEyebrow: "Dralvo Capital · Free for life",
    heroSub1: "An adaptive EA for XAUUSD — free when you open an account through Dralvo's GTC partner.",
    heroSub2: "3-layer capital protection. Smart trailing stop. 1,105 verified trades over 6 months.",
    acc: { usd: { name: "USD account", desc: "Low spread, standard volume" }, cent: { name: "Cent account", desc: "Small capital, low risk" } },
    s1: { eyebrow: "Step 1", title: "Open a GTC account via Dralvo", sub: "Pick an account type and open it through the partner link. GTC is Dralvo's exclusive broker.", copy: "Copy", copied: "Copied", open: "Open account" },
    s2: { eyebrow: "Step 2", titleDefault: "Verify your MT5 account", titleVerified: "Account verified", sub: "Enter the MT5 account number you just opened via the Dralvo IB link.", placeholder: "MT5 account number", verify: "Verify", verifying: "Checking...", errFail: "Verification failed. Please try again.", errConn: "Connection error. Please try again.", selectFirst: "Pick an account type in step 1 first.", account: "Account", via: "Verified via Dralvo IB." },
    s3: { eyebrow: "Step 3", title: "Download & install the EA", sub: "Complete steps 1 & 2 to unlock the download.", locked: "Complete steps 1 & 2 to unlock the download.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Guide", guideDesc: "HTML · open in a browser", installHeading: "Installation guide" },
    install: [
      { title: "Copy the EA into MT5", body: "Close MT5. <strong>File → Open Data Folder</strong>. Copy <code>Dralvo TiGold.ex5</code> into <code>MQL5\\Experts\\</code>. Reopen MT5." },
      { title: "Drag the EA onto a chart", body: "<strong>Navigator → Expert Advisors</strong>, right-click <strong>Refresh</strong>. Drag <strong>Dralvo TiGold</strong> onto an <strong>XAUUSD M1</strong> chart. Common tab: tick <strong>Allow Algo Trading</strong>." },
      { title: "Load the .set file", body: "<strong>Inputs → Load</strong> tab, choose <strong>Dralvo tigold v1.set</strong>. Check that <code>InpFixedLot</code> fits your capital. Click <strong>OK</strong>." },
      { title: "Enable Auto Trading", body: "Turn on the <strong>Algo Trading</strong> button in the toolbar (it lights up green). The <strong>DRALVO TiGOLD</strong> panel appears top-left — the EA is running." },
    ],
    s4: { eyebrow: "Step 4", title: "Activate the license", sub: "The EA needs a license key to run. Get one free via Dralvo's Telegram bot.", cardHeading: "Message the Telegram bot for a license key", l1: "Open Telegram and message", l2: 'The bot walks you through: confirm your MT5 account under the Dralvo IB + a minimum deposit of <strong>$50 (USD account) or 5,000 cents (Cent account)</strong>', l3: "Admin verifies and approves — you get notified right in the chat", l4: "Get the license key → enter it in the EA → start trading", open: "Open Telegram bot", note: "Free lifetime license for accounts registered through the Dralvo IB (requires a minimum deposit of $50 / 5,000 cents). Each license is bound to one MT5 account. Human support: @dralvoea." },
    bt: { eyebrow: "Verified performance", title: "The numbers speak.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · 100% real ticks · $10K, monthly-reset.", profile: "Risk profile — TiGold v3.0", kNet: "Net profit", kPf: "Profit Factor", kWin: "Win rate", kDd: "Max drawdown", sTrades: "Total trades", sWin: "Win rate", sAvgWin: "Avg win", sAvgLoss: "Avg loss", sRr: "Win/Loss", sStreak: "Streak W/L", final: "Final balance" },
    faqEyebrow: "FAQ",
    faqTitle: "Everything you need to know.",
    faq: [
      ["Does the EA need a VPS?", "A VPS is recommended so the EA runs 24/5 without interruption. A cheap VPS (~$5–10/month) with MT5 installed is enough."],
      ["Can I use a demo account?", "Demo is fine for getting familiar with the platform, but the TiGold license requires a REAL account opened via the Dralvo IB with a minimum deposit of $50 / 5,000 cents. For a low-risk start, use a Cent account at the minimum deposit."],
      ["PF is only ~1.18 — how is it profitable?", "A high ~76% win rate plus a daily profit-lock: it banks +6% for the day then stops, so small edges add up across ~1,105 trades over 6 months. Each month is tested on a fresh $10K (monthly-reset) to keep drawdown under 30%. The edge is thin — re-validate as more real-tick data accrues."],
      ["How much capital do I need to start?", "A Cent account lets you start from $50 (5,000 cents — the minimum deposit to activate the license). On a USD account, $5,000+ is recommended so the fixed lot keeps the max monthly drawdown near 28% — below $5K the broker's 0.01 minimum lot pushes it past 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Ready?", title: "Free. Forever. No strings.", body: "Open a GTC account via Dralvo, download the EA, get the license — all free. You only pay the broker spread, like any normal account.", primary: "Start now", secondary: "Ask on Telegram", guarantee: "Cancel anytime · No commitment · Install support" },
  },

  vi: {
    navHome: "Trang chủ",
    heroEyebrow: "Dralvo Capital · Miễn phí trọn đời",
    heroSub1: "EA thích ứng cho XAUUSD — miễn phí khi mở tài khoản qua đối tác GTC của Dralvo.",
    heroSub2: "3 lớp bảo vệ vốn. Trailing stop thông minh. 1,105 lệnh kiểm chứng trong 6 tháng.",
    acc: { usd: { name: "Tài khoản USD", desc: "Spread thấp, khối lượng chuẩn" }, cent: { name: "Tài khoản Cent", desc: "Vốn nhỏ, rủi ro thấp" } },
    s1: { eyebrow: "Bước 1", title: "Mở tài khoản GTC qua Dralvo", sub: "Chọn loại tài khoản, mở qua link đối tác. GTC là broker độc quyền của Dralvo.", copy: "Copy", copied: "Đã copy", open: "Mở tài khoản" },
    s2: { eyebrow: "Bước 2", titleDefault: "Xác nhận tài khoản MT5", titleVerified: "Tài khoản đã xác nhận", sub: "Nhập số tài khoản MT5 bạn vừa mở qua link IB Dralvo.", placeholder: "Số tài khoản MT5", verify: "Xác nhận", verifying: "Đang kiểm tra...", errFail: "Xác nhận thất bại. Vui lòng thử lại.", errConn: "Lỗi kết nối. Vui lòng thử lại.", selectFirst: "Chọn loại tài khoản ở bước 1 trước.", account: "Tài khoản", via: "Đã xác nhận qua IB Dralvo." },
    s3: { eyebrow: "Bước 3", title: "Tải EA & cài đặt", sub: "Hoàn thành bước 1 & 2 để mở khóa tải về.", locked: "Hoàn thành Bước 1 & 2 để mở khóa tải về.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Hướng dẫn", guideDesc: "HTML · mở bằng trình duyệt", installHeading: "Hướng dẫn cài đặt" },
    install: [
      { title: "Chép EA vào MT5", body: "Đóng MT5. <strong>File → Open Data Folder</strong>. Chép <code>Dralvo TiGold.ex5</code> vào <code>MQL5\\Experts\\</code>. Mở lại MT5." },
      { title: "Kéo EA lên chart", body: "<strong>Navigator → Expert Advisors</strong>, chuột phải <strong>Refresh</strong>. Kéo <strong>Dralvo TiGold</strong> thả vào chart <strong>XAUUSD M1</strong>. Tab Common: tick <strong>Allow Algo Trading</strong>." },
      { title: "Nạp file .set", body: "Tab <strong>Inputs → Load</strong>, chọn <strong>Dralvo tigold v1.set</strong>. Kiểm tra <code>InpFixedLot</code> phù hợp vốn. Bấm <strong>OK</strong>." },
      { title: "Bật Auto Trading", body: "Bật nút <strong>Algo Trading</strong> trên thanh công cụ (biểu tượng sáng xanh). Góc trái chart hiện bảng <strong>DRALVO TiGOLD</strong> — EA đang chạy." },
    ],
    s4: { eyebrow: "Bước 4", title: "Kích hoạt license", sub: "EA cần license key để chạy. Nhận key miễn phí qua bot Telegram của Dralvo.", cardHeading: "Nhắn bot Telegram để nhận license key", l1: "Mở Telegram, nhắn bot", l2: 'Bot hướng dẫn từng bước: xác nhận tài khoản MT5 mở qua IB Dralvo + nạp tối thiểu <strong>$50 (tài khoản USD) hoặc 5.000 cent (tài khoản Cent)</strong>', l3: "Admin kiểm tra và duyệt — bạn nhận thông báo ngay trong chat", l4: "Nhận license key → nhập vào EA → bắt đầu giao dịch", open: "Mở bot Telegram", note: "License miễn phí vĩnh viễn cho tài khoản đăng ký qua IB Dralvo (điều kiện: nạp tối thiểu $50 / 5.000 cent). Mỗi license gắn với 1 số tài khoản MT5. Hỗ trợ người thật: @dralvoea." },
    bt: { eyebrow: "Hiệu suất đã kiểm chứng", title: "Số liệu nói thay lời.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · 100% tick thật · vốn $10K, reset hàng tháng.", profile: "Hồ sơ rủi ro — TiGold v3.0", kNet: "Lợi nhuận ròng", kPf: "Profit Factor", kWin: "Tỷ lệ thắng", kDd: "Drawdown tối đa", sTrades: "Tổng lệnh", sWin: "Tỷ lệ thắng", sAvgWin: "Lãi TB", sAvgLoss: "Lỗ TB", sRr: "Lãi/Lỗ", sStreak: "Chuỗi T/B", final: "Số dư cuối kỳ" },
    faqEyebrow: "Hỏi đáp",
    faqTitle: "Mọi điều bạn cần biết.",
    faq: [
      ["EA có cần VPS không?", "Khuyến nghị dùng VPS để EA chạy 24/5 không gián đoạn. Có thể thuê VPS giá rẻ (~$5-10/tháng) và cài MT5 lên đó."],
      ["Dùng được tài khoản demo không?", "Demo phù hợp để làm quen nền tảng, nhưng license TiGold yêu cầu tài khoản THẬT mở qua IB Dralvo và nạp tối thiểu $50 / 5.000 cent. Muốn bắt đầu rủi ro thấp, dùng tài khoản Cent với mức nạp tối thiểu."],
      ["Sao PF chỉ ~1.18 mà vẫn lãi?", "Tỷ lệ thắng cao ~76% cộng khóa lãi theo ngày: đạt +6%/ngày là dừng, nên các lợi thế nhỏ tích lại qua ~1,105 lệnh trong 6 tháng. Mỗi tháng test trên vốn $10K mới (reset hàng tháng) để giữ drawdown dưới 30%. Edge mỏng — cần kiểm chứng lại khi có thêm dữ liệu tick thật."],
      ["Cần bao nhiêu vốn để bắt đầu?", "Tài khoản Cent có thể bắt đầu từ $50 (5.000 cent — mức nạp tối thiểu để kích hoạt license). Tài khoản USD: khuyến nghị từ $5,000 trở lên để lot cố định giữ drawdown tháng cao nhất ~28% — dưới $5K, lot tối thiểu 0.01 đẩy DD vượt 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Sẵn sàng?", title: "Miễn phí. Vĩnh viễn. Không bắt buộc.", body: "Mở tài khoản GTC qua Dralvo, tải EA, nhận license — tất cả miễn phí. Bạn chỉ trả spread cho broker như mọi tài khoản bình thường.", primary: "Bắt đầu ngay", secondary: "Hỏi trên Telegram", guarantee: "Hủy bất cứ lúc nào · Không ràng buộc · Hỗ trợ cài đặt" },
  },

  es: {
    navHome: "Inicio",
    heroEyebrow: "Dralvo Capital · Gratis de por vida",
    heroSub1: "Un EA adaptativo para XAUUSD — gratis al abrir una cuenta con el socio GTC de Dralvo.",
    heroSub2: "Protección de capital en 3 capas. Trailing stop inteligente. 1,105 operaciones verificadas en 6 meses.",
    acc: { usd: { name: "Cuenta USD", desc: "Spread bajo, volumen estándar" }, cent: { name: "Cuenta Cent", desc: "Capital pequeño, bajo riesgo" } },
    s1: { eyebrow: "Paso 1", title: "Abre una cuenta GTC vía Dralvo", sub: "Elige un tipo de cuenta y ábrela por el enlace del socio. GTC es el bróker exclusivo de Dralvo.", copy: "Copiar", copied: "Copiado", open: "Abrir cuenta" },
    s2: { eyebrow: "Paso 2", titleDefault: "Verifica tu cuenta MT5", titleVerified: "Cuenta verificada", sub: "Introduce el número de cuenta MT5 que acabas de abrir vía el enlace IB de Dralvo.", placeholder: "Número de cuenta MT5", verify: "Verificar", verifying: "Comprobando...", errFail: "La verificación falló. Inténtalo de nuevo.", errConn: "Error de conexión. Inténtalo de nuevo.", selectFirst: "Elige primero un tipo de cuenta en el paso 1.", account: "Cuenta", via: "Verificado vía Dralvo IB." },
    s3: { eyebrow: "Paso 3", title: "Descarga e instala el EA", sub: "Completa los pasos 1 y 2 para desbloquear la descarga.", locked: "Completa los pasos 1 y 2 para desbloquear la descarga.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Guía", guideDesc: "HTML · ábrela en un navegador", installHeading: "Guía de instalación" },
    install: [
      { title: "Copia el EA en MT5", body: "Cierra MT5. <strong>File → Open Data Folder</strong>. Copia <code>Dralvo TiGold.ex5</code> en <code>MQL5\\Experts\\</code>. Vuelve a abrir MT5." },
      { title: "Arrastra el EA a un gráfico", body: "<strong>Navigator → Expert Advisors</strong>, clic derecho <strong>Refresh</strong>. Arrastra <strong>Dralvo TiGold</strong> a un gráfico <strong>XAUUSD M1</strong>. Pestaña Common: marca <strong>Allow Algo Trading</strong>." },
      { title: "Carga el archivo .set", body: "Pestaña <strong>Inputs → Load</strong>, elige <strong>Dralvo tigold v1.set</strong>. Verifica que <code>InpFixedLot</code> se ajuste a tu capital. Clic en <strong>OK</strong>." },
      { title: "Activa el Auto Trading", body: "Activa el botón <strong>Algo Trading</strong> en la barra (se pone verde). El panel <strong>DRALVO TiGOLD</strong> aparece arriba a la izquierda — el EA está funcionando." },
    ],
    s4: { eyebrow: "Paso 4", title: "Activa la licencia", sub: "El EA necesita una clave de licencia para funcionar. Consíguela gratis con el bot de Telegram de Dralvo.", cardHeading: "Escríbele al bot de Telegram para tu clave de licencia", l1: "Abre Telegram y escribe a", l2: 'El bot te guía paso a paso: confirma tu cuenta MT5 abierta vía IB de Dralvo + un depósito mínimo de <strong>$50 (cuenta USD) o 5.000 centavos (cuenta Cent)</strong>', l3: "El admin verifica y aprueba — recibes la notificación en el chat", l4: "Recibe la clave → introdúcela en el EA → empieza a operar", open: "Abrir bot de Telegram", note: "Licencia gratuita de por vida para cuentas registradas vía Dralvo IB (requiere depósito mínimo de $50 / 5.000 centavos). Cada licencia se vincula a una cuenta MT5. Soporte humano: @dralvoea." },
    bt: { eyebrow: "Rendimiento verificado", title: "Los números hablan.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · ticks 100% reales · $10K, reinicio mensual.", profile: "Perfil de riesgo — TiGold v3.0", kNet: "Beneficio neto", kPf: "Profit Factor", kWin: "Tasa de acierto", kDd: "Drawdown máx.", sTrades: "Operaciones", sWin: "Tasa de acierto", sAvgWin: "Gan. media", sAvgLoss: "Pérd. media", sRr: "Gan/Pérd", sStreak: "Racha G/P", final: "Saldo final" },
    faqEyebrow: "Preguntas frecuentes",
    faqTitle: "Todo lo que necesitas saber.",
    faq: [
      ["¿El EA necesita un VPS?", "Se recomienda un VPS para que el EA funcione 24/5 sin interrupciones. Un VPS barato (~$5–10/mes) con MT5 instalado es suficiente."],
      ["¿Puedo usar una cuenta demo?", "La demo sirve para familiarizarte con la plataforma, pero la licencia TiGold requiere una cuenta REAL abierta vía IB de Dralvo con depósito mínimo de $50 / 5.000 centavos. Para empezar con bajo riesgo, usa una cuenta Cent con el depósito mínimo."],
      ["El PF es solo ~1,18 — ¿cómo es rentable?", "Una alta tasa de acierto (~76%) más un bloqueo de ganancia diaria: asegura +6% al día y se detiene, así las pequeñas ventajas se acumulan en ~1.105 operaciones durante 6 meses. Cada mes se prueba con $10K nuevos (reinicio mensual) para mantener el drawdown bajo 30%. La ventaja es fina — revalida a medida que crezcan los datos de ticks reales."],
      ["¿Cuánto capital necesito para empezar?", "En cuenta Cent puedes empezar desde $50 (5.000 centavos — el depósito mínimo para activar la licencia). En cuenta USD se recomiendan $5.000+ para que el lote fijo mantenga el drawdown mensual máximo cerca del 28% — por debajo de $5K el lote mínimo de 0,01 lo lleva por encima del 40%."],
    ] as [string, string][],
    cta: { eyebrow: "¿Listo?", title: "Gratis. Para siempre. Sin ataduras.", body: "Abre una cuenta GTC vía Dralvo, descarga el EA, obtén la licencia — todo gratis. Solo pagas el spread del bróker, como en cualquier cuenta normal.", primary: "Empezar ahora", secondary: "Preguntar por Telegram", guarantee: "Cancela cuando quieras · Sin compromiso · Soporte de instalación" },
  },

  id: {
    navHome: "Beranda",
    heroEyebrow: "Dralvo Capital · Gratis seumur hidup",
    heroSub1: "EA adaptif untuk XAUUSD — gratis saat membuka akun melalui mitra GTC Dralvo.",
    heroSub2: "Proteksi modal 3 lapis. Trailing stop pintar. 1,105 transaksi teruji dalam 6 bulan.",
    acc: { usd: { name: "Akun USD", desc: "Spread rendah, volume standar" }, cent: { name: "Akun Cent", desc: "Modal kecil, risiko rendah" } },
    s1: { eyebrow: "Langkah 1", title: "Buka akun GTC via Dralvo", sub: "Pilih jenis akun dan buka lewat tautan mitra. GTC adalah broker eksklusif Dralvo.", copy: "Salin", copied: "Tersalin", open: "Buka akun" },
    s2: { eyebrow: "Langkah 2", titleDefault: "Verifikasi akun MT5 Anda", titleVerified: "Akun terverifikasi", sub: "Masukkan nomor akun MT5 yang baru Anda buka via tautan IB Dralvo.", placeholder: "Nomor akun MT5", verify: "Verifikasi", verifying: "Memeriksa...", errFail: "Verifikasi gagal. Silakan coba lagi.", errConn: "Kesalahan koneksi. Silakan coba lagi.", selectFirst: "Pilih jenis akun di langkah 1 dulu.", account: "Akun", via: "Terverifikasi via Dralvo IB." },
    s3: { eyebrow: "Langkah 3", title: "Unduh & pasang EA", sub: "Selesaikan langkah 1 & 2 untuk membuka unduhan.", locked: "Selesaikan langkah 1 & 2 untuk membuka unduhan.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Panduan", guideDesc: "HTML · buka di browser", installHeading: "Panduan instalasi" },
    install: [
      { title: "Salin EA ke MT5", body: "Tutup MT5. <strong>File → Open Data Folder</strong>. Salin <code>Dralvo TiGold.ex5</code> ke <code>MQL5\\Experts\\</code>. Buka MT5 lagi." },
      { title: "Seret EA ke grafik", body: "<strong>Navigator → Expert Advisors</strong>, klik kanan <strong>Refresh</strong>. Seret <strong>Dralvo TiGold</strong> ke grafik <strong>XAUUSD M1</strong>. Tab Common: centang <strong>Allow Algo Trading</strong>." },
      { title: "Muat file .set", body: "Tab <strong>Inputs → Load</strong>, pilih <strong>Dralvo tigold v1.set</strong>. Pastikan <code>InpFixedLot</code> sesuai modal Anda. Klik <strong>OK</strong>." },
      { title: "Aktifkan Auto Trading", body: "Aktifkan tombol <strong>Algo Trading</strong> di toolbar (menyala hijau). Panel <strong>DRALVO TiGOLD</strong> muncul di kiri atas — EA sedang berjalan." },
    ],
    s4: { eyebrow: "Langkah 4", title: "Aktifkan lisensi", sub: "EA butuh kunci lisensi untuk berjalan. Dapatkan gratis via bot Telegram Dralvo.", cardHeading: "Hubungi bot Telegram untuk kunci lisensi", l1: "Buka Telegram dan hubungi", l2: 'Bot memandu langkah demi langkah: konfirmasi akun MT5 yang dibuka via IB Dralvo + deposit minimal <strong>$50 (akun USD) atau 5.000 sen (akun Cent)</strong>', l3: "Admin memverifikasi dan menyetujui — notifikasi langsung di chat", l4: "Dapatkan kunci lisensi → masukkan ke EA → mulai trading", open: "Buka bot Telegram", note: "Lisensi gratis seumur hidup untuk akun terdaftar via IB Dralvo (syarat: deposit minimal $50 / 5.000 sen). Setiap lisensi terikat ke satu akun MT5. Dukungan manusia: @dralvoea." },
    bt: { eyebrow: "Performa terverifikasi", title: "Angka yang berbicara.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · tick 100% nyata · $10K, reset bulanan.", profile: "Profil risiko — TiGold v3.0", kNet: "Laba bersih", kPf: "Profit Factor", kWin: "Win rate", kDd: "Drawdown maks", sTrades: "Total transaksi", sWin: "Win rate", sAvgWin: "Profit rata2", sAvgLoss: "Rugi rata2", sRr: "Untung/Rugi", sStreak: "Beruntun M/K", final: "Saldo akhir" },
    faqEyebrow: "Tanya jawab",
    faqTitle: "Semua yang perlu Anda tahu.",
    faq: [
      ["Apakah EA butuh VPS?", "VPS disarankan agar EA berjalan 24/5 tanpa terputus. VPS murah (~$5–10/bulan) dengan MT5 terpasang sudah cukup."],
      ["Bisakah pakai akun demo?", "Demo cocok untuk mengenal platform, tetapi lisensi TiGold membutuhkan akun RIIL yang dibuka via IB Dralvo dengan deposit minimal $50 / 5.000 sen. Untuk mulai dengan risiko rendah, gunakan akun Cent dengan deposit minimal."],
      ["PF hanya ~1,18 — kok bisa untung?", "Win rate tinggi ~76% plus kunci profit harian: mengamankan +6% per hari lalu berhenti, jadi keunggulan kecil terakumulasi pada ~1.105 transaksi selama 6 bulan. Setiap bulan diuji pada $10K baru (reset bulanan) agar drawdown di bawah 30%. Edge-nya tipis — validasi ulang seiring bertambahnya data tick nyata."],
      ["Berapa modal untuk mulai?", "Akun Cent bisa mulai dari $50 (5.000 sen — deposit minimal untuk mengaktifkan lisensi). Akun USD disarankan $5.000+ agar lot tetap menjaga drawdown bulanan maksimum sekitar 28% — di bawah $5K, lot minimum 0,01 mendorongnya di atas 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Siap?", title: "Gratis. Selamanya. Tanpa ikatan.", body: "Buka akun GTC via Dralvo, unduh EA, dapatkan lisensi — semua gratis. Anda hanya membayar spread broker, seperti akun biasa.", primary: "Mulai sekarang", secondary: "Tanya di Telegram", guarantee: "Batalkan kapan saja · Tanpa komitmen · Bantuan instalasi" },
  },

  "pt-BR": {
    navHome: "Início",
    heroEyebrow: "Dralvo Capital · Grátis para sempre",
    heroSub1: "Um EA adaptativo para XAUUSD — grátis ao abrir uma conta pelo parceiro GTC da Dralvo.",
    heroSub2: "Proteção de capital em 3 camadas. Trailing stop inteligente. 1.105 operações verificadas em 6 meses.",
    acc: { usd: { name: "Conta USD", desc: "Spread baixo, volume padrão" }, cent: { name: "Conta Cent", desc: "Capital pequeno, baixo risco" } },
    s1: { eyebrow: "Passo 1", title: "Abra uma conta GTC via Dralvo", sub: "Escolha um tipo de conta e abra pelo link do parceiro. A GTC é a corretora exclusiva da Dralvo.", copy: "Copiar", copied: "Copiado", open: "Abrir conta" },
    s2: { eyebrow: "Passo 2", titleDefault: "Verifique sua conta MT5", titleVerified: "Conta verificada", sub: "Informe o número da conta MT5 que você acabou de abrir pelo link IB da Dralvo.", placeholder: "Número da conta MT5", verify: "Verificar", verifying: "Verificando...", errFail: "Falha na verificação. Tente novamente.", errConn: "Erro de conexão. Tente novamente.", selectFirst: "Escolha um tipo de conta no passo 1 primeiro.", account: "Conta", via: "Verificado via Dralvo IB." },
    s3: { eyebrow: "Passo 3", title: "Baixe e instale o EA", sub: "Conclua os passos 1 e 2 para desbloquear o download.", locked: "Conclua os passos 1 e 2 para desbloquear o download.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Guia", guideDesc: "HTML · abra no navegador", installHeading: "Guia de instalação" },
    install: [
      { title: "Copie o EA para o MT5", body: "Feche o MT5. <strong>File → Open Data Folder</strong>. Copie <code>Dralvo TiGold.ex5</code> para <code>MQL5\\Experts\\</code>. Reabra o MT5." },
      { title: "Arraste o EA para um gráfico", body: "<strong>Navigator → Expert Advisors</strong>, clique direito <strong>Refresh</strong>. Arraste <strong>Dralvo TiGold</strong> para um gráfico <strong>XAUUSD M1</strong>. Aba Common: marque <strong>Allow Algo Trading</strong>." },
      { title: "Carregue o arquivo .set", body: "Aba <strong>Inputs → Load</strong>, escolha <strong>Dralvo tigold v1.set</strong>. Verifique se <code>InpFixedLot</code> combina com seu capital. Clique em <strong>OK</strong>." },
      { title: "Ative o Auto Trading", body: "Ligue o botão <strong>Algo Trading</strong> na barra (fica verde). O painel <strong>DRALVO TiGOLD</strong> aparece no canto superior esquerdo — o EA está rodando." },
    ],
    s4: { eyebrow: "Passo 4", title: "Ative a licença", sub: "O EA precisa de uma chave de licença para rodar. Pegue uma grátis pelo bot do Telegram da Dralvo.", cardHeading: "Fale com o bot do Telegram para sua chave de licença", l1: "Abra o Telegram e fale com", l2: 'O bot te guia passo a passo: confirme sua conta MT5 aberta via IB da Dralvo + depósito mínimo de <strong>$50 (conta USD) ou 5.000 centavos (conta Cent)</strong>', l3: "O admin verifica e aprova — você recebe a notificação no chat", l4: "Receba a chave → insira no EA → comece a operar", open: "Abrir bot do Telegram", note: "Licença grátis vitalícia para contas registradas via IB da Dralvo (requer depósito mínimo de $50 / 5.000 centavos). Cada licença é vinculada a uma conta MT5. Suporte humano: @dralvoea." },
    bt: { eyebrow: "Desempenho verificado", title: "Os números falam.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · ticks 100% reais · $10K, reinício mensal.", profile: "Perfil de risco — TiGold v3.0", kNet: "Lucro líquido", kPf: "Profit Factor", kWin: "Taxa de acerto", kDd: "Drawdown máx.", sTrades: "Operações", sWin: "Taxa de acerto", sAvgWin: "Ganho médio", sAvgLoss: "Perda média", sRr: "Ganho/Perda", sStreak: "Sequência G/P", final: "Saldo final" },
    faqEyebrow: "Perguntas frequentes",
    faqTitle: "Tudo o que você precisa saber.",
    faq: [
      ["O EA precisa de VPS?", "Recomenda-se um VPS para o EA rodar 24/5 sem interrupção. Um VPS barato (~$5–10/mês) com MT5 instalado é suficiente."],
      ["Posso usar conta demo?", "A demo serve para conhecer a plataforma, mas a licença TiGold exige conta REAL aberta via IB da Dralvo com depósito mínimo de $50 / 5.000 centavos. Para começar com baixo risco, use uma conta Cent no depósito mínimo."],
      ["O PF é só ~1,18 — como é lucrativo?", "Uma alta taxa de acerto (~76%) mais trava de lucro diária: garante +6% no dia e para, então pequenas vantagens se acumulam em ~1.105 operações ao longo de 6 meses. Cada mês é testado com $10K novos (reinício mensal) para manter o drawdown abaixo de 30%. A vantagem é fina — revalide conforme mais dados de ticks reais surgem."],
      ["Quanto capital preciso para começar?", "Em conta Cent dá para começar a partir de $50 (5.000 centavos — o depósito mínimo para ativar a licença). Em conta USD, recomenda-se $5.000+ para que o lote fixo mantenha o drawdown mensal máximo perto de 28% — abaixo de $5K, o lote mínimo de 0,01 o leva acima de 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Pronto?", title: "Grátis. Para sempre. Sem amarras.", body: "Abra uma conta GTC via Dralvo, baixe o EA, pegue a licença — tudo grátis. Você só paga o spread da corretora, como em qualquer conta normal.", primary: "Começar agora", secondary: "Perguntar no Telegram", guarantee: "Cancele quando quiser · Sem compromisso · Suporte de instalação" },
  },
});
