import { withLocaleFallback } from "@/lib/i18n";

/** Copy for the /tigold IB-onboarding page, in 8 locales. MT5 UI labels
 *  (File → Open Data Folder, Navigator, Allow Algo Trading, etc.) are kept in
 *  English inside install steps because the MetaTrader interface is English. */
export const TIGOLD_COPY = withLocaleFallback({
  en: {
    navHome: "Home",
    heroEyebrow: "Dralvo Capital · Free for life",
    heroSub1: "An adaptive EA for XAUUSD — free when you open an account through Dralvo's GTC partner.",
    heroSub2: "3-layer capital protection. Smart trailing stop. 1,105 verified trades over 6 months.",
    acc: { usd: { name: "USD account", desc: "Low spread, standard volume" }, cent: { name: "Cent account", desc: "Small capital, low risk" } },
    s1: { eyebrow: "Step 1", title: "Open a GTC account via Dralvo", sub: "Pick an account type and open it through the partner link. GTC is Dralvo's exclusive broker.", copy: "Copy", copied: "Copied", open: "Open account" },
    s2: { eyebrow: "Step 2", titleDefault: "Verify your MT5 account", titleVerified: "Account verified", sub: "Enter the MT5 account number you just opened via the Dralvo IB link.", placeholder: "MT5 account number", verify: "Verify", verifying: "Checking...", errFail: "Verification failed. Please try again.", errConn: "Connection error. Please try again.", selectFirst: "Pick an account type in step 1 first.", account: "Account", via: "Verified via Dralvo IB." },
    s3: { eyebrow: "Step 3", title: "Download & install the EA", sub: "Complete steps 1 & 2 to unlock the download.", locked: "Complete steps 1 & 2 to unlock the download.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Guide", guideDesc: "HTML · open in a browser", installHeading: "Installation guide" },
    install: [
      { title: "Copy the EA into MT5", body: "Close MT5. <strong>File → Open Data Folder</strong>. Copy <code>Dralvo TiGold.ex5</code> into <code>MQL5\\Experts\\</code>. Reopen MT5." },
      { title: "Drag the EA onto a chart", body: "<strong>Navigator → Expert Advisors</strong>, right-click <strong>Refresh</strong>. Drag <strong>Dralvo TiGold</strong> onto an <strong>XAUUSD M1</strong> chart. Common tab: tick <strong>Allow Algo Trading</strong>." },
      { title: "Load the .set file", body: "<strong>Inputs → Load</strong> tab, choose <strong>Dralvo tigold v1.set</strong>. Check that <code>InpFixedLot</code> fits your capital. Click <strong>OK</strong>." },
      { title: "Enable Auto Trading", body: "Turn on the <strong>Algo Trading</strong> button in the toolbar (it lights up green). The <strong>DRALVO TiGOLD</strong> panel appears top-left — the EA is running." },
    ],
    s4: { eyebrow: "Step 4", title: "Activate the license", sub: "The EA needs a license key to run. Get one free via Telegram.", cardHeading: "Message us on Telegram for a license key", l1: "Open Telegram and search for", l2: 'Send: <strong>"TiGold license [MT5 account number]"</strong>', l3: "Admin checks the account belongs to Dralvo IB", l4: "Get the license key → enter it in the EA → start trading", open: "Open Telegram", note: "Free lifetime license for accounts registered through Dralvo IB. Each license is bound to one MT5 account number." },
    bt: { eyebrow: "Verified performance", title: "The numbers speak.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · 100% real ticks · $10K, monthly-reset.", profile: "Risk profile — TiGold v3.0", kNet: "Net profit", kPf: "Profit Factor", kWin: "Win rate", kDd: "Max drawdown", sTrades: "Total trades", sWin: "Win rate", sAvgWin: "Avg win", sAvgLoss: "Avg loss", sRr: "Win/Loss", sStreak: "Streak W/L", final: "Final balance" },
    faqEyebrow: "FAQ",
    faqTitle: "Everything you need to know.",
    faq: [
      ["Does the EA need a VPS?", "A VPS is recommended so the EA runs 24/5 without interruption. A cheap VPS (~$5–10/month) with MT5 installed is enough."],
      ["Can I use a demo account?", "Yes. Open a demo account via the Dralvo IB link, confirm the demo account number — you still get the EA free."],
      ["PF is only ~1.18 — how is it profitable?", "A high ~76% win rate plus a daily profit-lock: it banks +6% for the day then stops, so small edges add up across ~1,105 trades over 6 months. Each month is tested on a fresh $10K (monthly-reset) to keep drawdown under 30%. The edge is thin — re-validate as more real-tick data accrues."],
      ["How much capital do I need to start?", "A Cent account lets you test from ~$10–50. On a USD account, $5,000+ is recommended so the fixed lot keeps the max monthly drawdown near 28% — below $5K the broker's 0.01 minimum lot pushes it past 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Ready?", title: "Free. Forever. No strings.", body: "Open a GTC account via Dralvo, download the EA, get the license — all free. You only pay the broker spread, like any normal account.", primary: "Start now", secondary: "Ask on Telegram", guarantee: "Cancel anytime · No commitment · Install support" },
  },

  vi: {
    navHome: "Trang chủ",
    heroEyebrow: "Dralvo Capital · Miễn phí trọn đời",
    heroSub1: "EA thích ứng cho XAUUSD — miễn phí khi mở tài khoản qua đối tác GTC của Dralvo.",
    heroSub2: "3 lớp bảo vệ vốn. Trailing stop thông minh. 1,105 lệnh kiểm chứng trong 6 tháng.",
    acc: { usd: { name: "Tài khoản USD", desc: "Spread thấp, khối lượng chuẩn" }, cent: { name: "Tài khoản Cent", desc: "Vốn nhỏ, rủi ro thấp" } },
    s1: { eyebrow: "Bước 1", title: "Mở tài khoản GTC qua Dralvo", sub: "Chọn loại tài khoản, mở qua link đối tác. GTC là broker độc quyền của Dralvo.", copy: "Copy", copied: "Đã copy", open: "Mở tài khoản" },
    s2: { eyebrow: "Bước 2", titleDefault: "Xác nhận tài khoản MT5", titleVerified: "Tài khoản đã xác nhận", sub: "Nhập số tài khoản MT5 bạn vừa mở qua link IB Dralvo.", placeholder: "Số tài khoản MT5", verify: "Xác nhận", verifying: "Đang kiểm tra...", errFail: "Xác nhận thất bại. Vui lòng thử lại.", errConn: "Lỗi kết nối. Vui lòng thử lại.", selectFirst: "Chọn loại tài khoản ở bước 1 trước.", account: "Tài khoản", via: "Đã xác nhận qua IB Dralvo." },
    s3: { eyebrow: "Bước 3", title: "Tải EA & cài đặt", sub: "Hoàn thành bước 1 & 2 để mở khóa tải về.", locked: "Hoàn thành Bước 1 & 2 để mở khóa tải về.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Hướng dẫn", guideDesc: "HTML · mở bằng trình duyệt", installHeading: "Hướng dẫn cài đặt" },
    install: [
      { title: "Chép EA vào MT5", body: "Đóng MT5. <strong>File → Open Data Folder</strong>. Chép <code>Dralvo TiGold.ex5</code> vào <code>MQL5\\Experts\\</code>. Mở lại MT5." },
      { title: "Kéo EA lên chart", body: "<strong>Navigator → Expert Advisors</strong>, chuột phải <strong>Refresh</strong>. Kéo <strong>Dralvo TiGold</strong> thả vào chart <strong>XAUUSD M1</strong>. Tab Common: tick <strong>Allow Algo Trading</strong>." },
      { title: "Nạp file .set", body: "Tab <strong>Inputs → Load</strong>, chọn <strong>Dralvo tigold v1.set</strong>. Kiểm tra <code>InpFixedLot</code> phù hợp vốn. Bấm <strong>OK</strong>." },
      { title: "Bật Auto Trading", body: "Bật nút <strong>Algo Trading</strong> trên thanh công cụ (biểu tượng sáng xanh). Góc trái chart hiện bảng <strong>DRALVO TiGOLD</strong> — EA đang chạy." },
    ],
    s4: { eyebrow: "Bước 4", title: "Kích hoạt license", sub: "EA cần license key để chạy. Nhận key miễn phí qua Telegram.", cardHeading: "Nhắn Telegram để nhận license key", l1: "Mở Telegram, tìm", l2: 'Gửi: <strong>"TiGold license [số tài khoản MT5]"</strong>', l3: "Admin kiểm tra tài khoản thuộc IB Dralvo", l4: "Nhận license key → nhập vào EA → bắt đầu giao dịch", open: "Mở Telegram", note: "License miễn phí vĩnh viễn cho tài khoản đăng ký qua IB Dralvo. Mỗi license gắn với 1 số tài khoản MT5." },
    bt: { eyebrow: "Hiệu suất đã kiểm chứng", title: "Số liệu nói thay lời.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · 100% tick thật · vốn $10K, reset hàng tháng.", profile: "Hồ sơ rủi ro — TiGold v3.0", kNet: "Lợi nhuận ròng", kPf: "Profit Factor", kWin: "Tỷ lệ thắng", kDd: "Drawdown tối đa", sTrades: "Tổng lệnh", sWin: "Tỷ lệ thắng", sAvgWin: "Lãi TB", sAvgLoss: "Lỗ TB", sRr: "Lãi/Lỗ", sStreak: "Chuỗi T/B", final: "Số dư cuối kỳ" },
    faqEyebrow: "Hỏi đáp",
    faqTitle: "Mọi điều bạn cần biết.",
    faq: [
      ["EA có cần VPS không?", "Khuyến nghị dùng VPS để EA chạy 24/5 không gián đoạn. Có thể thuê VPS giá rẻ (~$5-10/tháng) và cài MT5 lên đó."],
      ["Dùng được tài khoản demo không?", "Được. Mở tài khoản demo qua link IB Dralvo, xác nhận số tài khoản demo — bạn vẫn nhận được EA miễn phí."],
      ["Sao PF chỉ ~1.18 mà vẫn lãi?", "Tỷ lệ thắng cao ~76% cộng khóa lãi theo ngày: đạt +6%/ngày là dừng, nên các lợi thế nhỏ tích lại qua ~1,105 lệnh trong 6 tháng. Mỗi tháng test trên vốn $10K mới (reset hàng tháng) để giữ drawdown dưới 30%. Edge mỏng — cần kiểm chứng lại khi có thêm dữ liệu tick thật."],
      ["Cần bao nhiêu vốn để bắt đầu?", "Tài khoản Cent có thể test từ ~$10–50. Tài khoản USD: khuyến nghị từ $5,000 trở lên để lot cố định giữ drawdown tháng cao nhất ~28% — dưới $5K, lot tối thiểu 0.01 đẩy DD vượt 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Sẵn sàng?", title: "Miễn phí. Vĩnh viễn. Không bắt buộc.", body: "Mở tài khoản GTC qua Dralvo, tải EA, nhận license — tất cả miễn phí. Bạn chỉ trả spread cho broker như mọi tài khoản bình thường.", primary: "Bắt đầu ngay", secondary: "Hỏi trên Telegram", guarantee: "Hủy bất cứ lúc nào · Không ràng buộc · Hỗ trợ cài đặt" },
  },

  zh: {
    navHome: "首页",
    heroEyebrow: "Dralvo Capital · 终身免费",
    heroSub1: "面向 XAUUSD 的自适应 EA——通过 Dralvo 的 GTC 合作伙伴开户即免费。",
    heroSub2: "3 层本金保护。智能移动止损。6 个月内 1,105 笔已验证交易。",
    acc: { usd: { name: "USD 账户", desc: "低点差，标准手数" }, cent: { name: "Cent 账户", desc: "小资金，低风险" } },
    s1: { eyebrow: "第 1 步", title: "通过 Dralvo 开设 GTC 账户", sub: "选择账户类型，通过合作伙伴链接开户。GTC 是 Dralvo 的独家经纪商。", copy: "复制", copied: "已复制", open: "开设账户" },
    s2: { eyebrow: "第 2 步", titleDefault: "验证你的 MT5 账户", titleVerified: "账户已验证", sub: "输入你刚通过 Dralvo IB 链接开设的 MT5 账户号。", placeholder: "MT5 账户号", verify: "验证", verifying: "检查中...", errFail: "验证失败，请重试。", errConn: "连接错误，请重试。", selectFirst: "请先在第 1 步选择账户类型。", account: "账户", via: "已通过 Dralvo IB 验证。" },
    s3: { eyebrow: "第 3 步", title: "下载并安装 EA", sub: "完成第 1、2 步以解锁下载。", locked: "完成第 1、2 步以解锁下载。", ea: "EA (.ex5)", preset: "预设 (.set)", guide: "指南", guideDesc: "HTML · 用浏览器打开", installHeading: "安装指南" },
    install: [
      { title: "把 EA 复制到 MT5", body: "关闭 MT5。<strong>File → Open Data Folder</strong>。把 <code>Dralvo TiGold.ex5</code> 复制到 <code>MQL5\\Experts\\</code>。重新打开 MT5。" },
      { title: "把 EA 拖到图表上", body: "<strong>Navigator → Expert Advisors</strong>，右键 <strong>Refresh</strong>。把 <strong>Dralvo TiGold</strong> 拖到 <strong>XAUUSD M1</strong> 图表。Common 选项卡：勾选 <strong>Allow Algo Trading</strong>。" },
      { title: "加载 .set 文件", body: "<strong>Inputs → Load</strong> 选项卡，选择 <strong>Dralvo tigold v1.set</strong>。检查 <code>InpFixedLot</code> 是否匹配你的资金。点击 <strong>OK</strong>。" },
      { title: "启用自动交易", body: "打开工具栏上的 <strong>Algo Trading</strong> 按钮（变为绿色）。图表左上角出现 <strong>DRALVO TiGOLD</strong> 面板——EA 正在运行。" },
    ],
    s4: { eyebrow: "第 4 步", title: "激活许可证", sub: "EA 需要许可证密钥才能运行。通过 Telegram 免费获取。", cardHeading: "在 Telegram 联系我们获取许可证密钥", l1: "打开 Telegram，搜索", l2: '发送：<strong>"TiGold license [MT5 账户号]"</strong>', l3: "管理员核实账户属于 Dralvo IB", l4: "获取许可证密钥 → 输入到 EA → 开始交易", open: "打开 Telegram", note: "通过 Dralvo IB 注册的账户可获终身免费许可证。每个许可证绑定一个 MT5 账户号。" },
    bt: { eyebrow: "已验证业绩", title: "数字会说话。", sub: "GTC MT5 策略测试器 · XAUUSD M1 · 01/2026–06/2026 · 100% 真实 tick · 1 万美元，每月重置。", profile: "风险概况 — TiGold v3.0", kNet: "净利润", kPf: "盈利因子", kWin: "胜率", kDd: "最大回撤", sTrades: "总交易", sWin: "胜率", sAvgWin: "平均盈利", sAvgLoss: "平均亏损", sRr: "盈/亏", sStreak: "连胜/连亏", final: "期末余额" },
    faqEyebrow: "常见问题",
    faqTitle: "你需要知道的一切。",
    faq: [
      ["EA 需要 VPS 吗？", "建议使用 VPS 让 EA 24/5 不间断运行。一台便宜的 VPS（约 $5–10/月）装上 MT5 即可。"],
      ["可以用模拟账户吗？", "可以。通过 Dralvo IB 链接开设模拟账户，确认模拟账户号——你仍可免费获得 EA。"],
      ["盈利因子只有 ~1.18，为何还能盈利？", "约 76% 的高胜率加上每日锁利：当日 +6% 即停手，所以微小优势在 6 个月约 1,105 笔交易中累积。每月用全新的 1 万美元测试（每月重置）以将回撤控制在 30% 以内。优势很薄——随着真实 tick 数据增多需重新验证。"],
      ["开始需要多少资金？", "Cent 账户可从约 $10–50 测试。USD 账户：建议 $5,000 起，让固定手数把月最大回撤控制在 ~28%——低于 $5K 时 0.01 最小手会把回撤推到 40% 以上。"],
    ] as [string, string][],
    cta: { eyebrow: "准备好了吗？", title: "免费。永久。无附加条件。", body: "通过 Dralvo 开设 GTC 账户、下载 EA、获取许可证——全部免费。你只需像普通账户一样支付经纪商点差。", primary: "立即开始", secondary: "在 Telegram 询问", guarantee: "随时取消 · 无约束 · 安装支持" },
  },

  es: {
    navHome: "Inicio",
    heroEyebrow: "Dralvo Capital · Gratis de por vida",
    heroSub1: "Un EA adaptativo para XAUUSD — gratis al abrir una cuenta con el socio GTC de Dralvo.",
    heroSub2: "Protección de capital en 3 capas. Trailing stop inteligente. 1,105 operaciones verificadas en 6 meses.",
    acc: { usd: { name: "Cuenta USD", desc: "Spread bajo, volumen estándar" }, cent: { name: "Cuenta Cent", desc: "Capital pequeño, bajo riesgo" } },
    s1: { eyebrow: "Paso 1", title: "Abre una cuenta GTC vía Dralvo", sub: "Elige un tipo de cuenta y ábrela por el enlace del socio. GTC es el bróker exclusivo de Dralvo.", copy: "Copiar", copied: "Copiado", open: "Abrir cuenta" },
    s2: { eyebrow: "Paso 2", titleDefault: "Verifica tu cuenta MT5", titleVerified: "Cuenta verificada", sub: "Introduce el número de cuenta MT5 que acabas de abrir vía el enlace IB de Dralvo.", placeholder: "Número de cuenta MT5", verify: "Verificar", verifying: "Comprobando...", errFail: "La verificación falló. Inténtalo de nuevo.", errConn: "Error de conexión. Inténtalo de nuevo.", selectFirst: "Elige primero un tipo de cuenta en el paso 1.", account: "Cuenta", via: "Verificado vía Dralvo IB." },
    s3: { eyebrow: "Paso 3", title: "Descarga e instala el EA", sub: "Completa los pasos 1 y 2 para desbloquear la descarga.", locked: "Completa los pasos 1 y 2 para desbloquear la descarga.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Guía", guideDesc: "HTML · ábrela en un navegador", installHeading: "Guía de instalación" },
    install: [
      { title: "Copia el EA en MT5", body: "Cierra MT5. <strong>File → Open Data Folder</strong>. Copia <code>Dralvo TiGold.ex5</code> en <code>MQL5\\Experts\\</code>. Vuelve a abrir MT5." },
      { title: "Arrastra el EA a un gráfico", body: "<strong>Navigator → Expert Advisors</strong>, clic derecho <strong>Refresh</strong>. Arrastra <strong>Dralvo TiGold</strong> a un gráfico <strong>XAUUSD M1</strong>. Pestaña Common: marca <strong>Allow Algo Trading</strong>." },
      { title: "Carga el archivo .set", body: "Pestaña <strong>Inputs → Load</strong>, elige <strong>Dralvo tigold v1.set</strong>. Verifica que <code>InpFixedLot</code> se ajuste a tu capital. Clic en <strong>OK</strong>." },
      { title: "Activa el Auto Trading", body: "Activa el botón <strong>Algo Trading</strong> en la barra (se pone verde). El panel <strong>DRALVO TiGOLD</strong> aparece arriba a la izquierda — el EA está funcionando." },
    ],
    s4: { eyebrow: "Paso 4", title: "Activa la licencia", sub: "El EA necesita una clave de licencia para funcionar. Consíguela gratis por Telegram.", cardHeading: "Escríbenos por Telegram para una clave de licencia", l1: "Abre Telegram y busca", l2: 'Envía: <strong>"TiGold license [número de cuenta MT5]"</strong>', l3: "El admin verifica que la cuenta pertenece a Dralvo IB", l4: "Recibe la clave → introdúcela en el EA → empieza a operar", open: "Abrir Telegram", note: "Licencia gratuita de por vida para cuentas registradas vía Dralvo IB. Cada licencia se vincula a un número de cuenta MT5." },
    bt: { eyebrow: "Rendimiento verificado", title: "Los números hablan.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · ticks 100% reales · $10K, reinicio mensual.", profile: "Perfil de riesgo — TiGold v3.0", kNet: "Beneficio neto", kPf: "Profit Factor", kWin: "Tasa de acierto", kDd: "Drawdown máx.", sTrades: "Operaciones", sWin: "Tasa de acierto", sAvgWin: "Gan. media", sAvgLoss: "Pérd. media", sRr: "Gan/Pérd", sStreak: "Racha G/P", final: "Saldo final" },
    faqEyebrow: "Preguntas frecuentes",
    faqTitle: "Todo lo que necesitas saber.",
    faq: [
      ["¿El EA necesita un VPS?", "Se recomienda un VPS para que el EA funcione 24/5 sin interrupciones. Un VPS barato (~$5–10/mes) con MT5 instalado es suficiente."],
      ["¿Puedo usar una cuenta demo?", "Sí. Abre una cuenta demo vía el enlace IB de Dralvo, confirma el número de cuenta demo — igual recibes el EA gratis."],
      ["El PF es solo ~1,18 — ¿cómo es rentable?", "Una alta tasa de acierto (~76%) más un bloqueo de ganancia diaria: asegura +6% al día y se detiene, así las pequeñas ventajas se acumulan en ~1.105 operaciones durante 6 meses. Cada mes se prueba con $10K nuevos (reinicio mensual) para mantener el drawdown bajo 30%. La ventaja es fina — revalida a medida que crezcan los datos de ticks reales."],
      ["¿Cuánto capital necesito para empezar?", "En cuenta Cent puedes probar desde ~$10–50. En cuenta USD se recomiendan $5.000+ para que el lote fijo mantenga el drawdown mensual máximo cerca del 28% — por debajo de $5K el lote mínimo de 0,01 lo lleva por encima del 40%."],
    ] as [string, string][],
    cta: { eyebrow: "¿Listo?", title: "Gratis. Para siempre. Sin ataduras.", body: "Abre una cuenta GTC vía Dralvo, descarga el EA, obtén la licencia — todo gratis. Solo pagas el spread del bróker, como en cualquier cuenta normal.", primary: "Empezar ahora", secondary: "Preguntar por Telegram", guarantee: "Cancela cuando quieras · Sin compromiso · Soporte de instalación" },
  },

  hi: {
    navHome: "होम",
    heroEyebrow: "Dralvo Capital · आजीवन मुफ़्त",
    heroSub1: "XAUUSD के लिए एक अनुकूली EA — Dralvo के GTC साझेदार के ज़रिए खाता खोलने पर मुफ़्त।",
    heroSub2: "3-परत पूँजी सुरक्षा। स्मार्ट ट्रेलिंग स्टॉप। 6 महीनों में 1,105 सत्यापित ट्रेड।",
    acc: { usd: { name: "USD खाता", desc: "कम स्प्रेड, मानक वॉल्यूम" }, cent: { name: "Cent खाता", desc: "छोटी पूँजी, कम जोखिम" } },
    s1: { eyebrow: "चरण 1", title: "Dralvo के ज़रिए GTC खाता खोलें", sub: "खाता प्रकार चुनें और साझेदार लिंक से खोलें। GTC, Dralvo का विशेष ब्रोकर है।", copy: "कॉपी", copied: "कॉपी हो गया", open: "खाता खोलें" },
    s2: { eyebrow: "चरण 2", titleDefault: "अपना MT5 खाता सत्यापित करें", titleVerified: "खाता सत्यापित", sub: "वह MT5 खाता नंबर दर्ज करें जो आपने अभी Dralvo IB लिंक से खोला।", placeholder: "MT5 खाता नंबर", verify: "सत्यापित करें", verifying: "जाँच हो रही है...", errFail: "सत्यापन विफल। कृपया फिर प्रयास करें।", errConn: "कनेक्शन त्रुटि। कृपया फिर प्रयास करें।", selectFirst: "पहले चरण 1 में खाता प्रकार चुनें।", account: "खाता", via: "Dralvo IB के ज़रिए सत्यापित।" },
    s3: { eyebrow: "चरण 3", title: "EA डाउनलोड व इंस्टॉल करें", sub: "डाउनलोड अनलॉक करने के लिए चरण 1 व 2 पूरे करें।", locked: "डाउनलोड अनलॉक करने के लिए चरण 1 व 2 पूरे करें।", ea: "EA (.ex5)", preset: "प्रीसेट (.set)", guide: "गाइड", guideDesc: "HTML · ब्राउज़र में खोलें", installHeading: "इंस्टॉल गाइड" },
    install: [
      { title: "EA को MT5 में कॉपी करें", body: "MT5 बंद करें। <strong>File → Open Data Folder</strong>। <code>Dralvo TiGold.ex5</code> को <code>MQL5\\Experts\\</code> में कॉपी करें। MT5 फिर खोलें।" },
      { title: "EA को चार्ट पर खींचें", body: "<strong>Navigator → Expert Advisors</strong>, राइट-क्लिक <strong>Refresh</strong>। <strong>Dralvo TiGold</strong> को <strong>XAUUSD M1</strong> चार्ट पर खींचें। Common टैब: <strong>Allow Algo Trading</strong> टिक करें।" },
      { title: ".set फ़ाइल लोड करें", body: "<strong>Inputs → Load</strong> टैब, <strong>Dralvo tigold v1.set</strong> चुनें। जाँचें कि <code>InpFixedLot</code> आपकी पूँजी के अनुरूप है। <strong>OK</strong> दबाएँ।" },
      { title: "Auto Trading चालू करें", body: "टूलबार में <strong>Algo Trading</strong> बटन चालू करें (हरा हो जाता है)। चार्ट के ऊपर-बाएँ <strong>DRALVO TiGOLD</strong> पैनल दिखता है — EA चल रहा है।" },
    ],
    s4: { eyebrow: "चरण 4", title: "लाइसेंस सक्रिय करें", sub: "EA को चलने के लिए लाइसेंस की ज़रूरत है। इसे Telegram से मुफ़्त पाएँ।", cardHeading: "लाइसेंस की के लिए हमें Telegram पर संदेश भेजें", l1: "Telegram खोलें और खोजें", l2: 'भेजें: <strong>"TiGold license [MT5 खाता नंबर]"</strong>', l3: "एडमिन जाँचता है कि खाता Dralvo IB का है", l4: "लाइसेंस की पाएँ → EA में दर्ज करें → ट्रेडिंग शुरू करें", open: "Telegram खोलें", note: "Dralvo IB के ज़रिए पंजीकृत खातों के लिए आजीवन मुफ़्त लाइसेंस। हर लाइसेंस एक MT5 खाता नंबर से जुड़ा होता है।" },
    bt: { eyebrow: "सत्यापित प्रदर्शन", title: "आँकड़े बोलते हैं।", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · 100% असली tick · $10K, मासिक रीसेट।", profile: "जोखिम प्रोफ़ाइल — TiGold v3.0", kNet: "शुद्ध लाभ", kPf: "प्रॉफिट फैक्टर", kWin: "जीत दर", kDd: "अधिकतम ड्रॉडाउन", sTrades: "कुल ट्रेड", sWin: "जीत दर", sAvgWin: "औसत लाभ", sAvgLoss: "औसत हानि", sRr: "लाभ/हानि", sStreak: "लगातार जीत/हार", final: "अंतिम बैलेंस" },
    faqEyebrow: "सामान्य प्रश्न",
    faqTitle: "वह सब जो आपको जानना चाहिए।",
    faq: [
      ["क्या EA को VPS चाहिए?", "EA को 24/5 निर्बाध चलाने के लिए VPS की सलाह दी जाती है। एक सस्ता VPS (~$5–10/माह) जिसमें MT5 इंस्टॉल हो, पर्याप्त है।"],
      ["क्या मैं डेमो खाता उपयोग कर सकता हूँ?", "हाँ। Dralvo IB लिंक से डेमो खाता खोलें, डेमो खाता नंबर पुष्टि करें — आपको फिर भी EA मुफ़्त मिलता है।"],
      ["PF सिर्फ़ ~1.18 है — फिर लाभदायक कैसे?", "लगभग 76% की ऊँची जीत दर के साथ दैनिक लाभ-लॉक: दिन में +6% पाकर रुक जाता है, इसलिए छोटे फ़ायदे 6 महीनों में ~1,105 ट्रेड में जमा होते हैं। ड्रॉडाउन 30% से नीचे रखने के लिए हर महीने नए $10K पर टेस्ट (मासिक रीसेट)। बढ़त पतली है — अधिक असली tick डेटा के साथ फिर से सत्यापित करें।"],
      ["शुरू करने के लिए कितनी पूँजी चाहिए?", "Cent खाते पर ~$10–50 से टेस्ट कर सकते हैं। USD खाते पर $5,000+ की सलाह ताकि फ़िक्स्ड लॉट मासिक अधिकतम ड्रॉडाउन ~28% रखे — $5K से कम पर 0.01 न्यूनतम लॉट इसे 40% के पार ले जाता है।"],
    ] as [string, string][],
    cta: { eyebrow: "तैयार?", title: "मुफ़्त। हमेशा के लिए। कोई शर्त नहीं।", body: "Dralvo के ज़रिए GTC खाता खोलें, EA डाउनलोड करें, लाइसेंस पाएँ — सब मुफ़्त। आप किसी भी सामान्य खाते की तरह बस ब्रोकर स्प्रेड चुकाते हैं।", primary: "अभी शुरू करें", secondary: "Telegram पर पूछें", guarantee: "कभी भी रद्द करें · कोई बाध्यता नहीं · इंस्टॉल सहायता" },
  },

  id: {
    navHome: "Beranda",
    heroEyebrow: "Dralvo Capital · Gratis seumur hidup",
    heroSub1: "EA adaptif untuk XAUUSD — gratis saat membuka akun melalui mitra GTC Dralvo.",
    heroSub2: "Proteksi modal 3 lapis. Trailing stop pintar. 1,105 transaksi teruji dalam 6 bulan.",
    acc: { usd: { name: "Akun USD", desc: "Spread rendah, volume standar" }, cent: { name: "Akun Cent", desc: "Modal kecil, risiko rendah" } },
    s1: { eyebrow: "Langkah 1", title: "Buka akun GTC via Dralvo", sub: "Pilih jenis akun dan buka lewat tautan mitra. GTC adalah broker eksklusif Dralvo.", copy: "Salin", copied: "Tersalin", open: "Buka akun" },
    s2: { eyebrow: "Langkah 2", titleDefault: "Verifikasi akun MT5 Anda", titleVerified: "Akun terverifikasi", sub: "Masukkan nomor akun MT5 yang baru Anda buka via tautan IB Dralvo.", placeholder: "Nomor akun MT5", verify: "Verifikasi", verifying: "Memeriksa...", errFail: "Verifikasi gagal. Silakan coba lagi.", errConn: "Kesalahan koneksi. Silakan coba lagi.", selectFirst: "Pilih jenis akun di langkah 1 dulu.", account: "Akun", via: "Terverifikasi via Dralvo IB." },
    s3: { eyebrow: "Langkah 3", title: "Unduh & pasang EA", sub: "Selesaikan langkah 1 & 2 untuk membuka unduhan.", locked: "Selesaikan langkah 1 & 2 untuk membuka unduhan.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Panduan", guideDesc: "HTML · buka di browser", installHeading: "Panduan instalasi" },
    install: [
      { title: "Salin EA ke MT5", body: "Tutup MT5. <strong>File → Open Data Folder</strong>. Salin <code>Dralvo TiGold.ex5</code> ke <code>MQL5\\Experts\\</code>. Buka MT5 lagi." },
      { title: "Seret EA ke grafik", body: "<strong>Navigator → Expert Advisors</strong>, klik kanan <strong>Refresh</strong>. Seret <strong>Dralvo TiGold</strong> ke grafik <strong>XAUUSD M1</strong>. Tab Common: centang <strong>Allow Algo Trading</strong>." },
      { title: "Muat file .set", body: "Tab <strong>Inputs → Load</strong>, pilih <strong>Dralvo tigold v1.set</strong>. Pastikan <code>InpFixedLot</code> sesuai modal Anda. Klik <strong>OK</strong>." },
      { title: "Aktifkan Auto Trading", body: "Aktifkan tombol <strong>Algo Trading</strong> di toolbar (menyala hijau). Panel <strong>DRALVO TiGOLD</strong> muncul di kiri atas — EA sedang berjalan." },
    ],
    s4: { eyebrow: "Langkah 4", title: "Aktifkan lisensi", sub: "EA butuh kunci lisensi untuk berjalan. Dapatkan gratis via Telegram.", cardHeading: "Hubungi kami di Telegram untuk kunci lisensi", l1: "Buka Telegram dan cari", l2: 'Kirim: <strong>"TiGold license [nomor akun MT5]"</strong>', l3: "Admin memeriksa akun milik Dralvo IB", l4: "Dapatkan kunci lisensi → masukkan ke EA → mulai trading", open: "Buka Telegram", note: "Lisensi gratis seumur hidup untuk akun terdaftar via Dralvo IB. Setiap lisensi terikat ke satu nomor akun MT5." },
    bt: { eyebrow: "Performa terverifikasi", title: "Angka yang berbicara.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · tick 100% nyata · $10K, reset bulanan.", profile: "Profil risiko — TiGold v3.0", kNet: "Laba bersih", kPf: "Profit Factor", kWin: "Win rate", kDd: "Drawdown maks", sTrades: "Total transaksi", sWin: "Win rate", sAvgWin: "Profit rata2", sAvgLoss: "Rugi rata2", sRr: "Untung/Rugi", sStreak: "Beruntun M/K", final: "Saldo akhir" },
    faqEyebrow: "Tanya jawab",
    faqTitle: "Semua yang perlu Anda tahu.",
    faq: [
      ["Apakah EA butuh VPS?", "VPS disarankan agar EA berjalan 24/5 tanpa terputus. VPS murah (~$5–10/bulan) dengan MT5 terpasang sudah cukup."],
      ["Bisakah pakai akun demo?", "Bisa. Buka akun demo via tautan IB Dralvo, konfirmasi nomor akun demo — Anda tetap dapat EA gratis."],
      ["PF hanya ~1,18 — kok bisa untung?", "Win rate tinggi ~76% plus kunci profit harian: mengamankan +6% per hari lalu berhenti, jadi keunggulan kecil terakumulasi pada ~1.105 transaksi selama 6 bulan. Setiap bulan diuji pada $10K baru (reset bulanan) agar drawdown di bawah 30%. Edge-nya tipis — validasi ulang seiring bertambahnya data tick nyata."],
      ["Berapa modal untuk mulai?", "Akun Cent bisa uji dari ~$10–50. Akun USD disarankan $5.000+ agar lot tetap menjaga drawdown bulanan maksimum sekitar 28% — di bawah $5K, lot minimum 0,01 mendorongnya di atas 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Siap?", title: "Gratis. Selamanya. Tanpa ikatan.", body: "Buka akun GTC via Dralvo, unduh EA, dapatkan lisensi — semua gratis. Anda hanya membayar spread broker, seperti akun biasa.", primary: "Mulai sekarang", secondary: "Tanya di Telegram", guarantee: "Batalkan kapan saja · Tanpa komitmen · Bantuan instalasi" },
  },

  ru: {
    navHome: "Главная",
    heroEyebrow: "Dralvo Capital · Бесплатно навсегда",
    heroSub1: "Адаптивный EA для XAUUSD — бесплатно при открытии счёта через партнёра Dralvo GTC.",
    heroSub2: "3 слоя защиты капитала. Умный трейлинг-стоп. 1,105 проверенных сделок за 6 месяцев.",
    acc: { usd: { name: "Счёт USD", desc: "Низкий спред, стандартный объём" }, cent: { name: "Счёт Cent", desc: "Малый капитал, низкий риск" } },
    s1: { eyebrow: "Шаг 1", title: "Откройте счёт GTC через Dralvo", sub: "Выберите тип счёта и откройте по партнёрской ссылке. GTC — эксклюзивный брокер Dralvo.", copy: "Копировать", copied: "Скопировано", open: "Открыть счёт" },
    s2: { eyebrow: "Шаг 2", titleDefault: "Подтвердите счёт MT5", titleVerified: "Счёт подтверждён", sub: "Введите номер счёта MT5, который вы только что открыли по ссылке Dralvo IB.", placeholder: "Номер счёта MT5", verify: "Подтвердить", verifying: "Проверка...", errFail: "Подтверждение не удалось. Попробуйте снова.", errConn: "Ошибка соединения. Попробуйте снова.", selectFirst: "Сначала выберите тип счёта на шаге 1.", account: "Счёт", via: "Подтверждено через Dralvo IB." },
    s3: { eyebrow: "Шаг 3", title: "Скачайте и установите EA", sub: "Завершите шаги 1 и 2, чтобы открыть загрузку.", locked: "Завершите шаги 1 и 2, чтобы открыть загрузку.", ea: "EA (.ex5)", preset: "Пресет (.set)", guide: "Гид", guideDesc: "HTML · откройте в браузере", installHeading: "Руководство по установке" },
    install: [
      { title: "Скопируйте EA в MT5", body: "Закройте MT5. <strong>File → Open Data Folder</strong>. Скопируйте <code>Dralvo TiGold.ex5</code> в <code>MQL5\\Experts\\</code>. Снова откройте MT5." },
      { title: "Перетащите EA на график", body: "<strong>Navigator → Expert Advisors</strong>, правый клик <strong>Refresh</strong>. Перетащите <strong>Dralvo TiGold</strong> на график <strong>XAUUSD M1</strong>. Вкладка Common: отметьте <strong>Allow Algo Trading</strong>." },
      { title: "Загрузите файл .set", body: "Вкладка <strong>Inputs → Load</strong>, выберите <strong>Dralvo tigold v1.set</strong>. Проверьте, что <code>InpFixedLot</code> подходит вашему капиталу. Нажмите <strong>OK</strong>." },
      { title: "Включите Auto Trading", body: "Включите кнопку <strong>Algo Trading</strong> на панели (загорается зелёным). Панель <strong>DRALVO TiGOLD</strong> появляется вверху слева — EA работает." },
    ],
    s4: { eyebrow: "Шаг 4", title: "Активируйте лицензию", sub: "Для работы EA нужен лицензионный ключ. Получите его бесплатно в Telegram.", cardHeading: "Напишите нам в Telegram за лицензионным ключом", l1: "Откройте Telegram и найдите", l2: 'Отправьте: <strong>"TiGold license [номер счёта MT5]"</strong>', l3: "Админ проверяет, что счёт принадлежит Dralvo IB", l4: "Получите ключ → введите в EA → начните торговлю", open: "Открыть Telegram", note: "Бесплатная пожизненная лицензия для счетов, зарегистрированных через Dralvo IB. Каждая лицензия привязана к одному номеру счёта MT5." },
    bt: { eyebrow: "Проверенные результаты", title: "Цифры говорят сами.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · 100% реальные тики · $10K, ежемесячный сброс.", profile: "Профиль риска — TiGold v3.0", kNet: "Чистая прибыль", kPf: "Profit Factor", kWin: "Винрейт", kDd: "Макс. просадка", sTrades: "Всего сделок", sWin: "Винрейт", sAvgWin: "Сред. прибыль", sAvgLoss: "Сред. убыток", sRr: "Приб/Убыт", sStreak: "Серия П/У", final: "Итоговый баланс" },
    faqEyebrow: "Вопросы и ответы",
    faqTitle: "Всё, что нужно знать.",
    faq: [
      ["Нужен ли EA VPS?", "Рекомендуется VPS, чтобы EA работал 24/5 без перерывов. Достаточно дешёвого VPS (~$5–10/мес) с установленным MT5."],
      ["Можно использовать демо-счёт?", "Да. Откройте демо-счёт по ссылке Dralvo IB, подтвердите номер демо-счёта — вы всё равно получите EA бесплатно."],
      ["PF всего ~1,18 — как он прибыльный?", "Высокий винрейт ~76% плюс дневная фиксация прибыли: набирает +6% за день и останавливается, поэтому небольшие преимущества накапливаются на ~1 105 сделках за 6 месяцев. Каждый месяц тестируется на новых $10K (ежемесячный сброс), чтобы держать просадку ниже 30%. Преимущество тонкое — перепроверяйте по мере роста реальных тиковых данных."],
      ["Сколько капитала нужно для старта?", "На центовом счёте можно тестировать от ~$10–50. На долларовом рекомендуется от $5 000, чтобы фиксированный лот держал макс. месячную просадку около 28% — ниже $5K минимальный лот 0,01 уводит её выше 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Готовы?", title: "Бесплатно. Навсегда. Без условий.", body: "Откройте счёт GTC через Dralvo, скачайте EA, получите лицензию — всё бесплатно. Вы платите только спред брокеру, как на любом обычном счёте.", primary: "Начать сейчас", secondary: "Спросить в Telegram", guarantee: "Отмена в любой момент · Без обязательств · Поддержка установки" },
  },

  "pt-BR": {
    navHome: "Início",
    heroEyebrow: "Dralvo Capital · Grátis para sempre",
    heroSub1: "Um EA adaptativo para XAUUSD — grátis ao abrir uma conta pelo parceiro GTC da Dralvo.",
    heroSub2: "Proteção de capital em 3 camadas. Trailing stop inteligente. 1.105 operações verificadas em 6 meses.",
    acc: { usd: { name: "Conta USD", desc: "Spread baixo, volume padrão" }, cent: { name: "Conta Cent", desc: "Capital pequeno, baixo risco" } },
    s1: { eyebrow: "Passo 1", title: "Abra uma conta GTC via Dralvo", sub: "Escolha um tipo de conta e abra pelo link do parceiro. A GTC é a corretora exclusiva da Dralvo.", copy: "Copiar", copied: "Copiado", open: "Abrir conta" },
    s2: { eyebrow: "Passo 2", titleDefault: "Verifique sua conta MT5", titleVerified: "Conta verificada", sub: "Informe o número da conta MT5 que você acabou de abrir pelo link IB da Dralvo.", placeholder: "Número da conta MT5", verify: "Verificar", verifying: "Verificando...", errFail: "Falha na verificação. Tente novamente.", errConn: "Erro de conexão. Tente novamente.", selectFirst: "Escolha um tipo de conta no passo 1 primeiro.", account: "Conta", via: "Verificado via Dralvo IB." },
    s3: { eyebrow: "Passo 3", title: "Baixe e instale o EA", sub: "Conclua os passos 1 e 2 para desbloquear o download.", locked: "Conclua os passos 1 e 2 para desbloquear o download.", ea: "EA (.ex5)", preset: "Preset (.set)", guide: "Guia", guideDesc: "HTML · abra no navegador", installHeading: "Guia de instalação" },
    install: [
      { title: "Copie o EA para o MT5", body: "Feche o MT5. <strong>File → Open Data Folder</strong>. Copie <code>Dralvo TiGold.ex5</code> para <code>MQL5\\Experts\\</code>. Reabra o MT5." },
      { title: "Arraste o EA para um gráfico", body: "<strong>Navigator → Expert Advisors</strong>, clique direito <strong>Refresh</strong>. Arraste <strong>Dralvo TiGold</strong> para um gráfico <strong>XAUUSD M1</strong>. Aba Common: marque <strong>Allow Algo Trading</strong>." },
      { title: "Carregue o arquivo .set", body: "Aba <strong>Inputs → Load</strong>, escolha <strong>Dralvo tigold v1.set</strong>. Verifique se <code>InpFixedLot</code> combina com seu capital. Clique em <strong>OK</strong>." },
      { title: "Ative o Auto Trading", body: "Ligue o botão <strong>Algo Trading</strong> na barra (fica verde). O painel <strong>DRALVO TiGOLD</strong> aparece no canto superior esquerdo — o EA está rodando." },
    ],
    s4: { eyebrow: "Passo 4", title: "Ative a licença", sub: "O EA precisa de uma chave de licença para rodar. Pegue uma grátis pelo Telegram.", cardHeading: "Fale conosco no Telegram para uma chave de licença", l1: "Abra o Telegram e procure", l2: 'Envie: <strong>"TiGold license [número da conta MT5]"</strong>', l3: "O admin verifica que a conta pertence à Dralvo IB", l4: "Receba a chave → insira no EA → comece a operar", open: "Abrir Telegram", note: "Licença grátis vitalícia para contas registradas via Dralvo IB. Cada licença é vinculada a um número de conta MT5." },
    bt: { eyebrow: "Desempenho verificado", title: "Os números falam.", sub: "GTC MT5 Strategy Tester · XAUUSD M1 · 01/2026–06/2026 · ticks 100% reais · $10K, reinício mensal.", profile: "Perfil de risco — TiGold v3.0", kNet: "Lucro líquido", kPf: "Profit Factor", kWin: "Taxa de acerto", kDd: "Drawdown máx.", sTrades: "Operações", sWin: "Taxa de acerto", sAvgWin: "Ganho médio", sAvgLoss: "Perda média", sRr: "Ganho/Perda", sStreak: "Sequência G/P", final: "Saldo final" },
    faqEyebrow: "Perguntas frequentes",
    faqTitle: "Tudo o que você precisa saber.",
    faq: [
      ["O EA precisa de VPS?", "Recomenda-se um VPS para o EA rodar 24/5 sem interrupção. Um VPS barato (~$5–10/mês) com MT5 instalado é suficiente."],
      ["Posso usar conta demo?", "Sim. Abra uma conta demo pelo link IB da Dralvo, confirme o número da conta demo — você ainda recebe o EA grátis."],
      ["O PF é só ~1,18 — como é lucrativo?", "Uma alta taxa de acerto (~76%) mais trava de lucro diária: garante +6% no dia e para, então pequenas vantagens se acumulam em ~1.105 operações ao longo de 6 meses. Cada mês é testado com $10K novos (reinício mensal) para manter o drawdown abaixo de 30%. A vantagem é fina — revalide conforme mais dados de ticks reais surgem."],
      ["Quanto capital preciso para começar?", "Em conta Cent dá para testar a partir de ~$10–50. Em conta USD, recomenda-se $5.000+ para que o lote fixo mantenha o drawdown mensal máximo perto de 28% — abaixo de $5K, o lote mínimo de 0,01 o leva acima de 40%."],
    ] as [string, string][],
    cta: { eyebrow: "Pronto?", title: "Grátis. Para sempre. Sem amarras.", body: "Abra uma conta GTC via Dralvo, baixe o EA, pegue a licença — tudo grátis. Você só paga o spread da corretora, como em qualquer conta normal.", primary: "Começar agora", secondary: "Perguntar no Telegram", guarantee: "Cancele quando quiser · Sem compromisso · Suporte de instalação" },
  },
});
