/**
 * Affiliate program copy — vi + en authored; other locales fall back to en.
 */
import { withLocaleFallback } from "@/lib/i18n";

export const AFFILIATE_COPY = withLocaleFallback({
  "pt-BR": {
    navLabel: "Afiliado",

    hero: {
      eyebrow: "Programa de Afiliados",
      title: "Ganhe 30% de comissão recorrente.",
      subtitle:
        "Indique a Dralvo para a sua comunidade. Cada cliente que você trouxer rende 30% a cada mês em que ele permanecer. Sem limites, sem truques.",
      cta: "Torne-se um Afiliado",
      loginCta: "Já é parceiro? Ver dashboard",
    },

    how: {
      eyebrow: "Como funciona",
      title: "3 passos simples.",
      steps: [
        { title: "Cadastre-se", body: "Crie uma conta Dralvo e candidate-se como afiliado. Aprovamos em até 24h." },
        { title: "Compartilhe seu link", body: "Receba seu link de indicação exclusivo. Compartilhe no seu blog, YouTube, Telegram ou Facebook." },
        { title: "Ganhe", body: "Os clientes compram pelo seu link → você ganha 30% todos os meses. Saque ao atingir US$ 50." },
      ],
    },

    commission: {
      eyebrow: "Comissão",
      title: "30% por toda a vida do cliente.",
      subtitle: "A cada mês em que o cliente renova → você recebe 30%. Quanto mais tempo ele permanecer, mais você ganha.",
      items: [
        { label: "Taxa de comissão", value: "30%" },
        { label: "Janela do cookie", value: "30 dias" },
        { label: "Saque mínimo", value: "US$ 50" },
        { label: "Modelo", value: "Recorrente" },
      ],
    },

    why: {
      eyebrow: "Por que ser nosso parceiro",
      title: "Produto real. Números reais.",
      items: [
        { title: "Produto verificado", body: "EAs testados em backtest com 10 anos de dados reais. Não são bots fantasmas — os clientes veem resultados reais." },
        { title: "Ganhos transparentes", body: "Dashboard em tempo real: cliques, conversões, ganhos. Sem atrasos, sem números ocultos." },
        { title: "Suporte completo", body: "Grupo dedicado no Telegram para afiliados. Suporte de conteúdo, banners e landing page." },
        { title: "Pagamentos em dia", body: "Saque via transferência bancária. Solicite o pagamento assim que atingir US$ 50." },
      ],
    },

    cta: {
      eyebrow: "Pronto?",
      title: "Comece a ganhar hoje.",
      body: "Sem capital, sem experiência necessária. Basta ter uma comunidade interessada em trading de ouro.",
      button: "Candidate-se agora",
    },

    faq: {
      eyebrow: "FAQ",
      title: "Tudo o que você precisa saber.",
      items: [
        ["Quem pode se tornar afiliado?", "Qualquer pessoa — traders, blogueiros, YouTubers, administradores de grupos no Telegram/Facebook. Se você tem um público interessado em forex/ouro, está dentro."],
        ["Como eu ganho comissão?", "Um cliente compra o Dralvo VIP pelo seu link → você ganha 30% do pedido. A cada mês em que ele renova → você ganha mais 30%."],
        ["Quando posso sacar?", "Assim que seus ganhos pendentes atingirem US$ 50. Solicite o pagamento — transferimos em até 3 dias úteis."],
        ["Há limite de indicações?", "Não. Mais clientes = mais comissão. Sem tetos."],
        ["Quanto tempo dura o cookie?", "30 dias. Se um cliente clicar no seu link e comprar dentro de 30 dias, você recebe a comissão."],
      ],
    },

    dashboard: {
      title: "Dashboard de Afiliado",
      statusPending: "Aguardando aprovação",
      statusActive: "Ativo",
      statusSuspended: "Suspenso",
      statusRejected: "Recusado",
      referralLink: "Seu link de indicação",
      copyLink: "Copiar",
      copied: "Copiado!",
      stats: {
        clicks: "Cliques",
        conversions: "Conversões",
        conversionRate: "Taxa de conversão",
        pendingEarnings: "Ganhos pendentes",
        totalEarned: "Total ganho",
        paidOut: "Pago",
        available: "Disponível",
      },
      commissions: {
        title: "Histórico de comissões",
        empty: "Nenhuma comissão ainda.",
        amount: "Valor",
        source: "Pedido",
        status: "Status",
        date: "Data",
        statusPending: "Pendente",
        statusPaid: "Pago",
        statusCancelled: "Cancelado",
        statusRefunded: "Reembolsado",
      },
      requestPayout: "Solicitar pagamento",
      requesting: "Enviando...",
      payoutRequested: "Pagamento solicitado",
      payoutPendingDetail: "O administrador está processando. Transferiremos em até 3 dias úteis.",
      payoutSuccess: "Solicitação de pagamento enviada!",
      payoutError: "Não foi possível enviar a solicitação. Tente novamente mais tarde.",
      payoutMethodTitle: "Dados de pagamento",
      payoutRegionVn: "Banco VN",
      payoutRegionUsdt: "USDT (internacional)",
      payoutBank: "Banco / Carteira",
      payoutBankPlaceholder: "Selecione o banco",
      payoutAccount: "Número da conta",
      payoutHolder: "Titular da conta",
      payoutNetwork: "Rede",
      payoutAddress: "Endereço da carteira USDT",
      payoutSubmittedTo: "Pago para",
      payoutErrInvalidBank: "Escolha um banco válido.",
      payoutErrInvalidAccount: "O número da conta deve ter de 6 a 19 dígitos.",
      payoutErrInvalidHolder: "Informe o nome do titular da conta.",
      payoutErrInvalidNetwork: "Escolha uma rede USDT.",
      payoutErrInvalidAddress: "O endereço da carteira é inválido para a rede escolhida.",
      notEligible: "É preciso US$ 50 para sacar",
      notAffiliateTitle: "Você ainda não é afiliado",
      notAffiliateBody: "Candidate-se agora para receber seu link de indicação e começar a ganhar 30% de comissão dos clientes que você indicar.",
      applyNow: "Candidate-se agora",
      applying: "Candidatando...",
      howTitle: "Como funciona",
      howSteps: [
        "Candidate-se — o administrador aprova em até 24h",
        "Receba seu link de indicação exclusivo",
        "Compartilhe seu link — ganhe 30% de comissão todos os meses",
      ],
      pendingNotice: "Sua conta de afiliado está aguardando aprovação.",
      pendingNoticeDetail: "O administrador vai revisar e aprovar em até 24h. Você já pode ver seu link de indicação.",
    },

    admin: {
      title: "Admin — Afiliados",
      settings: "Configurações",
      affiliates: "Afiliados",
      commissions: "Comissões",
      payouts: "Solicitações de pagamento",
      saveSettings: "Salvar configurações",
      settingsSaved: "Salvo!",
      commissionRate: "Taxa de comissão (%)",
      cookieDays: "Cookie (dias)",
      minPayout: "Saque mínimo ($)",
      programActive: "Programa ativo",
      approve: "Aprovar",
      reject: "Recusar",
      suspend: "Suspender",
      markPaid: "Marcar como pago",
      noCommissions: "Nenhuma comissão pendente.",
      paidSuccess: "Marcado como pago.",
      noPayouts: "Nenhuma solicitação de pagamento ainda.",
      payoutReject: "Recusar",
      payoutPay: "Marcar como pago",
      payoutStatusRequested: "Solicitado",
      payoutStatusApproved: "Aprovado",
      payoutStatusPaid: "Pago",
      payoutStatusRejected: "Recusado",
    },
  },
  es: {
    navLabel: "Afiliados",

    hero: {
      eyebrow: "Programa de Afiliados",
      title: "Gana 30% de comisión recurrente.",
      subtitle:
        "Recomienda Dralvo a tu comunidad. Cada cliente que traigas te genera 30% cada mes que permanezca. Sin límites, sin trucos.",
      cta: "Conviértete en Afiliado",
      loginCta: "¿Ya eres socio? Ver panel",
    },

    how: {
      eyebrow: "Cómo funciona",
      title: "3 pasos sencillos.",
      steps: [
        { title: "Regístrate", body: "Crea una cuenta de Dralvo y postula como afiliado. Aprobamos en un plazo de 24 h." },
        { title: "Comparte tu enlace", body: "Obtén tu enlace de referido único. Compártelo en tu blog, YouTube, Telegram o Facebook." },
        { title: "Gana", body: "Los clientes compran a través de tu enlace → ganas 30% cada mes. Retira al alcanzar $50." },
      ],
    },

    commission: {
      eyebrow: "Comisión",
      title: "30% durante toda la vida del cliente.",
      subtitle: "Cada mes que el cliente renueva → recibes 30%. Cuanto más tiempo permanezca, más ganas.",
      items: [
        { label: "Tasa de comisión", value: "30%" },
        { label: "Ventana de cookie", value: "30 días" },
        { label: "Pago mínimo", value: "$50" },
        { label: "Modelo", value: "Recurring" },
      ],
    },

    why: {
      eyebrow: "Por qué asociarte con nosotros",
      title: "Producto real. Cifras reales.",
      items: [
        { title: "Producto verificado", body: "EA sometidos a backtest con 10 años de datos reales. No son bots fantasma: los clientes ven resultados reales." },
        { title: "Ganancias transparentes", body: "Panel en tiempo real: clics, conversiones, ganancias. Sin demoras, sin cifras ocultas." },
        { title: "Soporte completo", body: "Grupo de Telegram exclusivo para afiliados. Apoyo con contenido, banners y landing page." },
        { title: "Pagos puntuales", body: "Retira mediante transferencia bancaria. Solicita el pago en cuanto alcances $50." },
      ],
    },

    cta: {
      eyebrow: "¿Listo?",
      title: "Empieza a ganar hoy.",
      body: "Sin capital ni experiencia. Solo necesitas una comunidad interesada en el trading de oro.",
      button: "Postula ahora",
    },

    faq: {
      eyebrow: "FAQ",
      title: "Todo lo que necesitas saber.",
      items: [
        ["¿Quién puede ser afiliado?", "Cualquier persona: traders, blogueros, youtubers, administradores de grupos de Telegram/Facebook. Si tienes una audiencia interesada en forex/oro, estás dentro."],
        ["¿Cómo gano comisión?", "Un cliente compra Dralvo VIP a través de tu enlace → ganas 30% del pedido. Cada mes que renueva → ganas otro 30%."],
        ["¿Cuándo puedo retirar?", "En cuanto tus ganancias pendientes alcancen $50. Solicita el pago y transferimos en un plazo de 3 días hábiles."],
        ["¿Hay un límite de referidos?", "No. Más clientes = más comisión. Sin topes."],
        ["¿Cuánto dura la cookie?", "30 días. Si un cliente hace clic en tu enlace y compra dentro de los 30 días, recibes la comisión."],
      ],
    },

    dashboard: {
      title: "Panel de Afiliado",
      statusPending: "Pendiente de aprobación",
      statusActive: "Activo",
      statusSuspended: "Suspendido",
      statusRejected: "Rechazado",
      referralLink: "Tu enlace de referido",
      copyLink: "Copiar",
      copied: "¡Copiado!",
      stats: {
        clicks: "Clics",
        conversions: "Conversiones",
        conversionRate: "Tasa de conversión",
        pendingEarnings: "Ganancias pendientes",
        totalEarned: "Total ganado",
        paidOut: "Pagado",
        available: "Disponible",
      },
      commissions: {
        title: "Historial de comisiones",
        empty: "Aún no hay comisiones.",
        amount: "Monto",
        source: "Pedido",
        status: "Estado",
        date: "Fecha",
        statusPending: "Pendiente",
        statusPaid: "Pagado",
        statusCancelled: "Cancelado",
        statusRefunded: "Reembolsado",
      },
      requestPayout: "Solicitar pago",
      requesting: "Enviando...",
      payoutRequested: "Pago solicitado",
      payoutPendingDetail: "El administrador lo está procesando. Transferiremos en un plazo de 3 días hábiles.",
      payoutSuccess: "¡Solicitud de pago enviada!",
      payoutError: "No se pudo enviar la solicitud. Inténtalo de nuevo más tarde.",
      payoutMethodTitle: "Datos de pago",
      payoutRegionVn: "Banco VN",
      payoutRegionUsdt: "USDT (internacional)",
      payoutBank: "Banco / Billetera",
      payoutBankPlaceholder: "Seleccionar banco",
      payoutAccount: "Número de cuenta",
      payoutHolder: "Titular de la cuenta",
      payoutNetwork: "Red",
      payoutAddress: "Dirección de billetera USDT",
      payoutSubmittedTo: "Pagado a",
      payoutErrInvalidBank: "Elige un banco válido.",
      payoutErrInvalidAccount: "El número de cuenta debe tener entre 6 y 19 dígitos.",
      payoutErrInvalidHolder: "Ingresa el nombre del titular de la cuenta.",
      payoutErrInvalidNetwork: "Elige una red USDT.",
      payoutErrInvalidAddress: "La dirección de billetera no es válida para la red elegida.",
      notEligible: "Necesitas $50 para retirar",
      notAffiliateTitle: "Aún no eres afiliado",
      notAffiliateBody: "Postula ahora para obtener tu enlace de referido y empezar a ganar 30% de comisión de los clientes que recomiendes.",
      applyNow: "Postula ahora",
      applying: "Postulando...",
      howTitle: "Cómo funciona",
      howSteps: [
        "Postula: el administrador aprueba en un plazo de 24 h",
        "Obtén tu enlace de referido único",
        "Comparte tu enlace: gana 30% de comisión cada mes",
      ],
      pendingNotice: "Tu cuenta de afiliado está pendiente de aprobación.",
      pendingNoticeDetail: "El administrador la revisará y aprobará en un plazo de 24 h. Aún puedes ver tu enlace de referido.",
    },

    admin: {
      title: "Admin — Afiliados",
      settings: "Configuración",
      affiliates: "Afiliados",
      commissions: "Comisiones",
      payouts: "Solicitudes de pago",
      saveSettings: "Guardar configuración",
      settingsSaved: "¡Guardado!",
      commissionRate: "Tasa de comisión (%)",
      cookieDays: "Cookie (días)",
      minPayout: "Pago mínimo ($)",
      programActive: "Programa activo",
      approve: "Aprobar",
      reject: "Rechazar",
      suspend: "Suspender",
      markPaid: "Marcar como pagado",
      noCommissions: "No hay comisiones pendientes.",
      paidSuccess: "Marcado como pagado.",
      noPayouts: "Aún no hay solicitudes de pago.",
      payoutReject: "Rechazar",
      payoutPay: "Marcar como pagado",
      payoutStatusRequested: "Solicitado",
      payoutStatusApproved: "Aprobado",
      payoutStatusPaid: "Pagado",
      payoutStatusRejected: "Rechazado",
    },
  },
  id: {
    navLabel: "Affiliate",

    hero: {
      eyebrow: "Program Affiliate",
      title: "Dapatkan komisi berulang 30%.",
      subtitle:
        "Rekomendasikan Dralvo kepada komunitas Anda. Setiap pelanggan yang Anda bawa memberi Anda komisi 30% setiap bulan selama mereka berlangganan. Tanpa batas, tanpa akal-akalan.",
      cta: "Menjadi Affiliate",
      loginCta: "Sudah menjadi mitra? Lihat dashboard",
    },

    how: {
      eyebrow: "Cara kerjanya",
      title: "3 langkah sederhana.",
      steps: [
        { title: "Daftar", body: "Buat akun Dralvo dan ajukan sebagai affiliate. Kami akan menyetujui dalam 24 jam." },
        { title: "Bagikan tautan Anda", body: "Dapatkan tautan referral unik Anda. Bagikan di blog, YouTube, Telegram, atau Facebook Anda." },
        { title: "Dapatkan komisi", body: "Pelanggan membeli melalui tautan Anda → Anda memperoleh 30% setiap bulan. Tarik dana saat mencapai $50." },
      ],
    },

    commission: {
      eyebrow: "Komisi",
      title: "30% sepanjang masa pelanggan.",
      subtitle: "Setiap bulan pelanggan memperpanjang → Anda memperoleh 30%. Semakin lama mereka berlangganan, semakin besar penghasilan Anda.",
      items: [
        { label: "Tarif komisi", value: "30%" },
        { label: "Masa cookie", value: "30 hari" },
        { label: "Pencairan minimum", value: "$50" },
        { label: "Model", value: "Berulang" },
      ],
    },

    why: {
      eyebrow: "Mengapa bermitra dengan kami",
      title: "Produk nyata. Angka nyata.",
      items: [
        { title: "Produk terverifikasi", body: "EA di-backtest pada data riil selama 10 tahun. Bukan bot palsu — pelanggan melihat hasil yang nyata." },
        { title: "Penghasilan transparan", body: "Dashboard real-time: klik, konversi, penghasilan. Tanpa penundaan, tanpa angka tersembunyi." },
        { title: "Dukungan penuh", body: "Grup Telegram khusus untuk affiliate. Dukungan konten, banner, dan landing page." },
        { title: "Pencairan tepat waktu", body: "Tarik dana melalui transfer bank. Ajukan pencairan setelah mencapai $50." },
      ],
    },

    cta: {
      eyebrow: "Siap?",
      title: "Mulai hasilkan penghasilan hari ini.",
      body: "Tanpa modal, tanpa pengalaman yang diperlukan. Cukup komunitas yang tertarik pada trading emas.",
      button: "Ajukan sekarang",
    },

    faq: {
      eyebrow: "FAQ",
      title: "Semua yang perlu Anda ketahui.",
      items: [
        ["Siapa yang dapat menjadi affiliate?", "Siapa saja — trader, blogger, YouTuber, admin grup Telegram/Facebook. Jika Anda memiliki audiens yang tertarik pada forex/emas, Anda memenuhi syarat."],
        ["Bagaimana cara saya memperoleh komisi?", "Seorang pelanggan membeli Dralvo VIP melalui tautan Anda → Anda memperoleh 30% dari nilai pesanan. Setiap bulan mereka memperpanjang → Anda memperoleh 30% lagi."],
        ["Kapan saya dapat menarik dana?", "Setelah penghasilan tertunda Anda mencapai $50. Ajukan pencairan — kami mentransfer dalam 3 hari kerja."],
        ["Apakah ada batasan jumlah referral?", "Tidak. Semakin banyak pelanggan = semakin banyak komisi. Tanpa batas."],
        ["Berapa lama cookie berlaku?", "30 hari. Jika pelanggan mengklik tautan Anda dan melakukan pembelian dalam 30 hari, Anda memperoleh komisi."],
      ],
    },

    dashboard: {
      title: "Affiliate Dashboard",
      statusPending: "Menunggu persetujuan",
      statusActive: "Aktif",
      statusSuspended: "Ditangguhkan",
      statusRejected: "Ditolak",
      referralLink: "Tautan referral Anda",
      copyLink: "Salin",
      copied: "Tersalin!",
      stats: {
        clicks: "Klik",
        conversions: "Konversi",
        conversionRate: "Tingkat konversi",
        pendingEarnings: "Penghasilan tertunda",
        totalEarned: "Total penghasilan",
        paidOut: "Telah dibayarkan",
        available: "Tersedia",
      },
      commissions: {
        title: "Riwayat komisi",
        empty: "Belum ada komisi.",
        amount: "Jumlah",
        source: "Pesanan",
        status: "Status",
        date: "Tanggal",
        statusPending: "Tertunda",
        statusPaid: "Dibayar",
        statusCancelled: "Dibatalkan",
        statusRefunded: "Dikembalikan",
      },
      requestPayout: "Ajukan pencairan",
      requesting: "Mengirim...",
      payoutRequested: "Pencairan diajukan",
      payoutPendingDetail: "Admin sedang memprosesnya. Kami akan mentransfer dalam 3 hari kerja.",
      payoutSuccess: "Permintaan pencairan terkirim!",
      payoutError: "Tidak dapat mengirim permintaan. Coba lagi nanti.",
      payoutMethodTitle: "Detail pencairan",
      payoutRegionVn: "Bank VN",
      payoutRegionUsdt: "USDT (internasional)",
      payoutBank: "Bank / Dompet",
      payoutBankPlaceholder: "Pilih bank",
      payoutAccount: "Nomor rekening",
      payoutHolder: "Pemilik rekening",
      payoutNetwork: "Jaringan",
      payoutAddress: "Alamat dompet USDT",
      payoutSubmittedTo: "Dibayarkan ke",
      payoutErrInvalidBank: "Pilih bank yang valid.",
      payoutErrInvalidAccount: "Nomor rekening harus terdiri dari 6–19 digit.",
      payoutErrInvalidHolder: "Masukkan nama pemilik rekening.",
      payoutErrInvalidNetwork: "Pilih jaringan USDT.",
      payoutErrInvalidAddress: "Alamat dompet tidak valid untuk jaringan yang dipilih.",
      notEligible: "Perlu $50 untuk menarik dana",
      notAffiliateTitle: "Anda belum menjadi affiliate",
      notAffiliateBody: "Ajukan sekarang untuk mendapatkan tautan referral Anda dan mulai memperoleh komisi 30% dari pelanggan yang Anda rekomendasikan.",
      applyNow: "Ajukan sekarang",
      applying: "Mengajukan...",
      howTitle: "Cara kerjanya",
      howSteps: [
        "Ajukan — admin menyetujui dalam 24 jam",
        "Dapatkan tautan referral unik Anda",
        "Bagikan tautan Anda — dapatkan komisi 30% setiap bulan",
      ],
      pendingNotice: "Akun affiliate Anda sedang menunggu persetujuan.",
      pendingNoticeDetail: "Admin akan meninjau dan menyetujui dalam 24 jam. Anda tetap dapat melihat tautan referral Anda.",
    },

    admin: {
      title: "Admin — Affiliate",
      settings: "Pengaturan",
      affiliates: "Affiliates",
      commissions: "Komisi",
      payouts: "Permintaan pencairan",
      saveSettings: "Simpan pengaturan",
      settingsSaved: "Tersimpan!",
      commissionRate: "Tarif komisi (%)",
      cookieDays: "Cookie (hari)",
      minPayout: "Pencairan minimum ($)",
      programActive: "Program aktif",
      approve: "Setujui",
      reject: "Tolak",
      suspend: "Tangguhkan",
      markPaid: "Tandai dibayar",
      noCommissions: "Tidak ada komisi tertunda.",
      paidSuccess: "Ditandai sebagai dibayar.",
      noPayouts: "Belum ada permintaan pencairan.",
      payoutReject: "Tolak",
      payoutPay: "Tandai dibayar",
      payoutStatusRequested: "Diajukan",
      payoutStatusApproved: "Disetujui",
      payoutStatusPaid: "Dibayar",
      payoutStatusRejected: "Ditolak",
    },
  },
  ar: {
    navLabel: "Affiliate",

    hero: {
      eyebrow: "برنامج Affiliate",
      title: "احصل على عمولة متكررة بنسبة 30%.",
      subtitle:
        "قدّم Dralvo إلى مجتمعك. كل عميل تجلبه يمنحك عمولة 30% كل شهر يبقى فيه مشتركاً. بلا حدود، وبلا تعقيد.",
      cta: "كن Affiliate",
      loginCta: "شريك بالفعل؟ اعرض لوحة التحكم",
    },

    how: {
      eyebrow: "كيف يعمل",
      title: "3 خطوات بسيطة.",
      steps: [
        { title: "سجّل", body: "أنشئ حساباً في Dralvo وقدّم طلبك كـ affiliate. سنوافق خلال 24 ساعة." },
        { title: "شارك رابطك", body: "احصل على رابط الإحالة الخاص بك. شاركه على مدونتك أو YouTube أو Telegram أو Facebook." },
        { title: "اكسب", body: "يشتري العملاء عبر رابطك ← تكسب 30% كل شهر. اسحب أرباحك عند بلوغ 50 USD." },
      ],
    },

    commission: {
      eyebrow: "العمولة",
      title: "30% طوال بقاء العميل.",
      subtitle: "كل شهر يجدّد فيه العميل اشتراكه ← تحصل على 30%. كلما طالت مدة بقائه، زادت أرباحك.",
      items: [
        { label: "نسبة العمولة", value: "30%" },
        { label: "مدة الكوكي", value: "30 يوماً" },
        { label: "الحد الأدنى للسحب", value: "$50" },
        { label: "النموذج", value: "متكرر" },
      ],
    },

    why: {
      eyebrow: "لماذا الشراكة معنا",
      title: "منتج حقيقي. أرقام حقيقية.",
      items: [
        { title: "منتج موثّق", body: "تم اختبار الـ EA على بيانات حقيقية لمدة 10 سنوات. ليست روبوتات وهمية — العملاء يرون نتائج حقيقية." },
        { title: "أرباح شفافة", body: "لوحة تحكم فورية: النقرات والتحويلات والأرباح. بلا تأخير، وبلا أرقام مخفية." },
        { title: "دعم كامل", body: "مجموعة Telegram مخصصة للـ affiliates. دعم في المحتوى واللافتات وصفحات الهبوط." },
        { title: "مدفوعات في موعدها", body: "اسحب عبر التحويل البنكي. اطلب الدفع بمجرد بلوغك 50 USD." },
      ],
    },

    cta: {
      eyebrow: "مستعد؟",
      title: "ابدأ الكسب اليوم.",
      body: "لا حاجة إلى رأس مال أو خبرة. يكفي أن يكون لديك مجتمع مهتم بتداول الذهب.",
      button: "قدّم الآن",
    },

    faq: {
      eyebrow: "FAQ",
      title: "كل ما تحتاج إلى معرفته.",
      items: [
        ["من يمكنه أن يصبح affiliate؟", "أي شخص — المتداولون والمدونون وصنّاع محتوى YouTube ومشرفو مجموعات Telegram/Facebook. إن كان لديك جمهور مهتم بالفوركس/الذهب، فأنت مؤهل."],
        ["كيف أكسب العمولة؟", "يشتري العميل Dralvo VIP عبر رابطك ← تكسب 30% من قيمة الطلب. وفي كل شهر يجدّد فيه اشتراكه ← تكسب 30% إضافية."],
        ["متى يمكنني السحب؟", "بمجرد بلوغ أرباحك المعلّقة 50 USD. اطلب الدفع — ونحوّل المبلغ خلال 3 أيام عمل."],
        ["هل هناك حد لعدد الإحالات؟", "لا. المزيد من العملاء = المزيد من العمولة. بلا حدود قصوى."],
        ["كم تدوم مدة الكوكي؟", "30 يوماً. إذا نقر العميل على رابطك واشترى خلال 30 يوماً، تحصل على العمولة."],
      ],
    },

    dashboard: {
      title: "لوحة تحكم Affiliate",
      statusPending: "بانتظار الموافقة",
      statusActive: "نشط",
      statusSuspended: "موقوف",
      statusRejected: "مرفوض",
      referralLink: "رابط الإحالة الخاص بك",
      copyLink: "نسخ",
      copied: "تم النسخ!",
      stats: {
        clicks: "النقرات",
        conversions: "التحويلات",
        conversionRate: "معدل التحويل",
        pendingEarnings: "الأرباح المعلّقة",
        totalEarned: "إجمالي المكتسب",
        paidOut: "المدفوع",
        available: "المتاح",
      },
      commissions: {
        title: "سجل العمولات",
        empty: "لا توجد عمولات بعد.",
        amount: "المبلغ",
        source: "الطلب",
        status: "الحالة",
        date: "التاريخ",
        statusPending: "معلّق",
        statusPaid: "مدفوع",
        statusCancelled: "ملغى",
        statusRefunded: "مسترد",
      },
      requestPayout: "اطلب الدفع",
      requesting: "جارٍ الإرسال...",
      payoutRequested: "تم طلب الدفع",
      payoutPendingDetail: "الإدارة تعالج الطلب. سنحوّل المبلغ خلال 3 أيام عمل.",
      payoutSuccess: "تم إرسال طلب الدفع!",
      payoutError: "تعذّر إرسال الطلب. حاول مرة أخرى لاحقاً.",
      payoutMethodTitle: "بيانات الدفع",
      payoutRegionVn: "بنك VN",
      payoutRegionUsdt: "USDT (دولي)",
      payoutBank: "البنك / المحفظة",
      payoutBankPlaceholder: "اختر البنك",
      payoutAccount: "رقم الحساب",
      payoutHolder: "صاحب الحساب",
      payoutNetwork: "الشبكة",
      payoutAddress: "عنوان محفظة USDT",
      payoutSubmittedTo: "الدفع إلى",
      payoutErrInvalidBank: "اختر بنكاً صالحاً.",
      payoutErrInvalidAccount: "يجب أن يتكون رقم الحساب من 6–19 رقماً.",
      payoutErrInvalidHolder: "أدخل اسم صاحب الحساب.",
      payoutErrInvalidNetwork: "اختر شبكة USDT.",
      payoutErrInvalidAddress: "عنوان المحفظة غير صالح للشبكة المختارة.",
      notEligible: "تحتاج إلى 50 USD للسحب",
      notAffiliateTitle: "لست affiliate بعد",
      notAffiliateBody: "قدّم الآن للحصول على رابط الإحالة الخاص بك والبدء في كسب عمولة 30% من العملاء الذين تحيلهم.",
      applyNow: "قدّم الآن",
      applying: "جارٍ التقديم...",
      howTitle: "كيف يعمل",
      howSteps: [
        "قدّم — توافق الإدارة خلال 24 ساعة",
        "احصل على رابط الإحالة الخاص بك",
        "شارك رابطك — واكسب عمولة 30% كل شهر",
      ],
      pendingNotice: "حساب الـ affiliate الخاص بك بانتظار الموافقة.",
      pendingNoticeDetail: "ستراجع الإدارة الطلب وتوافق عليه خلال 24 ساعة. لا يزال بإمكانك عرض رابط الإحالة الخاص بك.",
    },

    admin: {
      title: "الإدارة — Affiliate",
      settings: "الإعدادات",
      affiliates: "Affiliates",
      commissions: "العمولات",
      payouts: "طلبات الدفع",
      saveSettings: "حفظ الإعدادات",
      settingsSaved: "تم الحفظ!",
      commissionRate: "نسبة العمولة (%)",
      cookieDays: "الكوكي (أيام)",
      minPayout: "الحد الأدنى للدفع ($)",
      programActive: "البرنامج نشط",
      approve: "موافقة",
      reject: "رفض",
      suspend: "إيقاف",
      markPaid: "وضع علامة مدفوع",
      noCommissions: "لا توجد عمولات معلّقة.",
      paidSuccess: "تم وضع علامة مدفوع.",
      noPayouts: "لا توجد طلبات دفع بعد.",
      payoutReject: "رفض",
      payoutPay: "وضع علامة مدفوع",
      payoutStatusRequested: "مطلوب",
      payoutStatusApproved: "موافَق عليه",
      payoutStatusPaid: "مدفوع",
      payoutStatusRejected: "مرفوض",
    },
  },
  vi: {
    // Nav / footer
    navLabel: "Affiliate",

    // Public landing page
    hero: {
      eyebrow: "Affiliate Program",
      title: "Kiếm 30% hoa hồng định kỳ.",
      subtitle:
        "Giới thiệu Dralvo đến cộng đồng của bạn. Mỗi khách hàng bạn mang đến — bạn nhận 30% hoa hồng mỗi tháng họ tiếp tục sử dụng. Không giới hạn, không vòng vo.",
      cta: "Đăng ký làm Affiliate",
      loginCta: "Đã có tài khoản? Xem dashboard",
    },

    // How it works
    how: {
      eyebrow: "Cách hoạt động",
      title: "3 bước đơn giản.",
      steps: [
        { title: "Đăng ký", body: "Tạo tài khoản Dralvo, đăng ký affiliate. Chúng tôi sẽ duyệt trong 24h." },
        { title: "Chia sẻ link", body: "Nhận link referral riêng. Chia sẻ lên blog, YouTube, Telegram, Facebook." },
        { title: "Nhận hoa hồng", body: "Khách mua qua link của bạn → bạn nhận 30% mỗi tháng. Rút khi đạt $50." },
      ],
    },

    // Commission structure
    commission: {
      eyebrow: "Hoa hồng",
      title: "30% trọn đời khách hàng.",
      subtitle: "Mỗi tháng khách renew → bạn nhận 30%. Khách dùng càng lâu, bạn càng lời.",
      items: [
        { label: "Tỷ lệ hoa hồng", value: "30%" },
        { label: "Cookie", value: "30 ngày" },
        { label: "Rút tối thiểu", value: "$50" },
        { label: "Mô hình", value: "Recurring" },
      ],
    },

    // Why partner
    why: {
      eyebrow: "Tại sao làm affiliate",
      title: "Sản phẩm thật, số thật.",
      items: [
        { title: "Sản phẩm đã kiểm chứng", body: "EA được backtest trên dữ liệu thật 10 năm. Không phải 'bot ma' — khách hàng thấy được kết quả." },
        { title: "Hoa hồng minh bạch", body: "Dashboard real-time: click, conversion, earnings. Không delay, không ẩn số." },
        { title: "Hỗ trợ tận răng", body: "Có Telegram riêng cho affiliate. Hỗ trợ content, banner, landing page." },
        { title: "Thanh toán đúng hạn", body: "Rút qua chuyển khoản. Tự request payout khi đạt $50." },
      ],
    },

    // CTA
    cta: {
      eyebrow: "Sẵn sàng?",
      title: "Bắt đầu kiếm hoa hồng hôm nay.",
      body: "Không cần vốn, không cần kinh nghiệm. Chỉ cần bạn có cộng đồng quan tâm đến trading vàng.",
      button: "Đăng ký ngay",
    },

    // FAQ
    faq: {
      eyebrow: "FAQ",
      title: "Mọi thứ bạn cần biết.",
      items: [
        ["Ai có thể làm affiliate?", "Bất kỳ ai — trader, blogger, YouTuber, admin group Telegram/Facebook. Chỉ cần bạn có cộng đồng quan tâm đến forex/vàng."],
        ["Làm sao để nhận hoa hồng?", "Khách mua Dralvo VIP qua link của bạn → bạn nhận 30% giá trị đơn hàng. Mỗi tháng khách renew → bạn nhận tiếp 30%."],
        ["Khi nào được rút tiền?", "Khi tổng hoa hồng pending đạt $50. Bạn request payout, chúng tôi chuyển khoản trong 3 ngày làm việc."],
        ["Có giới hạn số lượng khách không?", "Không. Càng nhiều khách, càng nhiều hoa hồng. Không có cap."],
        ["Cookie kéo dài bao lâu?", "30 ngày. Nếu khách click link của bạn và mua trong 30 ngày, bạn nhận hoa hồng."],
      ],
    },

    // Affiliate dashboard
    dashboard: {
      title: "Affiliate Dashboard",
      statusPending: "Đang chờ duyệt",
      statusActive: "Đang hoạt động",
      statusSuspended: "Tạm khóa",
      statusRejected: "Từ chối",
      referralLink: "Link referral",
      copyLink: "Copy",
      copied: "Đã copy!",
      stats: {
        clicks: "Click",
        conversions: "Conversion",
        conversionRate: "Tỷ lệ chuyển đổi",
        pendingEarnings: "Hoa hồng chờ",
        totalEarned: "Tổng đã kiếm",
        paidOut: "Đã thanh toán",
        available: "Có thể rút",
      },
      commissions: {
        title: "Lịch sử hoa hồng",
        empty: "Chưa có hoa hồng nào.",
        amount: "Số tiền",
        source: "Đơn gốc",
        status: "Trạng thái",
        date: "Ngày",
        statusPending: "Đang chờ",
        statusPaid: "Đã trả",
        statusCancelled: "Đã hủy",
        statusRefunded: "Hoàn tiền",
      },
      requestPayout: "Request rút tiền",
      requesting: "Đang gửi...",
      payoutRequested: "Đã gửi yêu cầu rút tiền",
      payoutPendingDetail: "Admin đang xử lý. Chúng tôi sẽ chuyển khoản trong 3 ngày làm việc.",
      payoutSuccess: "Đã gửi yêu cầu rút tiền!",
      payoutError: "Không gửi được yêu cầu. Thử lại sau.",
      payoutMethodTitle: "Thông tin nhận tiền",
      payoutRegionVn: "Ngân hàng VN",
      payoutRegionUsdt: "USDT (quốc tế)",
      payoutBank: "Ngân hàng / Ví",
      payoutBankPlaceholder: "Chọn ngân hàng",
      payoutAccount: "Số tài khoản",
      payoutHolder: "Chủ tài khoản",
      payoutNetwork: "Mạng (network)",
      payoutAddress: "Địa chỉ ví USDT",
      payoutSubmittedTo: "Nhận qua",
      payoutErrInvalidBank: "Chọn ngân hàng hợp lệ.",
      payoutErrInvalidAccount: "Số tài khoản phải là 6–19 chữ số.",
      payoutErrInvalidHolder: "Nhập tên chủ tài khoản.",
      payoutErrInvalidNetwork: "Chọn mạng USDT.",
      payoutErrInvalidAddress: "Địa chỉ ví không hợp lệ cho mạng đã chọn.",
      notEligible: "Cần đủ $50 để rút",
      notAffiliateTitle: "Bạn chưa là affiliate",
      notAffiliateBody: "Đăng ký ngay để nhận link referral và bắt đầu kiếm 30% hoa hồng từ khách hàng bạn giới thiệu.",
      applyNow: "Đăng ký ngay",
      applying: "Đang đăng ký...",
      howTitle: "Cách hoạt động",
      howSteps: [
        "Đăng ký — admin sẽ duyệt trong 24h",
        "Nhận link referral riêng của bạn",
        "Chia sẻ link — kiếm 30% hoa hồng mỗi tháng",
      ],
      pendingNotice: "Tài khoản affiliate của bạn đang chờ duyệt.",
      pendingNoticeDetail: "Admin sẽ xem xét và phê duyệt trong 24h. Bạn vẫn có thể xem link referral của mình.",
    },

    // Admin panel
    admin: {
      title: "Admin — Affiliate",
      settings: "Cấu hình",
      affiliates: "Affiliates",
      commissions: "Hoa hồng",
      payouts: "Yêu cầu rút",
      saveSettings: "Lưu cấu hình",
      settingsSaved: "Đã lưu!",
      commissionRate: "Tỷ lệ hoa hồng (%)",
      cookieDays: "Cookie (ngày)",
      minPayout: "Rút tối thiểu ($)",
      programActive: "Kích hoạt chương trình",
      approve: "Duyệt",
      reject: "Từ chối",
      suspend: "Khóa",
      markPaid: "Đánh dấu đã trả",
      noCommissions: "Không có hoa hồng pending.",
      paidSuccess: "Đã đánh dấu.",
      noPayouts: "Chưa có yêu cầu rút nào.",
      payoutReject: "Từ chối",
      payoutPay: "Đánh dấu đã trả",
      payoutStatusRequested: "Chờ xử lý",
      payoutStatusApproved: "Đã duyệt",
      payoutStatusPaid: "Đã trả",
      payoutStatusRejected: "Từ chối",
    },
  },

  en: {
    navLabel: "Affiliate",

    hero: {
      eyebrow: "Affiliate Program",
      title: "Earn 30% recurring commission.",
      subtitle:
        "Refer Dralvo to your community. Every customer you bring earns you 30% every month they stay. No limits, no games.",
      cta: "Become an Affiliate",
      loginCta: "Already a partner? View dashboard",
    },

    how: {
      eyebrow: "How it works",
      title: "3 simple steps.",
      steps: [
        { title: "Sign up", body: "Create a Dralvo account and apply as an affiliate. We'll approve within 24h." },
        { title: "Share your link", body: "Get your unique referral link. Share it on your blog, YouTube, Telegram, or Facebook." },
        { title: "Earn", body: "Customers buy through your link → you earn 30% every month. Withdraw when you reach $50." },
      ],
    },

    commission: {
      eyebrow: "Commission",
      title: "30% lifetime of customer.",
      subtitle: "Every month the customer renews → you get 30%. The longer they stay, the more you earn.",
      items: [
        { label: "Commission rate", value: "30%" },
        { label: "Cookie window", value: "30 days" },
        { label: "Min payout", value: "$50" },
        { label: "Model", value: "Recurring" },
      ],
    },

    why: {
      eyebrow: "Why partner with us",
      title: "Real product. Real numbers.",
      items: [
        { title: "Verified product", body: "EAs backtested on 10 years of real data. Not ghost bots — customers see real results." },
        { title: "Transparent earnings", body: "Real-time dashboard: clicks, conversions, earnings. No delays, no hidden numbers." },
        { title: "Full support", body: "Dedicated Telegram group for affiliates. Content, banners, landing page support." },
        { title: "On-time payouts", body: "Withdraw via bank transfer. Request payout once you hit $50." },
      ],
    },

    cta: {
      eyebrow: "Ready?",
      title: "Start earning today.",
      body: "No capital, no experience needed. Just a community interested in gold trading.",
      button: "Apply now",
    },

    faq: {
      eyebrow: "FAQ",
      title: "Everything you need to know.",
      items: [
        ["Who can become an affiliate?", "Anyone — traders, bloggers, YouTubers, Telegram/Facebook group admins. If you have an audience interested in forex/gold, you're in."],
        ["How do I earn commission?", "A customer buys Dralvo VIP through your link → you earn 30% of the order. Every month they renew → you earn another 30%."],
        ["When can I withdraw?", "Once your pending earnings reach $50. Request a payout — we transfer within 3 business days."],
        ["Is there a limit on referrals?", "No. More customers = more commission. No caps."],
        ["How long does the cookie last?", "30 days. If a customer clicks your link and purchases within 30 days, you get the commission."],
      ],
    },

    dashboard: {
      title: "Affiliate Dashboard",
      statusPending: "Pending approval",
      statusActive: "Active",
      statusSuspended: "Suspended",
      statusRejected: "Rejected",
      referralLink: "Your referral link",
      copyLink: "Copy",
      copied: "Copied!",
      stats: {
        clicks: "Clicks",
        conversions: "Conversions",
        conversionRate: "Conversion rate",
        pendingEarnings: "Pending earnings",
        totalEarned: "Total earned",
        paidOut: "Paid out",
        available: "Available",
      },
      commissions: {
        title: "Commission history",
        empty: "No commissions yet.",
        amount: "Amount",
        source: "Order",
        status: "Status",
        date: "Date",
        statusPending: "Pending",
        statusPaid: "Paid",
        statusCancelled: "Cancelled",
        statusRefunded: "Refunded",
      },
      requestPayout: "Request payout",
      requesting: "Sending...",
      payoutRequested: "Payout requested",
      payoutPendingDetail: "Admin is processing it. We'll transfer within 3 business days.",
      payoutSuccess: "Payout request sent!",
      payoutError: "Couldn't send the request. Try again later.",
      payoutMethodTitle: "Payout details",
      payoutRegionVn: "VN bank",
      payoutRegionUsdt: "USDT (international)",
      payoutBank: "Bank / Wallet",
      payoutBankPlaceholder: "Select bank",
      payoutAccount: "Account number",
      payoutHolder: "Account holder",
      payoutNetwork: "Network",
      payoutAddress: "USDT wallet address",
      payoutSubmittedTo: "Paid to",
      payoutErrInvalidBank: "Pick a valid bank.",
      payoutErrInvalidAccount: "Account number must be 6–19 digits.",
      payoutErrInvalidHolder: "Enter the account holder name.",
      payoutErrInvalidNetwork: "Pick a USDT network.",
      payoutErrInvalidAddress: "Wallet address is invalid for the chosen network.",
      notEligible: "Need $50 to withdraw",
      notAffiliateTitle: "You're not an affiliate yet",
      notAffiliateBody: "Apply now to get your referral link and start earning 30% commission from customers you refer.",
      applyNow: "Apply now",
      applying: "Applying...",
      howTitle: "How it works",
      howSteps: [
        "Apply — admin approves within 24h",
        "Get your unique referral link",
        "Share your link — earn 30% commission every month",
      ],
      pendingNotice: "Your affiliate account is pending approval.",
      pendingNoticeDetail: "Admin will review and approve within 24h. You can still view your referral link.",
    },

    admin: {
      title: "Admin — Affiliate",
      settings: "Settings",
      affiliates: "Affiliates",
      commissions: "Commissions",
      payouts: "Payout requests",
      saveSettings: "Save settings",
      settingsSaved: "Saved!",
      commissionRate: "Commission rate (%)",
      cookieDays: "Cookie (days)",
      minPayout: "Min payout ($)",
      programActive: "Program active",
      approve: "Approve",
      reject: "Reject",
      suspend: "Suspend",
      markPaid: "Mark paid",
      noCommissions: "No pending commissions.",
      paidSuccess: "Marked as paid.",
      noPayouts: "No payout requests yet.",
      payoutReject: "Reject",
      payoutPay: "Mark paid",
      payoutStatusRequested: "Requested",
      payoutStatusApproved: "Approved",
      payoutStatusPaid: "Paid",
      payoutStatusRejected: "Rejected",
    },
  },
});
