import { withLocaleFallback } from "@/lib/i18n";

/** Chrome/UI strings for the blog (article body comes from the DB per locale). */
export const BLOG_UI = withLocaleFallback({
  "pt-BR": {
    eyebrow: "Blog Dralvo",
    indexTitle: "Conhecimento sobre negociação de ouro e robôs XAUUSD",
    indexIntro:
      "Guias, análises e lições sobre negociação automatizada de ouro com Expert Advisors no MetaTrader 5 — transparente, sem martingale, sem grid.",
    home: "Início",
    signIn: "Entrar",
    readMore: "Ler mais",
    minRead: "min de leitura",
    tableOfContents: "Índice",
    faqTitle: "Perguntas frequentes",
    empty: "Ainda não há artigos. Volte em breve.",
    backToBlog: "← Todos os artigos",
    ctaTitle: "Comece a negociar ouro de forma automatizada",
    ctaBody: "Obtenha o robô TiGold gratuitamente via IB, ou desbloqueie tudo com o Dralvo VIP.",
    ctaButton: "Ver produtos",
    updated: "Atualizado",
    published: "Publicado",
  },
  es: {
    eyebrow: "Blog de Dralvo",
    indexTitle: "Conocimiento sobre trading de oro y robots XAUUSD",
    indexIntro:
      "Guías, análisis y lecciones sobre trading automatizado de oro con Expert Advisors en MetaTrader 5: transparente, sin martingale, sin grid.",
    home: "Inicio",
    signIn: "Iniciar sesión",
    readMore: "Leer más",
    minRead: "min de lectura",
    tableOfContents: "Índice de contenidos",
    faqTitle: "Preguntas frecuentes",
    empty: "Aún no hay artículos. Vuelva pronto.",
    backToBlog: "← Todos los artículos",
    ctaTitle: "Comience a operar oro de forma automatizada",
    ctaBody: "Obtenga el robot TiGold gratis a través de IB, o desbloquee todo con Dralvo VIP.",
    ctaButton: "Ver productos",
    updated: "Actualizado",
    published: "Publicado",
  },
  id: {
    eyebrow: "Blog Dralvo",
    indexTitle: "Pengetahuan perdagangan emas & robot XAUUSD",
    indexIntro:
      "Panduan, analisis, dan pembelajaran tentang perdagangan emas otomatis dengan Expert Advisor MetaTrader 5 — transparan, tanpa martingale, tanpa grid.",
    home: "Beranda",
    signIn: "Masuk",
    readMore: "Selengkapnya",
    minRead: "menit baca",
    tableOfContents: "Daftar isi",
    faqTitle: "Pertanyaan yang sering diajukan",
    empty: "Belum ada artikel. Silakan kembali lagi nanti.",
    backToBlog: "← Semua artikel",
    ctaTitle: "Mulai perdagangan emas otomatis",
    ctaBody: "Dapatkan robot TiGold secara gratis melalui IB, atau buka seluruh fitur dengan Dralvo VIP.",
    ctaButton: "Lihat produk",
    updated: "Diperbarui",
    published: "Diterbitkan",
  },
  ar: {
    eyebrow: "مدونة Dralvo",
    indexTitle: "معرفة تداول الذهب وروبوت XAUUSD",
    indexIntro:
      "أدلة وتحليلات ودروس حول تداول الذهب الآلي باستخدام خبراء MetaTrader 5 (Expert Advisors) — بشفافية، دون martingale، دون grid.",
    home: "الرئيسية",
    signIn: "تسجيل الدخول",
    readMore: "اقرأ المزيد",
    minRead: "دقيقة قراءة",
    tableOfContents: "جدول المحتويات",
    faqTitle: "الأسئلة الشائعة",
    empty: "لا توجد مقالات بعد. عد للاطلاع قريبًا.",
    backToBlog: "← جميع المقالات",
    ctaTitle: "ابدأ تداول الذهب الآلي",
    ctaBody: "احصل على روبوت TiGold مجانًا عبر IB، أو افتح كل الميزات مع Dralvo VIP.",
    ctaButton: "عرض المنتجات",
    updated: "محدَّث",
    published: "منشور",
  },
  vi: {
    eyebrow: "Blog Dralvo",
    indexTitle: "Kiến thức giao dịch vàng & robot XAUUSD",
    indexIntro:
      "Hướng dẫn, phân tích và kinh nghiệm về giao dịch vàng tự động bằng Expert Advisor trên MetaTrader 5 — minh bạch, không martingale, không grid.",
    home: "Trang chủ",
    signIn: "Đăng nhập",
    readMore: "Đọc tiếp",
    minRead: "phút đọc",
    tableOfContents: "Nội dung bài viết",
    faqTitle: "Câu hỏi thường gặp",
    empty: "Chưa có bài viết nào. Quay lại sau nhé.",
    backToBlog: "← Tất cả bài viết",
    ctaTitle: "Bắt đầu giao dịch vàng tự động",
    ctaBody: "Nhận robot TiGold miễn phí qua IB, hoặc mở khóa toàn bộ với Dralvo VIP.",
    ctaButton: "Xem sản phẩm",
    updated: "Cập nhật",
    published: "Đăng",
  },
  en: {
    eyebrow: "Dralvo Blog",
    indexTitle: "Gold trading & XAUUSD robot knowledge",
    indexIntro:
      "Guides, analysis and lessons on automated gold trading with MetaTrader 5 Expert Advisors — transparent, no martingale, no grid.",
    home: "Home",
    signIn: "Sign in",
    readMore: "Read more",
    minRead: "min read",
    tableOfContents: "Table of contents",
    faqTitle: "Frequently asked questions",
    empty: "No articles yet. Check back soon.",
    backToBlog: "← All articles",
    ctaTitle: "Start automated gold trading",
    ctaBody: "Get the TiGold robot free via IB, or unlock everything with Dralvo VIP.",
    ctaButton: "View products",
    updated: "Updated",
    published: "Published",
  },
});
